"""Claims for Attention_Algorithms/DECLARATION.md, family F3 (human effects over time and global figures).

Transcribed from docs/citations/attention_f3_2026-09-28.md (fetched 2026-09-28 by a literature agent; raw texts in the
session scratchpad under attn/f3/). 'tag' is U6 (effects on users) or G (a global figure for the arithmetic of
DECLARATION section 5). 'reading' is the agent's reading, decided after reading the quotes:
  established - causal (randomised or quasi-experimental) evidence of an effect, sign stated in agent_note;
  mixed       - credible studies disagree on sign or size, or the effect is null / tiny;
  weak        - correlational or uncontrolled only;
  figure      - a number used for arithmetic (G claims carry 'value', 'unit', 'year').
Every quote is a verbatim substring of its raw file after html-unescape, removal of '-\\n' joins and whitespace
collapsing (the normalisation of AI_Safety/CORRIGIBILITY_2026/checks/verify_claims.py). PDF ligatures (U+FB01 'fi')
are kept exactly as extracted.
"""

CLAIMS = [
    # ---- Allcott, Braghieri, Eichmeyer, Gentzkow 2020 (AER) -------------------------------------------------------
    {'id': 'f3:1',
     'tag': 'U6',
     'reading': 'established',
     'source': 'Allcott, Braghieri, Eichmeyer & Gentzkow, "The Welfare Effects of Social Media", American Economic Review 110(3):629-76',
     'version': 'author version dated November 8, 2019 (published AER vol. 110 no. 3, March 2020, per aeaweb.org page fetched 2026-09-28)',
     'url': 'https://web.stanford.edu/~gentzkow/research/facebook.pdf',
     'quote': ['Our overall index of subjective well-being improved by 0.09 standard deviations.',
               'However, we also show that the magnitudes of our causal eﬀects are far smaller than those we would have estimated using the correlational approach of much prior literature.'],
     'raw_file': 'attn/f3/allcott2020_welfare.txt',
     'agent_note': 'RCT (Facebook deactivation, 4 weeks, US 2018). Sign: deactivation IMPROVES subjective well-being '
                   '(harm of use); size small, +0.09 SD; causal estimate far below the correlational one.'},
    {'id': 'f3:2',
     'tag': 'U6',
     'reading': 'established',
     'source': 'Allcott, Braghieri, Eichmeyer & Gentzkow 2020, AER 110(3):629-76',
     'version': 'author version dated November 8, 2019 (published AER March 2020)',
     'url': 'https://web.stanford.edu/~gentzkow/research/facebook.pdf',
     'quote': ['Deactivating Facebook freed up 60 minutes per day for the average person in our Treatment group.',
               'Several weeks later, the Treatment group’s reported usage of the Facebook mobile app was about 11 minutes (22 percent) lower than in Control.'],
     'raw_file': 'attn/f3/allcott2020_welfare.txt',
     'agent_note': 'RCT. Sign: a pause from the feed PERSISTENTLY lowers later use (22% lower several weeks after), '
                   'consistent with habit formation; 60 min/day freed while deactivated.'},
    # ---- Allcott, Gentzkow, Song 2022 (AER) ----------------------------------------------------------------------
    {'id': 'f3:3',
     'tag': 'U6',
     'reading': 'established',
     'source': 'Allcott, Gentzkow & Song, "Digital Addiction", American Economic Review 112(7):2424-63 (NBER WP 28936)',
     'version': 'NBER Working Paper 28936, June 2021, revised March 2022 (published AER vol. 112 no. 7, July 2022, per aeaweb.org)',
     'url': 'https://www.nber.org/system/files/working_papers/w28936/w28936.pdf',
     'quote': ['Temporary incentives to reduce social media use have persistent effects, suggesting social media are habit forming.',
               'Allowing people to set limits on their future screen time substantially reduces use, suggesting self-control problems.',
               'The limit treatment reduced FITSBY screen time by 22 minutes per day (16 percent) over 12 weeks.'],
     'raw_file': 'attn/f3/allcott2022_addiction.txt',
     'agent_note': 'RCT (n ~2,000 US adults, 2020). Sign: habit formation and self-control problems are present '
                   '(bonus cut use 56 min/day during incentive, persistence after; limits cut use 22 min/day).'},
    {'id': 'f3:4',
     'tag': 'U6',
     'reading': 'established',
     'source': 'Allcott, Gentzkow & Song 2022, AER 112(7) (NBER WP 28936)',
     'version': 'NBER Working Paper 28936, revised March 2022',
     'url': 'https://www.nber.org/system/files/working_papers/w28936/w28936.pdf',
     'quote': ['Looking at these facts through the lens of our model suggests that self-control problems cause 31 percent of social media use.',
               'statistically insigniﬁcant changes in measures of happiness, life satisfaction, anxiety, and depression.'],
     'raw_file': 'attn/f3/allcott2022_addiction.txt',
     'agent_note': 'Structural estimate on RCT moments: 31% of use caused by self-control problems. Well-being '
                   'effects of the treatments were insignificant on happiness/life satisfaction/anxiety/depression '
                   '(improvement only on concentration/distraction components). Sign of excess use: established; '
                   'sign on mood: not shown.'},
    {'id': 'f3:5',
     'tag': 'U6',
     'reading': 'established',
     'source': 'Hamilton Project (Brookings) policy brief: Allcott, Gentzkow & Song, "Digital addiction: Evidence and policy implications"',
     'version': 'web page fetched 2026-09-28 (no date printed in the fetched text)',
     'url': 'https://www.hamiltonproject.org/publication/paper/digital-addiction-evidence-and-policy-implications/',
     'quote': ['They estimate that self-control problems, exacerbated by habit formation, account for an average of 31 percent (48 minutes per day) of social media use for participants in the experiment.',
               'they contribute less than 10 minutes of excess use per day for 22 percent of participants and more than 60 minutes for another 32 percent.'],
     'raw_file': 'attn/f3/hamilton_addiction.txt',
     'agent_note': 'Same RCT as f3:3-4, by the authors. Heterogeneity: excess use <10 min/day for 22% of '
                   'participants, >60 min/day for 32%. Relevant to f_avoid (use the user would not choose).'},
    # ---- Braghieri, Levy, Makarin 2022 (AER) ---------------------------------------------------------------------
    {'id': 'f3:6',
     'tag': 'U6',
     'reading': 'established',
     'source': 'Braghieri, Levy & Makarin, "Social Media and Mental Health", American Economic Review 112(11):3660-93',
     'version': 'published AER November 2022 (PDF on author site, journal pagination)',
     'url': 'https://alexeymakarin.github.io/assets/Braghieri_Levy_Makarin_AER_2022.pdf',
     'quote': ['We find that the rollout of Facebook at a college had a negative impact on student mental health.',
               'increased by 0.085 standard deviation units as a result of the introduction of Facebook.',
               'this magnitude is around 22 percent of the effect of losing one’s job on mental health'],
     'raw_file': 'attn/f3/braghieri2022.txt',
     'agent_note': 'Quasi-experiment (staggered Facebook roll-out across US colleges, 2004-06; DiD). Sign: '
                   'HARM, +0.085 SD on a poor-mental-health index (~22% of job loss). Early Facebook, not '
                   'today\'s algorithmic feeds; college students.'},
    # ---- Allcott et al. 2025 emotional state (AEJ: Policy, forthcoming) ------------------------------------------
    {'id': 'f3:7',
     'tag': 'U6',
     'reading': 'established',
     'source': 'Allcott, Gentzkow, Wittenbrink et al. (incl. Meta researchers), "The Effect of Deactivating Facebook and Instagram on Users\' Emotional State", American Economic Journal: Economic Policy (forthcoming); NBER WP 33697',
     'version': 'author PDF (undated); aeaweb.org lists AEJ: Economic Policy (Forthcoming), fetched 2026-09-28',
     'url': 'https://web.stanford.edu/~gentzkow/research/emotional_state.pdf',
     'quote': ['People who deactivated Facebook for the six weeks before the election reported a 0.060 standard deviation improvement in an index of happiness, depression, and anxiety',
               'People who deactivated Instagram for those six weeks reported a 0.041 standard deviation improvement relative to controls.',
               'However, the estimated effect sizes are smaller than benchmarks such as the effects of psychological interventions, nationwide mental health trends, and previous experimental estimates in smaller samples.'],
     'raw_file': 'attn/f3/allcott_emotional.txt',
     'agent_note': 'Two large RCTs (19,857 recruited; US 2020 election). Sign: deactivation improves emotional '
                   'state; size small (+0.060 SD Facebook, +0.041 SD Instagram, the latter not significant at the '
                   'preregistered threshold after multiple-testing adjustment). Not the PNAS 2024 political paper.'},
    # ---- Orben & Przybylski 2019 (NHB) ---------------------------------------------------------------------------
    {'id': 'f3:8',
     'tag': 'U6',
     'reading': 'weak',
     'source': 'Orben & Przybylski, "The association between adolescent well-being and digital technology use", Nature Human Behaviour 3:173-182',
     'version': 'published 14 January 2019 (nature.com article page)',
     'url': 'https://www.nature.com/articles/s41562-018-0506-1',
     'quote': ['The association we find between digital technology use and adolescent well-being is negative but small, explaining at most 0.4% of the variation in well-being.',
               'Taking the broader context of the data into account suggests that these effects are too small to warrant policy change.'],
     'raw_file': 'attn/f3/orben2019_nature.txt',
     'agent_note': 'Specification-curve analysis of three cross-sectional datasets (n = 355,358). Correlational; '
                   'negative sign but at most 0.4% of variance. A critique of the harm thesis.'},
    # ---- Odgers 2024 (Nature book review) ------------------------------------------------------------------------
    {'id': 'f3:9',
     'tag': 'U6',
     'reading': 'mixed',
     'source': 'Odgers, "The great rewiring: is social media really behind an epidemic of teenage mental illness?" (review of Haidt, The Anxious Generation), Nature 628:29-30',
     'version': 'Nature book review, 2024 (article d41586-024-00902-2), fetched 2026-09-28',
     'url': 'https://www.nature.com/articles/d41586-024-00902-2',
     'quote': ['Our efforts have produced a mix of no, small and mixed associations. Most data are correlative.',
               'When associations over time are found, they suggest not that social-media use predicts or causes depression, but that young people who already have mental-health problems use such platforms more often or in different ways from their healthy peers'],
     'raw_file': 'attn/f3/odgers2024.txt',
     'agent_note': 'Expert critique of the harm thesis: associations null/small/mixed, reverse direction where '
                   'longitudinal; still calls for platform reform given time spent.'},
    # ---- WHO Europe HBSC 2024 ------------------------------------------------------------------------------------
    {'id': 'f3:10',
     'tag': 'G',
     'reading': 'figure',
     'source': 'WHO Regional Office for Europe, "Teens, screens and mental health" (news release on the HBSC 2021/2022 survey, Volume 6)',
     'version': 'news item dated 25 September 2024',
     'url': 'https://www.who.int/europe/news/item/25-09-2024-teens--screens-and-mental-health',
     'quote': ['a sharp rise in problematic social media use among adolescents, with rates increasing from 7% in 2018 to 11% in 2022.',
               'Girls reported higher levels of problematic social media use than boys (13% vs 9%).'],
     'raw_file': 'attn/f3/who_hbsc2024.txt',
     'agent_note': 'problematic social media use, adolescents aged 11/13/15 = 0.11 (HBSC, ~280,000 respondents, 44 '
                   'countries/regions, 2022; up from 0.07 in 2018). Prevalence, not an effect.',
     'value': 0.11, 'unit': 'share of adolescents (11, 13, 15 y) with problematic social media use, HBSC Europe/central Asia/Canada', 'year': 2022},
    {'id': 'f3:11',
     'tag': 'U6',
     'reading': 'weak',
     'source': 'WHO Regional Office for Europe, "Teens, screens and mental health" (HBSC 2021/2022)',
     'version': 'news item dated 25 September 2024',
     'url': 'https://www.who.int/europe/news/item/25-09-2024-teens--screens-and-mental-health',
     'quote': ['problematic social media use has been associated with less sleep and later bedtimes',
               'Adolescents who are heavy but non-problematic users reported stronger peer support and social connections.'],
     'raw_file': 'attn/f3/who_hbsc2024.txt',
     'agent_note': 'Survey associations only: problematic use goes with less sleep; heavy non-problematic use goes '
                   'with MORE peer support. Sign depends on problematic vs heavy use.'},
    # ---- Ferguson 2024 meta-analysis (critique) and Thrul et al. 2025 reanalysis ---------------------------------
    {'id': 'f3:12',
     'tag': 'U6',
     'reading': 'mixed',
     'source': 'Ferguson, "Do Social Media Experiments Prove a Link With Mental Health: A Methodological and Meta-Analytic Review", Psychology of Popular Media 14(2):201-206',
     'version': 'author-hosted page proof (ppm0000541), fetched 2026-09-28; published 2024/2025',
     'url': 'https://www.christopherjferguson.com/Social%20Media%20Experiments%20Meta.pdf',
     'quote': ['Nonetheless, meta-analytic evidence for causal effects was statistically no different than zero.',
               'the overall estimate for d across studies was 0.088, which was nonsigni ﬁcant and well below the SESOI (r = .10, d = 0.21).',
               'All studies, regardless of outcome, have fairly straightforward weaknesses related to demand characteristics.'],
     'raw_file': 'attn/f3/ferguson2024.txt',
     'agent_note': 'Meta-analysis of 27 experiments: pooled d = 0.088, ns; high heterogeneity; demand '
                   'characteristics. A critique of the harm thesis.'},
    {'id': 'f3:13',
     'tag': 'U6',
     'reading': 'mixed',
     'source': 'Thrul, Devkota, AlJuboori, Regan, Alomairah & Vidal, "Social Media Reduction or Abstinence Interventions Are Providing Mental Health Benefits - Reanalysis of a Published Meta-Analysis", Psychology of Popular Media 14(2):207-209',
     'version': 'PubMed record PMID 40453192 (2025 Apr), fetched 2026-09-28',
     'url': 'https://pubmed.ncbi.nlm.nih.gov/40453192/',
     'quote': ['Stratified analyses indicated that interventions of <1 week resulted in significantly worse mental health outcomes (d = -0.175), while interventions of 1 week or longer resulted in significant improvements (d = 0.156).'],
     'raw_file': 'attn/f3/reanalysis2025_pubmed.txt',
     'agent_note': 'Reanalysis of Ferguson\'s data: the SIGN depends on intervention length (<1 week worse, '
                   '>=1 week better, d = +0.156). Supports a benefit of pauses of >=1 week; sign disagreement by length.'},
    # ---- Burnell et al. 2025 meta-analysis ------------------------------------------------------------------------
    {'id': 'f3:14',
     'tag': 'U6',
     'reading': 'established',
     'source': 'Burnell, Meter, Andrade, Slocum & George, "The effects of social media restriction: Meta-analytic evidence from randomized controlled trials", SSM - Mental Health 7:100459',
     'version': 'RTI publication page (abstract), 2025, fetched 2026-09-28',
     'url': 'https://www.rti.org/publication/the-effects-of-social-media-restriction-meta-analytic-evidence-fr',
     'quote': ['Thirty-two articles fit our criteria and were included in analyses (5544 individuals; 91 effect sizes).',
               'Although significant, the pooled estimates were small in magnitude, suggesting only weak support for the effectiveness of restricting social media use.'],
     'raw_file': 'attn/f3/burnell2025_rti.txt',
     'agent_note': 'Meta-analysis of 32 RCTs (adults/college, mean age 23.4): restriction improves SWB, pooled '
                   'g = 0.17 (95% CI 0.08-0.27). Sign: benefit of restriction; small.'},
    # ---- Lopes et al. 2026 medRxiv meta-analysis ------------------------------------------------------------------
    {'id': 'f3:15',
     'tag': 'U6',
     'reading': 'established',
     'source': 'Lopes, Branje, David, Gennara, Haidt, Rausch, ... Goldfield, "Effect of Social Media Constraints on Mental Health: A Systematic Review and Meta-Analysis of Experiments", medRxiv 10.64898/2026.06.01.26354614',
     'version': 'medRxiv preprint v2, 2026-06-09 (v1 2026-06-02); NOT peer reviewed; read via api.medrxiv.org',
     'url': 'https://www.medrxiv.org/content/10.64898/2026.06.01.26354614v2',
     'quote': ['consistent with a beneficial response for depressive symptoms (g = 0.22; 95% CI, 0.12 to 0.32)',
               'anxiety symptoms (g = 0.19; 95% CI, 0.05 to 0.34)',
               'Heterogeneity was substantial for several outcomes (I2 > 75%).'],
     'raw_file': 'attn/f3/lopes2026_medrxiv.txt',
     'agent_note': 'Preprint meta-analysis of 35 experiments (pooled N = 7,160), co-authored by Haidt and Rausch '
                   '(proponents of the harm thesis). Sign: constraints improve depression, anxiety, stress, '
                   'well-being; small effects, high heterogeneity; mostly 1-3 week interventions in college-age youth.'},
    # ---- Maerevoet et al. 2025 (Frontiers) null RCT ---------------------------------------------------------------
    {'id': 'f3:16',
     'tag': 'U6',
     'reading': 'mixed',
     'source': 'Maerevoet, Van de Casteele, Van de Putte, Debeer, Hoorelbeke, Vansteenkiste & Koster, "Causal effects of social media use on self-esteem, mindfulness, sleep and emotional well-being: a social media restriction study", Frontiers in Public Health 13',
     'version': 'published 30 May 2025 (doi 10.3389/fpubh.2025.1548504)',
     'url': 'https://www.frontiersin.org/journals/public-health/articles/10.3389/fpubh.2025.1548504/full',
     'quote': ['Results indicate a main effect of time for most outcomes, but the implemented SMU restriction did not moderate these effects.',
               'In conclusion, this study found no benefits from a temporary social media reduction on mental health outcomes.'],
     'raw_file': 'attn/f3/frontiers2025_restriction.txt',
     'agent_note': 'Small RCT (n = 67 students, 2 weeks at <=30 min/day, objective logging and actigraphy): NULL '
                   'on self-esteem, mindfulness, sleep and emotional well-being.'},
    # ---- Calvert et al. 2025 JAMA Netw Open (uncontrolled detox) --------------------------------------------------
    {'id': 'f3:17',
     'tag': 'U6',
     'reading': 'weak',
     'source': 'Calvert, Cipriani, ... Torous, "Social Media Detox and Youth Mental Health", JAMA Network Open 8(11):e2545245',
     'version': 'PubMed record PMID 41284297 (2025 Nov 3), fetched 2026-09-28',
     'url': 'https://pubmed.ncbi.nlm.nih.gov/41284297/',
     'quote': ['295 (79.1%) opting into a detox intervention that reduced symptoms anxiety by 16.1%',
               'In this cohort of young adults, reducing social media use for 1 week was associated with reductions in symptoms of depression, anxiety, and insomnia'],
     'raw_file': 'attn/f3/detox2025_jamanetopen_pubmed.txt',
     'agent_note': 'Cohort with an OPTIONAL 1-week detox, no randomised control: pre-post reductions in anxiety '
                   '(16.1%), depression (24.8%), insomnia (14.5%). Uncontrolled, so weak.'},
    # ---- Xiao et al. 2025 JAMA cohort -----------------------------------------------------------------------------
    {'id': 'f3:18',
     'tag': 'U6',
     'reading': 'weak',
     'source': 'Xiao, Meng, Brown, Keyes & Mann, "Addictive Screen Use Trajectories and Suicidal Behaviors, Suicidal Ideation, and Mental Health in US Youths", JAMA 334(3):219-228',
     'version': 'PubMed record PMID 40531519 (JAMA 2025 Jul 15), fetched 2026-09-28',
     'url': 'https://pubmed.ncbi.nlm.nih.gov/40531519/',
     'quote': ['increasing addictive use of social media had a risk ratio of 2.14 [95% CI, 1.61-2.85] for suicidal behaviors',
               'Total screen time at baseline was not associated with outcomes.'],
     'raw_file': 'attn/f3/xiao2025_pubmed.txt',
     'agent_note': 'ABCD cohort (n = 4,285, ages ~10-14): addictive-use trajectories, not screen time, associated '
                   'with suicidal behaviours (RR 2.14). Observational; direction not identified.'},
    # ---- Sleep: He et al. 2020 pilot RCT; Pedersen et al. 2022 SCREENS cluster RCT --------------------------------
    {'id': 'f3:19',
     'tag': 'U6',
     'reading': 'established',
     'source': 'He, Tu, Xiao, Su & Tang, "Effect of restricting bedtime mobile phone use on sleep, arousal, mood, and working memory: A randomized pilot trial", PLoS One 15(2):e0228756',
     'version': 'PubMed record PMID 32040492 (2020 Feb 10), fetched 2026-09-28',
     'url': 'https://pubmed.ncbi.nlm.nih.gov/32040492/',
     'quote': ['Restricting mobile phone use before bedtime for four weeks was effective in reducing sleep latency, increasing sleep duration, improving sleep quality, reducing pre-sleep arousal, and improving positive affect and working memory.'],
     'raw_file': 'attn/f3/he2020_bedtime_pubmed.txt',
     'agent_note': 'Pilot RCT, n = 38 adults, no phone 30 min before bed. Sign: restriction improves sleep. Very '
                   'small; not social-media-specific.'},
    {'id': 'f3:20',
     'tag': 'U6',
     'reading': 'mixed',
     'source': 'Pedersen, Rasmussen, ... Grøntved, "Effects of Limiting Recreational Screen Media Use on Physical Activity and Sleep in Families With Children: A Cluster Randomized Clinical Trial" (SCREENS), JAMA Pediatrics 176(8):741-749',
     'version': 'PubMed record PMID 35604678 (2022 Aug 1), fetched 2026-09-28',
     'url': 'https://pubmed.ncbi.nlm.nih.gov/35604678/',
     'quote': ['No significant between-group mean differences were observed between intervention and control for the electroencephalography-based sleep outcomes.',
               'intention-to-treat between-group mean difference, 45.8 minutes per day'],
     'raw_file': 'attn/f3/screens2022_pubmed.txt',
     'agent_note': 'Cluster RCT (89 families, 2 weeks, screen use <=3 h/week): NULL on EEG sleep; +45.8 min/day '
                   'non-sedentary activity in children. Disagrees with f3:19 on sleep.'},
    # ---- Notifications: Kushlev 2016 (secondary); Fitz 2019 RCT ---------------------------------------------------
    {'id': 'f3:21',
     'tag': 'U6',
     'reading': 'established',
     'source': 'Kushlev, Proulx & Dunn, "\'Silence Your Phones\': Smartphone Notifications Increase Inattention and Hyperactivity Symptoms", CHI 2016 - read via University of Virginia release on ScienceDaily (SECONDARY; ACM and ResearchGate returned 403)',
     'version': 'ScienceDaily release dated 2016-05-09 (URL date), fetched 2026-09-28',
     'url': 'https://www.sciencedaily.com/releases/2016/05/160509191843.htm',
     'quote': ['The results showed that the participants experienced significantly higher levels of inattention and hyperactivity when alerts were turned on.',
               '221 students at the University of British Columbia drawn from the general student population were assigned for one week to maximize phone interruptions'],
     'raw_file': 'attn/f3/kushlev2016_sciencedaily.txt',
     'agent_note': 'Within-subject experiment (n = 221, one week alerts on vs one week off). Sign: notifications '
                   'raise inattention/hyperactivity symptoms. Secondary source; canonical pre-2019 work.'},
    {'id': 'f3:22',
     'tag': 'U6',
     'reading': 'established',
     'source': 'Fitz, Kushlev, Jagannathan, Lewis, Paliwal & Ariely, "Batching smartphone notifications can improve well-being", Computers in Human Behavior 101:84-94',
     'version': 'journal PDF (2019) hosted by author, fetched 2026-09-28',
     'url': 'https://www.kushlev.com/s/2019-Fitz-Batching.pdf',
     'quote': ['we conducted a randomized ﬁeld experiment (n = 237)',
               'participants whose noti ﬁcations were batched three-times-a-day felt more attentive, productive, in a better mood, and in greater control of their phones.'],
     'raw_file': 'attn/f3/fitz2019.txt',
     'agent_note': 'RCT (n = 237, two weeks). Sign: batching notifications 3x/day improves attention, mood, '
                   'sense of control.'},
    {'id': 'f3:23',
     'tag': 'U6',
     'reading': 'mixed',
     'source': 'Fitz et al. 2019, Computers in Human Behavior 101:84-94',
     'version': 'journal PDF (2019) hosted by author',
     'url': 'https://www.kushlev.com/s/2019-Fitz-Batching.pdf',
     'quote': ['In contrast, participants who did not receive noti ﬁcations at all reaped few of those bene ﬁts, but experienced higher levels of anxiety and “fear of missing out ” (FoMO).'],
     'raw_file': 'attn/f3/fitz2019.txt',
     'agent_note': 'Same RCT: switching notifications off entirely did NOT help and raised anxiety/FoMO. The sign '
                   'depends on the design of the pause (predictable batching vs none).'},
    # ---- Heitmayer & Lahlou 2021 -----------------------------------------------------------------------------------
    {'id': 'f3:24',
     'tag': 'G',
     'reading': 'figure',
     'source': 'Heitmayer & Lahlou, "Why are smartphones disruptive? An empirical study of smartphone use in real-life contexts", Computers in Human Behavior 116:106637',
     'version': 'author accepted version, LSE Research Online eprint 107820 (2021), fetched 2026-09-28',
     'url': 'https://researchonline.lse.ac.uk/id/eprint/107820/1/Why_Are_Smartphones_Disruptive_compressed_Final_Submission.pdf',
     'quote': ['Importantly, we find that 89% of smartphone interactions are initiated by users, not by notifications.',
               'about 11% of the full sessions were initiated by notifications, the rest by users'],
     'raw_file': 'attn/f3/heitmayer2021.txt',
     'agent_note': 'share of smartphone sessions started by a notification = 0.11 (N = 37 UK users aged 21-29, '
                   '1,130 interactions, wearable video; phones mostly on silent). All apps, not social media only. '
                   'Direct published value for f_notif; small, non-representative sample.',
     'value': 0.11, 'unit': 'share of smartphone sessions initiated by a notification', 'year': 2021},
    {'id': 'f3:25',
     'tag': 'U6',
     'reading': 'weak',
     'source': 'Heitmayer & Lahlou 2021, Computers in Human Behavior 116:106637',
     'version': 'author accepted version, LSE Research Online eprint 107820',
     'url': 'https://researchonline.lse.ac.uk/id/eprint/107820/1/Why_Are_Smartphones_Disruptive_compressed_Final_Submission.pdf',
     'quote': ['Many users seem to find it difficult to only use their phones briefly, and to only do what they originally intended to do with it.',
               'smartphone use appears to be more purpose -driven when users receive notifications, and more distraction -seeking when it is self -initiated.'],
     'raw_file': 'attn/f3/heitmayer2021.txt',
     'agent_note': 'Observational/qualitative: continuous-scroll feeds lengthen sessions beyond intent; '
                   'self-initiated use is the longer, distraction-seeking kind. Cuts against a notification-only '
                   'account of re-engagement (habit carries most sessions).'},
    # ---- Pielot, Vradi & Park 2018 --------------------------------------------------------------------------------
    {'id': 'f3:26',
     'tag': 'G',
     'reading': 'figure',
     'source': 'Pielot, Vradi & Park, "Dismissed! A Detailed Exploration of How Mobile Phone Users Handle Push Notifications", MobileHCI \'18 (Barcelona)',
     'version': 'MobileHCI 2018 paper PDF (interruptions.net mirror), fetched 2026-09-28; canonical pre-2019 work',
     'url': 'https://www.interruptions.net/literature/Pielot-MobileHCI18.pdf',
     'quote': ['We analyzed 794,525 notiﬁcations from 278 mobile phone users',
               'Our participants received a median number of 56 notiﬁcations per day'],
     'raw_file': 'attn/f3/pielot2018_dismissed.txt',
     'agent_note': 'notifications per user per day (median) = 56 (278 Android users, 2018). All apps.',
     'value': 56.0, 'unit': 'notifications per user per day (median)', 'year': 2018},
    {'id': 'f3:27',
     'tag': 'G',
     'reading': 'figure',
     'source': 'Pielot, Vradi & Park 2018, MobileHCI \'18',
     'version': 'MobileHCI 2018 paper PDF',
     'url': 'https://www.interruptions.net/literature/Pielot-MobileHCI18.pdf',
     'quote': ['notiﬁcations from non-messenger apps are consumed at much lower rates (Email: 15.47%, Social, 26.55%, NonSocial: 16.19%).'],
     'raw_file': 'attn/f3/pielot2018_dismissed.txt',
     'agent_note': 'conversion (notification -> app opened) for social-network notifications = 0.2655 (2018). '
                   'A per-notification open rate, not the share of sessions; bounds how many pushes start sessions.',
     'value': 0.2655, 'unit': 'share of social-network notifications that lead to opening the app', 'year': 2018},
    # ---- DataReportal / Kepios (Manochi) -------------------------------------------------------------------------
    {'id': 'f3:28',
     'tag': 'G',
     'reading': 'figure',
     'source': 'DataReportal (Kepios, with Meltwater and We Are Social), "Digital 2026: Global Overview Report"',
     'version': 'report published October 2025, data to October 2025; web page fetched 2026-09-28',
     'url': 'https://datareportal.com/reports/digital-2026-global-overview-report',
     'quote': ['Kepios analysis reveals that global social media user identities now stand at 5.66 billion, with that figure equivalent to 68.7 percent of the global population.',
               'The total user identities figure increased by 4.8 percent in the 12 months to October 2025'],
     'raw_file': 'attn/f3/datareportal2026.txt',
     'agent_note': 'social media user identities Oct 2025 = 5.66e9 (DataReportal Digital 2026; identities may '
                   'not be unique individuals); annual growth 4.8% to Oct 2025.',
     'value': 5.66e9, 'unit': 'social media user identities (monthly active, worldwide)', 'year': 2025},
    {'id': 'f3:29',
     'tag': 'G',
     'reading': 'figure',
     'source': 'DataReportal, "Global Social Media Statistics" (analysis credited to Manochi)',
     'version': 'live page, figures for the start of April 2026, fetched 2026-09-28',
     'url': 'https://datareportal.com/social-media-users',
     'quote': ['there were 5.79 billion social media “user identities” around the world at the start of April 2026.',
               'That equates to annualised growth of 5.4 percent'],
     'raw_file': 'attn/f3/datareportal_smu.txt',
     'agent_note': 'users 2026 = 5.79e9 social media user identities (DataReportal, April 2026); annualised growth '
                   '5.4% (294 million new identities in 12 months).',
     'value': 5.79e9, 'unit': 'social media user identities (monthly active, worldwide)', 'year': 2026},
    {'id': 'f3:30',
     'tag': 'G',
     'reading': 'figure',
     'source': 'DataReportal, "Global Social Media Statistics" (GWI survey data)',
     'version': 'live page, April 2026 figures, fetched 2026-09-28',
     'url': 'https://datareportal.com/social-media-users',
     'quote': ['spends an average of 18 hours and 36 minutes using social media each week, which includes browsing social networks and watching online videos on platforms like YouTube, TikTok, Instagram, and Facebook.'],
     'raw_file': 'attn/f3/datareportal_smu.txt',
     'agent_note': 'time on social media = 1,116 min/week per user (GWI, internet users 16+, incl. video '
                   'platforms) = 159.4 min/day (derived: 1116/7). Survey self-report, 54 economies.',
     'value': 1116.0, 'unit': 'minutes per week per social media user (GWI, incl. video platforms)', 'year': 2026},
    {'id': 'f3:31',
     'tag': 'G',
     'reading': 'figure',
     'source': 'DataReportal, "Global Social Media Statistics"',
     'version': 'live page, April 2026 figures, fetched 2026-09-28',
     'url': 'https://datareportal.com/social-media-users',
     'quote': ['the world spends over 15 billion hours consuming content on social platforms each day'],
     'raw_file': 'attn/f3/datareportal_smu.txt',
     'agent_note': 'world time on social platforms = 1.5e10 hours/day (DataReportal, 2026). Cross-check for '
                   'users x minutes (5.79e9 x 159.4 min = 1.54e10 h/day).',
     'value': 1.5e10, 'unit': 'hours per day, worldwide, on social platforms', 'year': 2026},
    {'id': 'f3:32',
     'tag': 'G',
     'reading': 'figure',
     'source': 'DataReportal, "Digital 2026: Global Overview Report" (Similarweb App Intelligence, Android)',
     'version': 'report published October 2025, fetched 2026-09-28',
     'url': 'https://datareportal.com/reports/digital-2026-global-overview-report',
     'quote': ['the typical TikTok user spends 1 hour and 37 minutes per day using the platform’s Android app',
               'users opening the platform’s Android app an average of 10 times per day'],
     'raw_file': 'attn/f3/datareportal2026.txt',
     'agent_note': 'TikTok Android time per user = 97 min/day (Similarweb, Aug 2025 data); ~10 opens/day.',
     'value': 97.0, 'unit': 'minutes per day per TikTok Android user', 'year': 2025},
    # ---- Forecast to 2030 (secondary) -----------------------------------------------------------------------------
    {'id': 'f3:33',
     'tag': 'G',
     'reading': 'figure',
     'source': 'BusinessStats, "Number of Worldwide Social Network Users 2017-2030" (SECONDARY aggregator citing Statista Digital Economy Compass, DataReportal, GWI; Statista page itself masks the numbers behind a paywall)',
     'version': 'web page fetched 2026-09-28 (undated; describes 2025 as current year)',
     'url': 'https://businesstats.com/number-of-worldwide-social-network-users/',
     'quote': ['2.73B (2017) → 5.42B (2025) → 6.05B (2030 proj).',
               '2026–2030 projections based on Statista Digital Economy Compass demographic modelling'],
     'raw_file': 'attn/f3/businesstats_forecast.txt',
     'agent_note': 'users 2030 = 6.05e9 (secondary, BusinessStats citing Statista; unique-user basis, 5.42e9 in '
                   '2025, BELOW DataReportal\'s identity count 5.79e9 for 2026: different bases, do not mix). '
                   'Implied growth ~2%/yr for 2028-30. Primary Statista figure not verifiable (paywall).',
     'value': 6.05e9, 'unit': 'social media users (unique, monthly, worldwide), projection', 'year': 2030},
    # ---- Critiques of the evidence base --------------------------------------------------------------------------
    {'id': 'f3:34',
     'tag': 'U6',
     'reading': 'mixed',
     'source': 'Felton, "Notes on Randomized Controlled Trials for Studying Social Media Harms", arXiv:2606.00900 [stat.ME]',
     'version': 'v1, submitted 30 May 2026',
     'url': 'https://arxiv.org/abs/2606.00900',
     'quote': ['published RCTs typically identify effects of a \\textit{local}, or small-scale, intervention: a person is assigned to quit social media, but her immediate peers continue using it in large numbers.',
               'Such global interventions alter both the proximal social environment and the broader culture, potentially harming teenagers who abstain from social media entirely.'],
     'raw_file': 'attn/f3/arxiv_2606.00900.txt',
     'agent_note': 'Methodological critique: deactivation RCTs estimate a local effect and cannot size the '
                   'population-level (global) effect, in either direction. Limits what the established RCT signs '
                   'imply for a whole-platform change.'},
]
