"""Build the queue of every CONSIST and DESCR row across the pinned retrodiction batteries, in battery order,
grouped in batches of five (owner request 2026-09-17, prompt-log entry 61). Deterministic: parses the pinned
outputs only. Run:  uv run python theory/retrodictions/synthesis_batches/build_queue.py > theory/retrodictions/synthesis_batches/QUEUE.md
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
BATTERIES = [
    ("main", "theory/retrodictions/crr_retrodictions.txt", "std"),
    ("daniel", "runs/phaseA/crr_retrodictions.txt", "daniel"),
    ("sharp", "theory/retrodictions/sharp_claims.txt", "std"),
    ("bio", "theory/retrodictions/bio_retrodictions.txt", "std"),
    ("ei", "theory/retrodictions/ei_networks.txt", "std"),
    ("driven", "theory/retrodictions/driven_systems.txt", "std"),
    ("cognitive", "theory/retrodictions/cognitive_collective.txt", "std"),
    ("wild", "theory/retrodictions/wild_systems.txt", "std"),
    ("twenty", "theory/retrodictions/twenty_systems.txt", "std"),
    ("emptiness", "theory/retrodictions/emptiness.txt", "std"),
    ("shannon", "theory/retrodictions/shannon.txt", "std"),
    ("lqg", "theory/retrodictions/loop_gravity.txt", "std"),
]
KEEP = ("CONSIST", "DESCR")
BATCH = 5


def parse_std(text):
    out, cur = [], None
    for line in text.splitlines():
        m = re.match(r"^\[ *(\d+)\] \(([^)]*)\) (.*)$", line)
        if m:
            cur = [m.group(1), m.group(2), m.group(3).strip(), None]; out.append(cur); continue
        m = re.match(r"^\s+GRADE:\s+([A-Z]+)", line)
        if m and cur is not None and cur[3] is None:
            cur[3] = m.group(1)
    return [(f"[{r[0]}]", r[1], r[2], r[3]) for r in out]


def parse_daniel(text):
    out, cur = [], None
    for line in text.splitlines():
        m = re.match(r"^\[([a-z]\d+)\] (.*)$", line)
        if m:
            cur = [m.group(1), "", m.group(2).strip(), None]; out.append(cur); continue
        m = re.search(r"class (\w+) \| .*\| verdict ([A-Z]+)", line)
        if m and cur is not None and cur[3] is None:
            cur[1], cur[3] = m.group(1), m.group(2)
    return [(f"[{r[0]}]", r[1], r[2], r[3]) for r in out]


def main():
    entries = []
    for name, path, kind in BATTERIES:
        text = (ROOT / path).read_text()
        rows = parse_std(text) if kind == "std" else parse_daniel(text)
        for rid, cls, title, grade in rows:
            if grade in KEEP:
                entries.append((name, path, rid, cls, title, grade))
    print("# Synthesis queue: every CONSIST and DESCR row, in battery order, batches of five")
    print()
    print("Generated by `build_queue.py` from the pinned battery outputs (prompt-log entry 61). Each row is to be")
    print("re-read under the SYNTHESIS class (`docs/notes/2026-09-17_synthesis_class.md`) by a batch script")
    print(f"`batch_NN.py` in this folder with a pinned `batch_NN.txt`. Total {len(entries)} rows, {-(-len(entries) // BATCH)} batches.")
    print()
    counts = {}
    for e in entries:
        counts[e[5]] = counts.get(e[5], 0) + 1
    print("Counts: " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())))
    print()
    print("| # | batch | battery | row | class | grade | title |")
    print("|---|---|---|---|---|---|---|")
    for i, (name, path, rid, cls, title, grade) in enumerate(entries, 1):
        b = (i - 1) // BATCH + 1
        print(f"| {i} | {b:02d} | {name} (`{path}`) | {rid} | {cls} | {grade} | {title.replace('|', '/')} |")


if __name__ == "__main__":
    main()
