"""Claims for Life_Sciences/DECLARATION_1.md OL-1 and DS-4, transcribed from docs/citations/life_origin_2026-09-26.md and
docs/citations/life_sequencing_2026-09-26.md (fetched 2026-09-26; raw texts in the session scratchpad life/origin/ and life/seq/).
'proposed' is the source agent's reading; 'reading' is the investigator's, decided after reading the quotes; every change carries
a 'change' note (three cells, all to SILENT; grade_origin.py prints the grading under both).
DS-4's fold figures are the quoted ones: 'varies by a factor of 40' (per generation) and 'varies more than 120-fold' (per year).
"""

CLAIMS = [{'theory': 'T1',
  'name': 'RNA world',
  'ingredient': 'I1',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'The fetched texts posit RNA replication but do not state a self-sustaining cycle as a requirement. The '
          'cycles they name are environmental drives (wet-dry, freeze-thaw), external to the system, e.g. RW26: '
          "'repeated wet-dry and freeze–thaw cycles acted on exposed environments'. Gilbert 1986 (the original) is "
          'paywalled; no text read.',
  'proposed': 'SILENT'},
 {'theory': 'T1',
  'name': 'RNA world',
  'ingredient': 'I2',
  'reading': 'CONTAINS',
  'source': 'Robertson MP, Joyce GF. The origins of the RNA world. Cold Spring Harb Perspect Biol 4(5):a003608',
  'version': '2012-05-01; PubMed abstract (PMID 20739415); full text not retrievable (see access notes)',
  'url': 'https://doi.org/10.1101/cshperspect.a003608',
  'quote': ['genetic continuity was assured by the replication of RNA'],
  'raw_file': 'life/origin/pubmed_robertson_joyce2012.txt',
  'note': 'Heredity by template replication. The bounded-strength part of I2 is the error threshold (see T4); the '
          'fetched RNA-world texts quoted here do not state it themselves.',
  'proposed': 'CONTAINS'},
 {'theory': 'T1',
  'name': 'RNA world',
  'ingredient': 'I2',
  'reading': 'CONTAINS',
  'source': 'Vázquez-Salazar A. Complex and Messy Prebiotic Chemistry: Obstacles and Opportunities for an RNA World. '
            'Life (Basel) 16(2):240',
  'version': '2026-02-02; PMC12942124 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life16020240',
  'quote': ['Within a local compartment, a heritable RNA sequence can undergo imperfect templated copying'],
  'raw_file': 'life/origin/rnaworld_life2026.txt',
  'note': 'Imperfect templated copying: heredity seeded by the past template, with error.',
  'proposed': 'CONTAINS'},
 {'theory': 'T1',
  'name': 'RNA world',
  'ingredient': 'I3',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "No statement found that replication events rather than clock time set the system's timescale.",
  'proposed': 'SILENT'},
 {'theory': 'T1',
  'name': 'RNA world',
  'ingredient': 'I4',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No path-length or minimal-path statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T1',
  'name': 'RNA world',
  'ingredient': 'I5',
  'reading': 'SILENT',
  'source': 'Vázquez-Salazar A. Complex and Messy Prebiotic Chemistry: Obstacles and Opportunities for an RNA World. '
            'Life (Basel) 16(2):240',
  'version': '2026-02-02; PMC12942124 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life16020240',
  'quote': ['without implying that complex mixtures are intrinsically directed toward specific outcomes',
            'without assuming that any specific outcome was predetermined'],
  'raw_file': 'life/origin/rnaworld_life2026.txt',
  'note': 'Weak: a methodological disclaimer of directedness in a 2026 review, not a core axiom of the RNA-world '
          'hypothesis. The investigator may prefer SILENT.',
  'proposed': 'CONTAINS',
  'change': 'SILENT: a methodological disclaimer of directedness in a 2026 review, not a statement of the RNA-world '
            'hypothesis (the agent flagged it as weak)'},
 {'theory': 'T1',
  'name': 'RNA world',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Robertson MP, Joyce GF. The origins of the RNA world. Cold Spring Harb Perspect Biol 4(5):a003608',
  'version': '2012-05-01; PubMed abstract (PMID 20739415); full text not retrievable (see access notes)',
  'url': 'https://doi.org/10.1101/cshperspect.a003608',
  'quote': ['There is now strong evidence indicating that an RNA World did indeed exist before DNA- and protein-based '
            'life. However, arguments regarding whether life on Earth began with RNA are more tenuous.'],
  'raw_file': 'life/origin/pubmed_robertson_joyce2012.txt',
  'note': 'Status as stated by Robertson & Joyce 2012.',
  'proposed': 'PRED'},
 {'theory': 'T1',
  'name': 'RNA world',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Vázquez-Salazar A. Complex and Messy Prebiotic Chemistry: Obstacles and Opportunities for an RNA World. '
            'Life (Basel) 16(2):240',
  'version': '2026-02-02; PMC12942124 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life16020240',
  'quote': ['in vitro evolution has produced RNA replicases capable of extending templates and, in recent work, '
            'sustaining adaptive evolution in RNA-only systems'],
  'raw_file': 'life/origin/rnaworld_life2026.txt',
  'note': 'Experimental status, 2026 review.',
  'proposed': 'PRED'},
 {'theory': 'T1',
  'name': 'RNA world',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': "Lancet D, Segrè D, Kahana A. Twenty years of 'Lipid World': a fertile partnership with David Deamer. Life "
            '(Basel) 9(4):77',
  'version': '2019-09-20; PMC6958426 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life9040077',
  'quote': ['Our findings falsify the existence of an ancient RNA world'],
  'raw_file': 'life/origin/lancet2019_lipidworld.txt',
  'note': 'A contrary claim by other authors, quoted inside Lancet et al. 2019; recorded as a sign that the status is '
          'contested, not as a verdict.',
  'proposed': 'PRED'},
 {'theory': 'T2',
  'name': 'Metabolism-first (iron-sulfur world / reverse Krebs)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': 'Wächtershäuser G. Evolution of the first metabolic cycles. PNAS 87(1):200-204',
  'version': '1990-01; PubMed abstract (PMID 2296579)',
  'url': 'https://doi.org/10.1073/pnas.87.1.200',
  'quote': ['I here propose the hypothesis that this process is an autocatalytic cycle',
            'The cycle is catalytic for pyrite formation and autocatalytic for its own multiplication.'],
  'raw_file': 'life/origin/pubmed_wachtershauser1990.txt',
  'note': '',
  'proposed': 'CONTAINS'},
 {'theory': 'T2',
  'name': 'Metabolism-first (iron-sulfur world / reverse Krebs)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': 'Morowitz HJ, Kostelnik JD, Yang J, Cody GD. The origin of intermediary metabolism. PNAS 97(14):7704-7708',
  'version': '2000-07-05; PubMed abstract (PMID 10859347)',
  'url': 'https://doi.org/10.1073/pnas.110153997',
  'quote': ['the reductive citric acid cycle is an engine of synthesis, taking in CO(2) and synthesizing the molecules '
            'of the cycle'],
  'raw_file': 'life/origin/pubmed_morowitz2000.txt',
  'note': '',
  'proposed': 'CONTAINS'},
 {'theory': 'T2',
  'name': 'Metabolism-first (iron-sulfur world / reverse Krebs)',
  'ingredient': 'I2',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "Metabolism-first sources do not state template heredity. MU19 concedes the limit: 'Although the ability of "
          "simple reaction networks to evolve is limited in the absence of a genetic mechanism'. PRE20 names the link "
          "as open: 'A cell-like energy-coupling system could only be persistent over time if it can be inherited'. "
          'Neither states an incompatible claim, so SILENT rather than CONFLICTS.',
  'proposed': 'SILENT'},
 {'theory': 'T2',
  'name': 'Metabolism-first (iron-sulfur world / reverse Krebs)',
  'ingredient': 'I3',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No own-clock statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T2',
  'name': 'Metabolism-first (iron-sulfur world / reverse Krebs)',
  'ingredient': 'I4',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "No path-length statement. W90's 'retrodictively constructed' refers to inferring the ancestral cycle from "
          'the extant one, not to a path metric.',
  'proposed': 'SILENT'},
 {'theory': 'T2',
  'name': 'Metabolism-first (iron-sulfur world / reverse Krebs)',
  'ingredient': 'I5',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No statement on teleology or anticipation found.',
  'proposed': 'SILENT'},
 {'theory': 'T2',
  'name': 'Metabolism-first (iron-sulfur world / reverse Krebs)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Wächtershäuser G. Evolution of the first metabolic cycles. PNAS 87(1):200-204',
  'version': '1990-01; PubMed abstract (PMID 2296579)',
  'url': 'https://doi.org/10.1073/pnas.87.1.200',
  'quote': ['an autocatalytic cycle that can be retrodictively constructed from the extant reductive citric acid cycle '
            'by replacing thioesters by thioacids and by assuming that the required reducing power is obtained from '
            'the oxidative formation of pyrite (FeS2)',
            'the postulated cycle cannot exist as a single isolated cycle but must be a member of a network of '
            'concatenated homologous cycles'],
  'raw_file': 'life/origin/pubmed_wachtershauser1990.txt',
  'note': 'Signature claims (1990).',
  'proposed': 'PRED'},
 {'theory': 'T2',
  'name': 'Metabolism-first (iron-sulfur world / reverse Krebs)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Muchowska KB, Varma SJ, Chevallot-Beroux E, Lethuillier-Karl L, Li G, Moran J. Metals promote sequences '
            'of the reverse Krebs cycle. Nat Ecol Evol 1:1716-1721',
  'version': '2017; PMC5659384 (Europe PMC full-text XML, author manuscript)',
  'url': 'https://doi.org/10.1038/s41559-017-0311-7',
  'quote': ['Here we report non-enzymatic promotion of multiple reactions of the rTCA cycle in consecutive sequence, '
            'whereby 6 of its 11 reactions are promoted by Zn2+, Cr3+ and Fe0 in an acidic aqueous solution.',
            'A notable criticism by Orgel concerning the hypothesis of a prebiotic complete rTCA cycle is the '
            'difficulty for simple non-enzymatic catalysts to promote the reactions of the cycle over parasitic '
            'reactions with sufficient selectivity to achieve the theoretical 50% efficiency threshold such that '
            'autocatalysis could self-sustain or self-amplify.'],
  'raw_file': 'life/origin/muchowska2017_revkrebs.txt',
  'note': 'Partial support plus the standing criticism.',
  'proposed': 'PRED'},
 {'theory': 'T2',
  'name': 'Metabolism-first (iron-sulfur world / reverse Krebs)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Muchowska KB, Varma SJ, Moran J. Synthesis and breakdown of universal metabolic precursors promoted by '
            'iron. Nature 569:104-107',
  'version': '2019; PMC6517266 (NCBI efetch PMC XML, author manuscript)',
  'url': 'https://doi.org/10.1038/s41586-019-1151-1',
  'quote': ['build up nine of the eleven Krebs (tricarboxylic acid, TCA) cycle intermediates, including all five '
            'universal metabolic precursors'],
  'raw_file': 'life/origin/muchowska2019_iron.txt',
  'note': "Status 2019. The source's numbers are transcribed, not recomputed (R1).",
  'proposed': 'PRED'},
 {'theory': 'T3',
  'name': 'Autocatalytic sets (Kauffman; RAF, Hordijk & Steel)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': "Hordijk W, Steel M. Autocatalytic networks at the basis of life's origin and organization. Life (Basel) "
            '8(4):62',
  'version': '2018-12; PMC6315399 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life8040062',
  'quote': ['An autocatalytic set thus forms a catalytically closed (RA) and self-sustaining (F) reaction network (or '
            'RAF).'],
  'raw_file': 'life/origin/hordijk_steel2018_life.txt',
  'note': 'Catalytic closure is the cycle in network form. It is a closed loop of catalysis, not necessarily a single '
          'cyclic pathway.',
  'proposed': 'CONTAINS'},
 {'theory': 'T3',
  'name': 'Autocatalytic sets (Kauffman; RAF, Hordijk & Steel)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': 'Hordijk W, Kauffman SA, Steel M. Required levels of catalysis for emergence of autocatalytic sets in '
            'models of chemical reaction systems. Int J Mol Sci 12(5):3085-3101',
  'version': '2011; PMC3116177 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/ijms12053085',
  'quote': ['The formation of a self-sustaining autocatalytic chemical network is a necessary but not sufficient '
            'condition for the origin of life.'],
  'raw_file': 'life/origin/hordijk_kauffman_steel2011.txt',
  'note': '',
  'proposed': 'CONTAINS'},
 {'theory': 'T3',
  'name': 'Autocatalytic sets (Kauffman; RAF, Hordijk & Steel)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': 'Kauffman SA. Autocatalytic sets of proteins. J Theor Biol 119(1):1-24',
  'version': '1986-03-07; PubMed abstract (PMID 3713221)',
  'url': 'https://doi.org/10.1016/s0022-5193(86)80047-9',
  'quote': ['the emergence of reflexively autocatalytic sets of peptides and polypeptides may be an essentially '
            'inevitable collective property of any sufficiently complex set of polypeptides'],
  'raw_file': 'life/origin/pubmed_kauffman1986.txt',
  'note': '',
  'proposed': 'CONTAINS'},
 {'theory': 'T3',
  'name': 'Autocatalytic sets (Kauffman; RAF, Hordijk & Steel)',
  'ingredient': 'I2',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "No template heredity is stated. HS18 speaks of evolvability, not heredity: 'This property provides one of "
          "the necessary conditions for autocatalytic sets to be potentially evolvable'.",
  'proposed': 'SILENT'},
 {'theory': 'T3',
  'name': 'Autocatalytic sets (Kauffman; RAF, Hordijk & Steel)',
  'ingredient': 'I3',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No own-clock statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T3',
  'name': 'Autocatalytic sets (Kauffman; RAF, Hordijk & Steel)',
  'ingredient': 'I4',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No path-length statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T3',
  'name': 'Autocatalytic sets (Kauffman; RAF, Hordijk & Steel)',
  'ingredient': 'I5',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No statement on teleology or anticipation found.',
  'proposed': 'SILENT'},
 {'theory': 'T3',
  'name': 'Autocatalytic sets (Kauffman; RAF, Hordijk & Steel)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Hordijk W, Kauffman SA, Steel M. Required levels of catalysis for emergence of autocatalytic sets in '
            'models of chemical reaction systems. Int J Mol Sci 12(5):3085-3101',
  'version': '2011; PMC3116177 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/ijms12053085',
  'quote': ['a linear growth rate in the level of catalysis (with increasing length n of the largest molecules in the '
            'system) is sufficient for autocatalytic sets to arise spontaneously'],
  'raw_file': 'life/origin/hordijk_kauffman_steel2011.txt',
  'note': 'Signature quantitative claim of the RAF programme.',
  'proposed': 'PRED'},
 {'theory': 'T3',
  'name': 'Autocatalytic sets (Kauffman; RAF, Hordijk & Steel)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': "Hordijk W, Steel M. Autocatalytic networks at the basis of life's origin and organization. Life (Basel) "
            '8(4):62',
  'version': '2018-12; PMC6315399 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life8040062',
  'quote': ['contrary to most of the other models, various experimental chemical examples of autocatalytic sets do '
            'exist'],
  'raw_file': 'life/origin/hordijk_steel2018_life.txt',
  'note': 'Empirical status as stated by the authors.',
  'proposed': 'PRED'},
 {'theory': 'T3',
  'name': 'Autocatalytic sets (Kauffman; RAF, Hordijk & Steel)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Kauffman SA. Autocatalytic sets of proteins. J Theor Biol 119(1):1-24',
  'version': '1986-03-07; PubMed abstract (PMID 3713221)',
  'url': 'https://doi.org/10.1016/s0022-5193(86)80047-9',
  'quote': ['Recombinant DNA procedures, cloning random DNA coding sequences into expression vectors, afford a direct '
            'avenue to test the distribution of catalytic capacities in peptide space'],
  'raw_file': 'life/origin/pubmed_kauffman1986.txt',
  'note': "Kauffman's proposed test (1986).",
  'proposed': 'PRED'},
 {'theory': 'T4',
  'name': 'Hypercycle and error threshold (Eigen; Eigen & Schuster)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': "Hordijk W, Steel M. Autocatalytic networks at the basis of life's origin and organization. Life (Basel) "
            '8(4):62',
  'version': '2018-12; PMC6315399 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life8040062',
  'quote': ['They consist of a cyclic arrangement of catalytic polymers, each one catalyzing both its own replication '
            'as well as that of the next one in the cycle.'],
  'raw_file': 'life/origin/hordijk_steel2018_life.txt',
  'note': 'The primary sources (Eigen 1971; Eigen & Schuster 1977) are paywalled with no PubMed abstract. The '
          'definition is quoted from reviews.',
  'proposed': 'CONTAINS'},
 {'theory': 'T4',
  'name': 'Hypercycle and error threshold (Eigen; Eigen & Schuster)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': 'Szilágyi A, Zachar I, Scheuring I, Kun Á, Könnyű B, Czárán T. Ecology and evolution in the RNA world: '
            'dynamics and stability of prebiotic replicator systems. Life (Basel) 7(4):48',
  'version': '2017; PMC5745561 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life7040048',
  'quote': ['R3 catalyses the replication of R1 and closes the hypercycle'],
  'raw_file': 'life/origin/szilagyi2017_rnaworld.txt',
  'note': '',
  'proposed': 'CONTAINS'},
 {'theory': 'T4',
  'name': 'Hypercycle and error threshold (Eigen; Eigen & Schuster)',
  'ingredient': 'I2',
  'reading': 'CONTAINS',
  'source': 'Szilágyi A, Zachar I, Scheuring I, Kun Á, Könnyű B, Czárán T. Ecology and evolution in the RNA world: '
            'dynamics and stability of prebiotic replicator systems. Life (Basel) 7(4):48',
  'version': '2017; PMC5745561 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life7040048',
  'quote': ['The hypercycle was proposed by Eigen and Schuster [22,41,42,43] as a solution to the error threshold [1], '
            'a severe limit to the information content of primordial biological sequences.',
            'the inequality of the error threshold setting an upper limit to reliably replicable sequence lengths: '
            '(6)L<ln(AW/Am)μ'],
  'raw_file': 'life/origin/szilagyi2017_rnaworld.txt',
  'note': 'Bounded heredity. The error threshold caps the information that copying from the past can carry. This is '
          "the closest existing statement to I2's 'bounded strength'; OL-2 tests it. Equation (6) as extracted reads L "
          '< ln(A_W/A_m)/μ.',
  'proposed': 'CONTAINS'},
 {'theory': 'T4',
  'name': 'Hypercycle and error threshold (Eigen; Eigen & Schuster)',
  'ingredient': 'I2',
  'reading': 'CONTAINS',
  'source': 'Velten H, Pinheiro CF, Castro e Silva A. Extended error threshold mechanism in quasispecies theory via '
            'population dynamics. arXiv:2406.14516',
  'version': 'arXiv v1, submitted 2024-06-20 (only version); PDF text extracted with pypdfium2',
  'url': 'https://arxiv.org/abs/2406.14516',
  'quote': ['p ≪ 1, ln(1 − p) ≈ −p one arrives at the conclusion (1) i.e., pL < ln σ.'],
  'raw_file': 'life/origin/velten2024_arxiv.txt',
  'note': 'A secondary derivation of the Eigen condition, per replication step: pL < ln σ, equivalently Q = (1-p)^L > '
          "1/σ. This matches OL-2's T-N form μ_c = 1 − σ^(−1/L).",
  'proposed': 'CONTAINS'},
 {'theory': 'T4',
  'name': 'Hypercycle and error threshold (Eigen; Eigen & Schuster)',
  'ingredient': 'I3',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'The error rate is stated per replication (per copying event), which is an own-event unit. No statement was '
          'found that own events rather than clock time set the timescale, so SILENT.',
  'proposed': 'SILENT'},
 {'theory': 'T4',
  'name': 'Hypercycle and error threshold (Eigen; Eigen & Schuster)',
  'ingredient': 'I4',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No path-length statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T4',
  'name': 'Hypercycle and error threshold (Eigen; Eigen & Schuster)',
  'ingredient': 'I5',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No statement on teleology or anticipation found.',
  'proposed': 'SILENT'},
 {'theory': 'T4',
  'name': 'Hypercycle and error threshold (Eigen; Eigen & Schuster)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': "Hordijk W, Steel M. Autocatalytic networks at the basis of life's origin and organization. Life (Basel) "
            '8(4):62',
  'version': '2018-12; PMC6315399 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life8040062',
  'quote': ['as far as we are aware, there are no published experimental chemical examples of hypercycles'],
  'raw_file': 'life/origin/hordijk_steel2018_life.txt',
  'note': 'Empirical status (2018).',
  'proposed': 'PRED'},
 {'theory': 'T4',
  'name': 'Hypercycle and error threshold (Eigen; Eigen & Schuster)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Szilágyi A, Zachar I, Scheuring I, Kun Á, Könnyű B, Czárán T. Ecology and evolution in the RNA world: '
            'dynamics and stability of prebiotic replicator systems. Life (Basel) 7(4):48',
  'version': '2017; PMC5745561 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life7040048',
  'quote': ['the hypercycle, is probably the worst performer in almost all of these respects'],
  'raw_file': 'life/origin/szilagyi2017_rnaworld.txt',
  'note': 'A theoretical assessment (2017).',
  'proposed': 'PRED'},
 {'theory': 'T4',
  'name': 'Hypercycle and error threshold (Eigen; Eigen & Schuster)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Biebricher CK, Eigen M. The error threshold. Virus Res 107(2):117-127',
  'version': '2005-02; PubMed abstract (PMID 15649558)',
  'url': 'https://doi.org/10.1016/j.virusres.2004.11.002',
  'quote': ['A consequence of quasispecies is the existence of an error threshold for selective competence.'],
  'raw_file': 'life/origin/pubmed_biebricher_eigen2005.txt',
  'note': 'The error threshold is the signature prediction. Its empirical status in RNA viruses is covered by '
          'Biebricher & Eigen 2005 (abstract only).',
  'proposed': 'PRED'},
 {'theory': 'T5',
  'name': 'Chemoton (Gánti)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': 'Zachar I, Fedor A, Szathmáry E. Two different template replicators coexisting in the same protocell: '
            'stochastic simulation of an extended chemoton model. PLoS One 6(7):e21380',
  'version': '2011; PMC3139576 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.1371/journal.pone.0021380',
  'quote': ['It consists of three autocatalytic subsystems: a metabolic subsystem (self-reproducing chemical cycle), '
            'an informational subsystem (template polymerization cycle) and a boundary subsystem surrounding the '
            'former two (membrane).'],
  'raw_file': 'life/origin/zachar2011_chemoton.txt',
  'note': "Gánti's book (2003) was not fetched. The three subsystems are quoted from Zachar et al. 2011.",
  'proposed': 'CONTAINS'},
 {'theory': 'T5',
  'name': 'Chemoton (Gánti)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': 'Tran QP, Yi R, Fahrenbach AC. Towards a prebiotic chemoton - nucleotide precursor synthesis driven by the '
            'autocatalytic formose reaction. Chem Sci 14:9589',
  'version': '2023-09-13; PMC10498504 (Europe PMC full-text XML)',
  'url': 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10498504/',
  'quote': ['At the heart of the chemoton is a self-sustaining autocatalytic system capable of providing the '
            'substrates for the other two required autocatalytic cycles'],
  'raw_file': 'life/origin/tran2023_chemoton.txt',
  'note': '',
  'proposed': 'CONTAINS'},
 {'theory': 'T5',
  'name': 'Chemoton (Gánti)',
  'ingredient': 'I2',
  'reading': 'CONTAINS',
  'source': 'Zachar I, Fedor A, Szathmáry E. Two different template replicators coexisting in the same protocell: '
            'stochastic simulation of an extended chemoton model. PLoS One 6(7):e21380',
  'version': '2011; PMC3139576 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.1371/journal.pone.0021380',
  'quote': ['By the introduction of an information carrier template molecule, at least limited heredity [10] can be '
            'achieved: when the chemoton reaches a certain size, it splits into daughter spheres, thus it is able to '
            'pass on changes in the template molecules to offspring.'],
  'raw_file': 'life/origin/zachar2011_chemoton.txt',
  'note': "Explicitly 'limited heredity'.",
  'proposed': 'CONTAINS'},
 {'theory': 'T5',
  'name': 'Chemoton (Gánti)',
  'ingredient': 'I3',
  'reading': 'SILENT',
  'source': 'Zachar I, Fedor A, Szathmáry E. Two different template replicators coexisting in the same protocell: '
            'stochastic simulation of an extended chemoton model. PLoS One 6(7):e21380',
  'version': '2011; PMC3139576 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.1371/journal.pone.0021380',
  'quote': ['The chemical reactions of the three subsystems are coupled stoichiometrically, which coordinates the '
            'growth and division of the cell',
            'when the chemoton reaches a certain size, it splits into daughter spheres'],
  'raw_file': 'life/origin/zachar2011_chemoton.txt',
  'note': 'Reading: division is triggered by the own state of the system (size, reached through stoichiometric '
          "coupling), not by an external clock. This is weaker than H-L5's arc-versus-clock claim. The investigator "
          'may prefer SILENT.',
  'proposed': 'CONTAINS',
  'change': 'SILENT: size-triggered division is the chemoton mechanism; nothing is said of own events against clock '
            'time (the agent flagged it as a reading)'},
 {'theory': 'T5',
  'name': 'Chemoton (Gánti)',
  'ingredient': 'I4',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No path-length statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T5',
  'name': 'Chemoton (Gánti)',
  'ingredient': 'I5',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No statement on teleology or anticipation found in the fetched texts. Ginsburg 2015, titled “The '
          'teleological transitions in evolution: A Gántian view” (PMID 25890032), was found by title only in a PubMed '
          'search and not read.',
  'proposed': 'SILENT'},
 {'theory': 'T5',
  'name': 'Chemoton (Gánti)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': "Hordijk W, Steel M. Autocatalytic networks at the basis of life's origin and organization. Life (Basel) "
            '8(4):62',
  'version': '2018-12; PMC6315399 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life8040062',
  'quote': ['there appear to be no published experimental chemical examples of chemotons'],
  'raw_file': 'life/origin/hordijk_steel2018_life.txt',
  'note': 'Empirical status (2018).',
  'proposed': 'PRED'},
 {'theory': 'T5',
  'name': 'Chemoton (Gánti)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Tran QP, Yi R, Fahrenbach AC. Towards a prebiotic chemoton - nucleotide precursor synthesis driven by the '
            'autocatalytic formose reaction. Chem Sci 14:9589',
  'version': '2023-09-13; PMC10498504 (Europe PMC full-text XML)',
  'url': 'https://pmc.ncbi.nlm.nih.gov/articles/PMC10498504/',
  'quote': ['The synthesis of nucleotide precursors fuelled by the formose reaction, one of the most plausible forms '
            'of autocatalysis on the early Earth, is demonstrated, and the relevance to the chemoton model is '
            'discussed.'],
  'raw_file': 'life/origin/tran2023_chemoton.txt',
  'note': 'Partial experimental step (2023).',
  'proposed': 'PRED'},
 {'theory': 'T6',
  'name': 'Compartment-first / Lipid world (GARD; Szostak protocells)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': 'Zhu TF, Szostak JW. Coupled growth and division of model protocell membranes. J Am Chem Soc '
            '131(15):5705-5713',
  'version': '2009; PMC2669828 (Europe PMC full-text XML, author manuscript)',
  'url': 'https://doi.org/10.1021/ja900919c',
  'quote': ['We show that model protocells can proceed through multiple cycles of reproduction.'],
  'raw_file': 'life/origin/zhu_szostak2009.txt',
  'note': '',
  'proposed': 'CONTAINS'},
 {'theory': 'T6',
  'name': 'Compartment-first / Lipid world (GARD; Szostak protocells)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': "Lancet D, Segrè D, Kahana A. Twenty years of 'Lipid World': a fertile partnership with David Deamer. Life "
            '(Basel) 9(4):77',
  'version': '2019-09-20; PMC6958426 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life9040077',
  'quote': ['It is the ensuing non-trivial concentration-preserving (homeostatic) growth, followed by random fission, '
            'that marks true lipid reproduction'],
  'raw_file': 'life/origin/lancet2019_lipidworld.txt',
  'note': 'A growth–fission cycle.',
  'proposed': 'CONTAINS'},
 {'theory': 'T6',
  'name': 'Compartment-first / Lipid world (GARD; Szostak protocells)',
  'ingredient': 'I2',
  'reading': 'CONTAINS',
  'source': "Lancet D, Segrè D, Kahana A. Twenty years of 'Lipid World': a fertile partnership with David Deamer. Life "
            '(Basel) 9(4):77',
  'version': '2019-09-20; PMC6958426 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life9040077',
  'quote': ['lipid mixed assemblies that grow and split can transmit molecular information from one generation to '
            'another'],
  'raw_file': 'life/origin/lancet2019_lipidworld.txt',
  'note': "Compositional inheritance. On its bound: 'GARD was technically contested in [48] due to poor evolvability' "
          '(same source).',
  'proposed': 'CONTAINS'},
 {'theory': 'T6',
  'name': 'Compartment-first / Lipid world (GARD; Szostak protocells)',
  'ingredient': 'I2',
  'reading': 'CONTAINS',
  'source': 'Zhu TF, Szostak JW. Coupled growth and division of model protocell membranes. J Am Chem Soc '
            '131(15):5705-5713',
  'version': '2009; PMC2669828 (Europe PMC full-text XML, author manuscript)',
  'url': 'https://doi.org/10.1021/ja900919c',
  'quote': ['Encapsulated RNA molecules, representing a primitive genome, are distributed to the daughter vesicles.'],
  'raw_file': 'life/origin/zhu_szostak2009.txt',
  'note': '',
  'proposed': 'CONTAINS'},
 {'theory': 'T6',
  'name': 'Compartment-first / Lipid world (GARD; Szostak protocells)',
  'ingredient': 'I3',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "In ZS09 division is set off by an external event (gentle shear): 'Modest shear forces are then sufficient "
          "to cause the thread-like vesicles to divide'. The theory states no own-clock claim, so SILENT. The "
          'investigator may note that this division cut is environmental (relevant to OL-3).',
  'proposed': 'SILENT'},
 {'theory': 'T6',
  'name': 'Compartment-first / Lipid world (GARD; Szostak protocells)',
  'ingredient': 'I4',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No path-length statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T6',
  'name': 'Compartment-first / Lipid world (GARD; Szostak protocells)',
  'ingredient': 'I5',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No statement on teleology or anticipation found.',
  'proposed': 'SILENT'},
 {'theory': 'T6',
  'name': 'Compartment-first / Lipid world (GARD; Szostak protocells)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Chen IA, Roberts RW, Szostak JW. The emergence of competition between model protocells. Science '
            '305(5689):1474-1476',
  'version': '2004-09-03; PubMed abstract (PMID 15353806)',
  'url': 'https://doi.org/10.1126/science.1100757',
  'quote': ['more efficient RNA replication could cause faster cell growth, leading to the emergence of Darwinian '
            'evolution at the cellular level'],
  'raw_file': 'life/origin/pubmed_chen2004.txt',
  'note': '',
  'proposed': 'PRED'},
 {'theory': 'T6',
  'name': 'Compartment-first / Lipid world (GARD; Szostak protocells)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': "Lancet D, Segrè D, Kahana A. Twenty years of 'Lipid World': a fertile partnership with David Deamer. Life "
            '(Basel) 9(4):77',
  'version': '2019-09-20; PMC6958426 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life9040077',
  'quote': ['Twenty years later, experimental verification is still hard to attain.'],
  'raw_file': 'life/origin/lancet2019_lipidworld.txt',
  'note': 'Status of compositional inheritance (GARD), as stated by its authors.',
  'proposed': 'PRED'},
 {'theory': 'T6',
  'name': 'Compartment-first / Lipid world (GARD; Szostak protocells)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Segré D, Ben-Eli D, Deamer DW, Lancet D. The lipid world. Orig Life Evol Biosph 31(1-2):119-145',
  'version': '2001; PubMed abstract (PMID 11296516)',
  'url': 'https://doi.org/10.1023/a:1006746807104',
  'quote': ['these concepts provide a theoretical framework, and suggest experimental tests for a Lipid World model '
            'for the origin of life'],
  'raw_file': 'life/origin/pubmed_segre2001.txt',
  'note': '',
  'proposed': 'PRED'},
 {'theory': 'T7',
  'name': 'Assembly theory (Cronin, Walker et al.)',
  'ingredient': 'I1',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'AT does not require a cycle; no statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T7',
  'name': 'Assembly theory (Cronin, Walker et al.)',
  'ingredient': 'I2',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "No heredity statement as such. Related: 'the minimal number of operations necessary to construct an "
          "observed object based on objects that could have existed in its past' (SH23) is construction from past "
          'objects, not templated inheritance. Left SILENT.',
  'proposed': 'SILENT'},
 {'theory': 'T7',
  'name': 'Assembly theory (Cronin, Walker et al.)',
  'ingredient': 'I3',
  'reading': 'CONTAINS',
  'source': 'Sharma A, Czégel D, Lachmann M, Kempes CP, Walker SI, Cronin L. Assembly theory explains and quantifies '
            'selection and evolution. Nature 622:321-328',
  'version': '2023; PMC10567559 (Europe PMC full-text XML); arXiv:2206.02279 v3 (2023-03-12)',
  'url': 'https://doi.org/10.1038/s41586-023-06600-9',
  'quote': ['It introduces an ‘assembly time’ that ticks at each object being made: assembly physics includes an '
            'explicit arrow of time intrinsic to the structure of objects.'],
  'raw_file': 'life/origin/sharma2023_assembly.txt',
  'note': "An event-counted clock ('ticks at each object being made'). SH23 also defines clock-rate timescales τd and "
          'τp, so AT uses both kinds of time.',
  'proposed': 'CONTAINS'},
 {'theory': 'T7',
  'name': 'Assembly theory (Cronin, Walker et al.)',
  'ingredient': 'I4',
  'reading': 'CONTAINS',
  'source': 'Sharma A, Czégel D, Lachmann M, Kempes CP, Walker SI, Cronin L. Assembly theory explains and quantifies '
            'selection and evolution. Nature 622:321-328',
  'version': '2023; PMC10567559 (Europe PMC full-text XML); arXiv:2206.02279 v3 (2023-03-12)',
  'url': 'https://doi.org/10.1038/s41586-023-06600-9',
  'quote': ['For each object, the most important feature is the assembly index ai, which corresponds to the shortest '
            'number of steps required to generate the object from basic building blocks.',
            'This can be quantified as the length of the shortest assembly pathway that can generate the object (Fig. '
            '1).'],
  'raw_file': 'life/origin/sharma2023_assembly.txt',
  'note': 'The assembly index is a minimal path: the analogue of the chord C* (D3), not the arc C (D2). AT contrasts '
          "it with the paths actually taken, e.g. 'a vast separation in scales separating the number of objects that "
          "could have been explored versus those that are actually constructed following a particular path'. AT has no "
          'surplus S = C − C* as a quantity. That is a reading, not a finding (declaration OL-1).',
  'proposed': 'CONTAINS'},
 {'theory': 'T7',
  'name': 'Assembly theory (Cronin, Walker et al.)',
  'ingredient': 'I4',
  'reading': 'CONTAINS',
  'source': 'Sharma A, et al. Assembly theory explains and quantifies selection and evolution. arXiv:2206.02279 '
            'abstract page',
  'version': 'arXiv v3, last revised 2023-03-12 (v1 2022-06-05)',
  'url': 'https://arxiv.org/abs/2206.02279',
  'quote': ['defined as the minimal number of steps needed to construct the object from basic building blocks'],
  'raw_file': 'life/origin/sharma_abs.txt',
  'note': 'arXiv abstract wording (v3).',
  'proposed': 'CONTAINS'},
 {'theory': 'T7',
  'name': 'Assembly theory (Cronin, Walker et al.)',
  'ingredient': 'I5',
  'reading': 'CONTAINS',
  'source': 'Sharma A, Czégel D, Lachmann M, Kempes CP, Walker SI, Cronin L. Assembly theory explains and quantifies '
            'selection and evolution. Nature 622:321-328',
  'version': '2023; PMC10567559 (Europe PMC full-text XML); arXiv:2206.02279 v3 (2023-03-12)',
  'url': 'https://doi.org/10.1038/s41586-023-06600-9',
  'quote': ['Historical contingency is introduced by assuming that only the knowledge or constraints built on a given '
            'path can be used in the future'],
  'raw_file': 'life/origin/sharma2023_assembly.txt',
  'note': 'Only the past path feeds the future.',
  'proposed': 'CONTAINS'},
 {'theory': 'T7',
  'name': 'Assembly theory (Cronin, Walker et al.)',
  'ingredient': 'I5',
  'reading': 'CONTAINS',
  'source': 'Sharma A, et al. Assembly theory explains and quantifies selection and evolution. arXiv:2206.02279 '
            'abstract page',
  'version': 'arXiv v3, last revised 2023-03-12 (v1 2022-06-05)',
  'url': 'https://arxiv.org/abs/2206.02279',
  'quote': ['To understand how open-ended forms can emerge in a forward-process from physics that does not include '
            'their design'],
  'raw_file': 'life/origin/sharma_abs.txt',
  'note': 'No design: no teleology.',
  'proposed': 'CONTAINS'},
 {'theory': 'T7',
  'name': 'Assembly theory (Cronin, Walker et al.)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Sharma A, Czégel D, Lachmann M, Kempes CP, Walker SI, Cronin L. Assembly theory explains and quantifies '
            'selection and evolution. Nature 622:321-328',
  'version': '2023; PMC10567559 (Europe PMC full-text XML); arXiv:2206.02279 v3 (2023-03-12)',
  'url': 'https://doi.org/10.1038/s41586-023-06600-9',
  'quote': ['This suggests that selectivity in an unknown physical process can be explained by experimentally '
            'detecting the number of objects, their assembly index and copy number as a function of time.'],
  'raw_file': 'life/origin/sharma2023_assembly.txt',
  'note': '',
  'proposed': 'PRED'},
 {'theory': 'T7',
  'name': 'Assembly theory (Cronin, Walker et al.)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Marshall SM, et al. Identifying molecules as biosignatures with assembly theory and mass spectrometry. '
            'Nat Commun 12:3033',
  'version': '2021; PMC8144626 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.1038/s41467-021-23258-x',
  'quote': ['only biologically produced samples produce MA above a certain threshold',
            'Importantly this measurement does not imply that samples with a maximum MA below 15 are non-living'],
  'raw_file': 'life/origin/marshall2021_assembly_ms.txt',
  'note': 'The signature biosignature prediction (a molecular assembly threshold of about 15, per the source). '
          'Published critiques exist but were not fetched here.',
  'proposed': 'PRED'},
 {'theory': 'T8',
  'name': 'Dissipative adaptation (England)',
  'ingredient': 'I1',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "Self-replication is assumed, not a self-sustaining cycle required for origin. The 'division cycle' appears "
          'only as the E. coli example.',
  'proposed': 'SILENT'},
 {'theory': 'T8',
  'name': 'Dissipative adaptation (England)',
  'ingredient': 'I2',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "No heredity statement; 'durability' is the replicator's lifetime, not inheritance.",
  'proposed': 'SILENT'},
 {'theory': 'T8',
  'name': 'Dissipative adaptation (England)',
  'ingredient': 'I3',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "The heat bound is written over one division interval: 'it again after a time interval of τdiv, the typical "
          "duration of a single round of growth and cell division' (EN13). This is the analyst's choice of window, not "
          'a claim that own events set the clock, so SILENT.',
  'proposed': 'SILENT'},
 {'theory': 'T8',
  'name': 'Dissipative adaptation (England)',
  'ingredient': 'I4',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No path-length statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T8',
  'name': 'Dissipative adaptation (England)',
  'ingredient': 'I5',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No statement on teleology or anticipation found. Adaptation is attributed to the history of work absorption '
          '(EN15, HE17) with no forward-looking term. Left SILENT because this is not stated as a principle.',
  'proposed': 'SILENT'},
 {'theory': 'T8',
  'name': 'Dissipative adaptation (England)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'England JL. Statistical physics of self-replication. J Chem Phys 139:121923 (2013)',
  'version': 'arXiv:1209.1179 v1 (2012-09-06, only version); journal version 2013-08-21 not retrievable (pubs.aip.org '
             '403); PDF text extracted with pypdfium2',
  'url': 'https://arxiv.org/abs/1209.1179',
  'quote': ['we will derive a lower bound on the heat output of a self-replicator in terms of its size, growth rate, '
            'entropy, and durability',
            'these calculations also establish that the E. coli bacterium produces an amount of heat less than three '
            'times as large as the absolute physical lower bound dictated by its growth rate, internal entropy '
            'production, and durability'],
  'raw_file': 'life/origin/england2013_arxiv.txt',
  'note': '',
  'proposed': 'PRED'},
 {'theory': 'T8',
  'name': 'Dissipative adaptation (England)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'England JL. Dissipative adaptation in driven self-assembly. Nat Nanotechnol 10(11):919-923',
  'version': '2015-11; PubMed abstract (PMID 26530021)',
  'url': 'https://doi.org/10.1038/nnano.2015.250',
  'quote': ['I propose that they imply a general thermodynamic mechanism for self-organization via dissipation of '
            'absorbed work that may be applicable in a broad class of driven many-body systems'],
  'raw_file': 'life/origin/pubmed_england2015.txt',
  'note': '',
  'proposed': 'PRED'},
 {'theory': 'T8',
  'name': 'Dissipative adaptation (England)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Horowitz JM, England JL. Spontaneous fine-tuning to environment in many-species chemical reaction '
            'networks. PNAS 114(29):7565-7570',
  'version': '2017-07-18; PubMed abstract (PMID 28674005)',
  'url': 'https://doi.org/10.1073/pnas.1700617114',
  'quote': ['We find that the long-time dynamics of such systems are biased toward states that exhibit a fine-tuned '
            'extremization of environmental forcing.'],
  'raw_file': 'life/origin/pubmed_horowitz_england2017.txt',
  'note': 'An in-silico result (2017).',
  'proposed': 'PRED'},
 {'theory': 'T9',
  'name': 'Free-energy principle applied to life (Friston 2013)',
  'ingredient': 'I1',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "The paper names a circular causality ('reminiscent of the action–perception cycle') and a random global "
          'attractor, but not a self-sustaining cycle as an origin requirement. SILENT.',
  'proposed': 'SILENT'},
 {'theory': 'T9',
  'name': 'Free-energy principle applied to life (Friston 2013)',
  'ingredient': 'I2',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No heredity statement.',
  'proposed': 'SILENT'},
 {'theory': 'T9',
  'name': 'Free-energy principle applied to life (Friston 2013)',
  'ingredient': 'I3',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No own-clock statement. The analysis uses ergodic time averages over clock time.',
  'proposed': 'SILENT'},
 {'theory': 'T9',
  'name': 'Free-energy principle applied to life (Friston 2013)',
  'ingredient': 'I4',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No path-length statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T9',
  'name': 'Free-energy principle applied to life (Friston 2013)',
  'ingredient': 'I5',
  'reading': 'SILENT',
  'source': 'Friston K. Life as we know it. J R Soc Interface 10(86):20130475',
  'version': '2013; PMC3730701 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.1098/rsif.2013.0475',
  'quote': ['the internal states will appear to have solved the problem of Bayesian inference by encoding posterior '
            'beliefs about hidden (external) states',
            'The internal dynamics that predict this event appear to emerge in their fluctuations before the event '
            'itself (figure 4)—as would be anticipated if internal events are modelling external events.'],
  'raw_file': 'life/origin/friston2013_life.txt',
  'note': 'Reading: the internal states carry content (beliefs about external states) and anticipate events. This sits '
          "against I5's 'the cut has no content'. No causation from the future is claimed: prediction is built from "
          'past data. So the conflict is with the no-content half of I5, not the no-future half. The investigator '
          'should confirm.',
  'proposed': 'CONFLICTS',
  'change': 'SILENT: content in internal states (posterior beliefs) is not content at the cut, and prediction built '
            'from past data is not being fed by a future; the proposed CONFLICTS reads a different claim'},
 {'theory': 'T9',
  'name': 'Free-energy principle applied to life (Friston 2013)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Friston K. Life as we know it. J R Soc Interface 10(86):20130475',
  'version': '2013; PMC3730701 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.1098/rsif.2013.0475',
  'quote': ['any system that exists will appear to minimize free energy and therefore engage in active inference',
            'The final section uses simulations to provide a proof of principle'],
  'raw_file': 'life/origin/friston2013_life.txt',
  'note': "Status: the paper's evidence is a simulation (proof of principle).",
  'proposed': 'PRED'},
 {'theory': 'T10',
  'name': 'Autopoiesis (Maturana & Varela)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': 'Luisi PL. The minimal autopoietic unit. Orig Life Evol Biosph 44(4):335-338',
  'version': '2014-12; PubMed abstract (PMID 25585801)',
  'url': 'https://doi.org/10.1007/s11084-014-9388-z',
  'quote': ['a living cell is an open system capable of self-maintenance, due to a process of internal '
            'self-regeneration of the components, all within a boundary which is itself product from within'],
  'raw_file': 'life/origin/pubmed_luisi2014.txt',
  'note': 'Reading: closed self-production is the cycle. Luisi paraphrases Varela et al. 1974, which is paywalled '
          "(linkinghub/ScienceDirect 403) with no PubMed abstract. Scope caveat from LU03: autopoiesis is 'not a "
          "theory about the origin of life'.",
  'proposed': 'CONTAINS'},
 {'theory': 'T10',
  'name': 'Autopoiesis (Maturana & Varela)',
  'ingredient': 'I2',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "LU14: 'In this definition (or better operational description) there is no mention of DNA or genetic code.' "
          'This is silence about genetic heredity, not a denial of continuity, so SILENT rather than CONFLICTS.',
  'proposed': 'SILENT'},
 {'theory': 'T10',
  'name': 'Autopoiesis (Maturana & Varela)',
  'ingredient': 'I3',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No own-clock statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T10',
  'name': 'Autopoiesis (Maturana & Varela)',
  'ingredient': 'I4',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No path-length statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T10',
  'name': 'Autopoiesis (Maturana & Varela)',
  'ingredient': 'I5',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "No teleology statement found. BL04 frames cognition 'in contradistinction to the representationalistic "
          "point of view', which could bear on I5's 'no content'. Left SILENT because it is not a claim about the "
          'future or about empty content.',
  'proposed': 'SILENT'},
 {'theory': 'T10',
  'name': 'Autopoiesis (Maturana & Varela)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Luisi PL. The minimal autopoietic unit. Orig Life Evol Biosph 44(4):335-338',
  'version': '2014-12; PubMed abstract (PMID 25585801)',
  'url': 'https://doi.org/10.1007/s11084-014-9388-z',
  'quote': ['there are preliminary experimental data supporting the possible existence of this primitive form of cell '
            'activity'],
  'raw_file': 'life/origin/pubmed_luisi2014.txt',
  'note': '',
  'proposed': 'PRED'},
 {'theory': 'T10',
  'name': 'Autopoiesis (Maturana & Varela)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': "Hordijk W, Steel M. Autocatalytic networks at the basis of life's origin and organization. Life (Basel) "
            '8(4):62',
  'version': '2018-12; PMC6315399 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life8040062',
  'quote': ['some simple autopoietic chemical systems have been constructed experimentally'],
  'raw_file': 'life/origin/hordijk_steel2018_life.txt',
  'note': '',
  'proposed': 'PRED'},
 {'theory': 'T10',
  'name': 'Autopoiesis (Maturana & Varela)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Luisi PL. Autopoiesis: a review and a reappraisal. Naturwissenschaften 90(2):49-59',
  'version': '2003-02; PubMed abstract (PMID 12590297)',
  'url': 'https://doi.org/10.1007/s00114-002-0389-9',
  'quote': ['not an abstract theory, not a concept of artificial life, not a theory about the origin of life-but '
            'rather a pragmatic blueprint of life based on cellular life'],
  'raw_file': 'life/origin/pubmed_luisi2003.txt',
  'note': "Scope: by Luisi's reading, autopoiesis makes no origin-of-life prediction.",
  'proposed': 'PRED'},
 {'theory': 'T11',
  'name': 'Dynamic kinetic stability (Pross)',
  'ingredient': 'I1',
  'reading': 'CONTAINS',
  'source': 'Pascal R, Pross A, Sutherland JD. Towards an evolutionary theory of the origin of life based on kinetics '
            'and thermodynamics. Open Biol 3:130156',
  'version': '2013; PMC3843823 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.1098/rsob.130156',
  'quote': ['This means that any autocatalytic cycle or other replication process must proceed unidirectionally to '
            'display DKS [3].',
            'the process can be represented as a reaction cycle in which the autocatalytic species is recycled and '
            'reproduced (Scheme 3)'],
  'raw_file': 'life/origin/pascal_pross_sutherland2013.txt',
  'note': '',
  'proposed': 'CONTAINS'},
 {'theory': 'T11',
  'name': 'Dynamic kinetic stability (Pross)',
  'ingredient': 'I2',
  'reading': 'CONTAINS',
  'source': 'Pross A, Pascal R. How and why kinetics, thermodynamics, and chemistry induce the logic of biological '
            'evolution. Beilstein J Org Chem 13:665-674',
  'version': '2017; PMC5389199 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3762/bjoc.13.66',
  'quote': ['The storage of genetic information as a sequence in a polymer associated with template replication '
            'through base-pairing constitutes an efficient system to ensure evolvability.'],
  'raw_file': 'life/origin/pross2017_beilstein.txt',
  'note': 'Weak: DKS itself is defined on persistent replicators; template heredity enters as an efficient means, not '
          'as part of the definition.',
  'proposed': 'CONTAINS'},
 {'theory': 'T11',
  'name': 'Dynamic kinetic stability (Pross)',
  'ingredient': 'I3',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'Candidate, not graded: PR23 ties irreversibility to the ratio of the own generation time of the system to '
          "the transition-state lifetime: 'the constraint on the kinetic barrier ΔGr≠ is rather related to time (the "
          'ratio of the duration of two events, namely transition state lifetime and reproduction timescale) than to '
          "thermodynamics'. Generation time is still measured in clock time ('generation times spanning from 1 s to 1 "
          "century'), so SILENT under the conservative rule.",
  'proposed': 'SILENT'},
 {'theory': 'T11',
  'name': 'Dynamic kinetic stability (Pross)',
  'ingredient': 'I4',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': 'No path-length statement found.',
  'proposed': 'SILENT'},
 {'theory': 'T11',
  'name': 'Dynamic kinetic stability (Pross)',
  'ingredient': 'I5',
  'reading': 'SILENT',
  'source': '',
  'version': '',
  'url': '',
  'quote': [],
  'raw_file': '',
  'note': "Candidate, not graded: PPS13 states contingency ('evolution towards subsequent states cannot generally be "
          "predicted by any extrapolation of the present behaviour'). That concerns unpredictability, not future "
          'causation, so SILENT.',
  'proposed': 'SILENT'},
 {'theory': 'T11',
  'name': 'Dynamic kinetic stability (Pross)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Pascal R, Pross A, Sutherland JD. Towards an evolutionary theory of the origin of life based on kinetics '
            'and thermodynamics. Open Biol 3:130156',
  'version': '2013; PMC3843823 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.1098/rsob.130156',
  'quote': ['Another direction of potential interest could be to seek the emergence of autocatalytic cycles in '
            'combinatorial mixtures of prebiotically plausible reactants and activated reagents or energy sources.',
            'A universal scale of DKS seems therefore unattainable from a kinetic point of view'],
  'raw_file': 'life/origin/pascal_pross_sutherland2013.txt',
  'note': 'The proposed research direction, and the stated limit on quantifying DKS.',
  'proposed': 'PRED'},
 {'theory': 'T11',
  'name': 'Dynamic kinetic stability (Pross)',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Pross A, Pascal R. On the Emergence of Autonomous Chemical Systems through Dissipation Kinetics. Life '
            '(Basel) 13(11):2171',
  'version': '2023-11-06; PMC10672272 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life13112171',
  'quote': ['Numerically this treatment leads to kinetic barriers ΔGr≠ exceeding values of 73 and 127 kJ mol−1 at 25 '
            '°C considering generation times spanning from 1 s to 1 century, respectively.'],
  'raw_file': 'life/origin/pross2023_life.txt',
  'note': "A semi-quantitative model prediction (the source's numbers, transcribed).",
  'proposed': 'PRED'},
 {'theory': 'REV',
  'name': 'Preiner et al. 2020 review',
  'ingredient': 'PRED',
  'reading': 'PRED',
  'source': 'Preiner M, et al. The future of origin of life research: bridging decades-old divisions. Life (Basel) '
            '10(3):20',
  'version': '2020-02-26; PMC7151616 (Europe PMC full-text XML)',
  'url': 'https://doi.org/10.3390/life10030020',
  'quote': ['even though classical approaches and theories—e.g., bottom-up and top-down, RNA world vs. '
            'metabolism-first—have been prevalent in origin of life research, they are ceasing to be mutually '
            'exclusive'],
  'raw_file': 'life/origin/preiner2020_review.txt',
  'note': "A comparative review; context for OL-1's expectation that CRR restates what the theories share.",
  'proposed': 'PRED'}]

DS4 = {'gen_fold': 40.0,
 'gen_basis': 'pedigree-based per-generation rates, 68 species (Bergeron et al. 2023, PMC9995274.1)',
 'year_fold': 120.0,
 'year_basis': 'mu_yearly_modelled from a joint parental-age model (Bergeron et al. 2023); the text does not state how '
               "many species the 120-fold covers ('55 species with modelled per-generation rates')",
 'same_footing': False,
 'matched_pair': 'Bergeron et al. 2023 Supplementary Table 9 (not downloaded; a test on it would be a prereg with a '
                 'later-day data step)',
 'claims': [{'tag': 'DS-4',
             'source': 'Bergeron et al. 2023, Evolution of the germline mutation rate across vertebrates, Nature '
                       '615:285 (PMC9995274.1)',
             'version': 'PMC9995274.1; epub 2023-03-01; doi 10.1038/s41586-023-05752-y; fetched 2026-09-26',
             'url': 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9995274/',
             'quote': ['Here we quantify germline mutation rates across vertebrates by sequencing and comparing the '
                       'high-coverage genomes of 151 parent–offspring trios from 68 species of mammals, fishes, birds '
                       'and reptiles. We show that the per-generation mutation rate varies among species by a factor '
                       'of 40',
                       'Overall, µgeneration varies by a factor of 40 across all species.',
                       'The average pedigree-based mutation rates per generation for each species, which are '
                       'represented by the squares, show 40-fold variation among species.',
                       'The estimated average µyearly_modelled varies more than 120-fold among species (Supplementary '
                       'Note 1 and Supplementary Table 9), with the highest µyearly_modelled estimated for the Texas '
                       'banded gecko at 1.96 × 10−8 mutations per site per year',
                       'whereas the lowest µyearly_modelled estimates were obtained for two bird species, the griffon '
                       'vulture and the snowy owl, both with less than 0.18 × 10−9 mutations per site per year',
                       'This large amount of interspecific variation is remarkable given that pedigree-based GMR '
                       'estimates of individual species assessed by previous separate studies only show an '
                       'approximately 16-fold variation in yearly GMRs34,51.',
                       'Within primates, we observed a twofold variation across species',
                       'When sample sizes are small, yearly rates are commonly inferred by dividing the per-generation '
                       'rate by the average age of the parents (or the generation time if parental age is '
                       'unknown)49–51.',
                       'Bearing this in mind, we decided to use µyearly_modelled for the current analysis as we '
                       'believe that this measure is more representative of the yearly rate at the generation time for '
                       'each species (estimated yearly rates are provided in Supplementary Table 9 for comparison).',
                       'Unfortunately, small per-species sample sizes in our dataset precluded modelling the effects '
                       'of parental age separately for each species. However, we observed very similar intercepts and '
                       'slopes across taxonomic groups, allowing us to fit a joint model for all species.',
                       'In total there are 55 species with modelled per-generation rates, including 32 mammalian and '
                       '15 avian species.',
                       'The generation time, age at maturity and species-level fecundity are the key life-history '
                       'traits affecting this variation among species.',
                       'The exceptionally high yearly mutation rates of domesticated animals, which have been '
                       'continually selected on fecundity traits including shorter generation times, further support '
                       'the importance of generation time in the evolution of mutation rates.',
                       'For the 105 trios for which parental age was known at reproduction, we found a significant '
                       'positive association between µgeneration and the average parental age at reproduction (linear '
                       'regression adjusted r2 = 0.14, P = 3.9 × 10−5; Fig. 1b).',
                       'Our results (Fig. 1b), as well as previous studies of mice, humans and cats20,34, imply that '
                       'parents always carry a minimum number of mutations in their gametes regardless of their age.',
                       'all three of these regressions have similar positive y-intercept values on the order of '
                       'approximately 0.59 × 10−8 mutations per site per generation.'],
             'raw_file': 'life/seq/bergeron2023.txt',
             'note': 'Per-generation spread: 40-fold (raw µgeneration, species means, 68 species). Per-year spread: '
                     '>120-fold (µyearly_modelled, a joint Poisson model of parental age; species count for the yearly '
                     'figure not stated in the text; modelled per-generation rates exist for 55 species). Not the same '
                     'statistic; the same-footing pair (µgeneration_modelled and µyearly_modelled for one species set) '
                     'is in Supplementary Table 9, not downloaded.'}]}
