"""Claims for Lossless_Pause/DECLARATION.md D1-D8, transcribed from docs/citations/lossless_pause_{training,serving,hardware}_2026-09-25.md
(fetched 2026-09-25 by research agents; raw texts in the session scratchpad pause_lit/<family>/). 'reading' is the investigator's
reading of each quote against its tagged prediction (states / opposite / bears), decided after reading the quotes; the agents'
own notes are in 'agent_note'. Verified verbatim by checks/verify_claims.py.
"""

CLAIMS = [{'id': 'training:0',
  'pred': 'D1',
  'reading': 'states',
  'source': 'PyTorch notes: Reproducibility',
  'version': "PyTorch 2.14 docs (page 'Last Updated On: May 14, 2026')",
  'url': 'https://docs.pytorch.org/docs/2.14/notes/randomness.html',
  'quote': ['Completely reproducible results are not guaranteed across PyTorch releases, individual commits, or '
            'different platforms.',
            'Furthermore, results may not be reproducible between CPU and GPU executions, even when using identical '
            'seeds.'],
  'raw_file': 'training/pytorch_randomness_notes.txt',
  'agent_note': 'States the platform/release dependence in D1; does not mention GPU count.'},
 {'id': 'training:1',
  'pred': 'D2',
  'reading': 'states',
  'source': 'PyTorch notes: Reproducibility',
  'version': 'PyTorch 2.14 docs',
  'url': 'https://docs.pytorch.org/docs/2.14/notes/randomness.html',
  'quote': ['Due to benchmarking noise and different hardware, the benchmark may select different algorithms on '
            'subsequent runs, even on the same machine.',
            'The backward pass uses non-deterministic atomic operations by default.'],
  'raw_file': 'training/pytorch_randomness_notes.txt',
  'agent_note': 'States two D2 sources: cuDNN algorithm selection (benchmark) and atomics (Flash SDPA backward).'},
 {'id': 'training:2',
  'pred': 'context',
  'reading': 'context',
  'source': 'PyTorch notes: Reproducibility',
  'version': 'PyTorch 2.14 docs',
  'url': 'https://docs.pytorch.org/docs/2.14/notes/randomness.html',
  'quote': ['Deterministic operations are often slower than nondeterministic operations, so single-run performance may '
            'decrease for your model.'],
  'raw_file': 'training/pytorch_randomness_notes.txt',
  'agent_note': "Cost of determinism, qualitative; bears on D1's 'needs deterministic algorithms'."},
 {'id': 'training:3',
  'pred': 'D1',
  'reading': 'states',
  'source': 'torch.use_deterministic_algorithms',
  'version': 'PyTorch 2.14 docs',
  'url': 'https://docs.pytorch.org/docs/2.14/generated/torch.use_deterministic_algorithms.html',
  'quote': ['algorithms which, given the same input, and when run on the same software and hardware, always produce '
            'the same output.',
            'This setting alone is not always enough to make an application reproducible.'],
  'raw_file': 'training/pytorch_use_deterministic_algorithms.txt',
  'agent_note': 'States the same-software-and-hardware scope of D1.'},
 {'id': 'training:4',
  'pred': 'D2',
  'reading': 'states',
  'source': 'torch.use_deterministic_algorithms',
  'version': 'PyTorch 2.14 docs',
  'url': 'https://docs.pytorch.org/docs/2.14/generated/torch.use_deterministic_algorithms.html',
  'quote': ['torch.Tensor.scatter_add_() when called on a CUDA tensor',
            'torch.index_add() when called on CUDA tensor',
            'The following normally-nondeterministic operations will throw a RuntimeError when mode=True:'],
  'raw_file': 'training/pytorch_use_deterministic_algorithms.txt',
  'agent_note': 'Lists scatter/index_add CUDA ops as normally nondeterministic (the atomics class of D2). The 2.14 '
                'page does not mention CUBLAS_WORKSPACE_CONFIG (checked: 0 matches).'},
 {'id': 'training:5',
  'pred': 'context',
  'reading': 'context',
  'source': 'PyTorch notes: CUDA semantics (cuBLAS workspaces)',
  'version': 'PyTorch 2.14 docs',
  'url': 'https://docs.pytorch.org/docs/2.14/notes/cuda.html',
  'quote': ['The workspace size per allocation can be specified via the environment variable CUBLAS_WORKSPACE_CONFIG '
            'with the format :[SIZE]:[COUNT].'],
  'raw_file': 'training/pytorch_cuda_semantics.txt',
  'agent_note': 'Where CUBLAS_WORKSPACE_CONFIG is documented in PyTorch 2.14; no determinism statement here.'},
 {'id': 'training:6',
  'pred': 'D1',
  'reading': 'states',
  'source': 'cuBLAS documentation, 2.1.4 Results Reproducibility',
  'version': 'cuBLAS 13.4 documentation',
  'url': 'https://docs.nvidia.com/cuda/cublas/index.html',
  'quote': ['By design, all cuBLAS API routines from a given toolkit version, generate the same bit-wise results at '
            'every run when executed on GPUs with the same architecture and the same number of SMs.',
            'However, bit-wise reproducibility is not guaranteed across toolkit versions because the implementation '
            'might differ due to some implementation changes.'],
  'raw_file': 'training/cublas_13.4.txt',
  'agent_note': "States D1's hardware/software scope (same architecture, same SM count, same toolkit)."},
 {'id': 'training:7',
  'pred': 'D2',
  'reading': 'states',
  'source': 'cuBLAS documentation, 2.1.4 Results Reproducibility',
  'version': 'cuBLAS 13.4 documentation',
  'url': 'https://docs.nvidia.com/cuda/cublas/index.html',
  'quote': ['This guarantee no longer holds when multiple CUDA streams are active or fixed-point emulation is used.',
            'In that case, the results are not guaranteed to be bit-wise reproducible because atomics are used for the '
            'computation.',
            'set a debug environment variable CUBLAS_WORKSPACE_CONFIG to :16:8 (may limit overall performance) or '
            ':4096:8 (will increase library footprint in GPU memory by approximately 24MiB).'],
  'raw_file': 'training/cublas_13.4.txt',
  'agent_note': 'States atomics as a source (D2) and names multi-stream workspace selection as a further source not '
                'listed in D2.'},
 {'id': 'training:8',
  'pred': 'D1',
  'reading': 'states',
  'source': 'cuDNN Backend developer guide: Reproducibility (Determinism)',
  'version': 'cuDNN v9.26.0 docs',
  'url': 'https://docs.nvidia.com/deeplearning/cudnn/backend/latest/developer/misc.html',
  'quote': ['By design, most of cuDNN’s routines from a given version generate the same bit-wise results across runs '
            'when executed on GPUs with the same architecture.',
            'Across different architectures, no cuDNN routines guarantee bitwise reproducibility.'],
  'raw_file': 'training/cudnn_misc.txt',
  'agent_note': "States D1's 'changing GPU type breaks it' for cuDNN."},
 {'id': 'training:9',
  'pred': 'D2',
  'reading': 'states',
  'source': 'cuDNN Backend developer guide: Reproducibility (Determinism)',
  'version': 'cuDNN v9.26.0 docs',
  'url': 'https://docs.nvidia.com/deeplearning/cudnn/backend/latest/developer/misc.html',
  'quote': ['because they use atomic operations in a way that introduces truly random floating point rounding errors'],
  'raw_file': 'training/cudnn_misc.txt',
  'agent_note': 'States atomics as a D2 source.'},
 {'id': 'training:10',
  'pred': 'D1',
  'reading': 'bears',
  'source': 'Megatron Core user guide: Deterministic Training',
  'version': "Megatron Core docs 'latest' (version_match 0.19.0)",
  'url': 'https://docs.nvidia.com/megatron-core/developer-guide/latest/user-guide/deterministic-training.html',
  'quote': ['Deterministic training guarantees that two runs with identical inputs produce identical outputs at every '
            'step.',
            'asserts that two runs of the same configuration produce bit-identical outputs and gradients'],
  'raw_file': 'training/megatron_core_deterministic_training.txt',
  'agent_note': 'Bears on D1: guarantee is stated for the same configuration; nothing on changing GPU count or type.'},
 {'id': 'training:11',
  'pred': 'D2',
  'reading': 'states',
  'source': 'Megatron Core user guide: Deterministic Training',
  'version': "Megatron Core docs 'latest' (version_match 0.19.0)",
  'url': 'https://docs.nvidia.com/megatron-core/developer-guide/latest/user-guide/deterministic-training.html',
  'quote': ['Conservative default — Ring’s reduction order is fixed by topology, so it is bit-exact across runs on '
            'every supported NCCL version',
            'Tree is intentionally excluded: its intra-node chain reduction order is not user-controllable, and the '
            'inter-node tree topology can vary across runs without a pinned topology file, so it cannot be vouched for '
            'as bit-exact across stacks.',
            'Must be off — asserted (fused CE is non-deterministic); drop the flag yourself'],
  'raw_file': 'training/megatron_core_deterministic_training.txt',
  'agent_note': "States NCCL reduction order as a D2 source; 'fixed by topology' also bears on D1 (order tied to the "
                'layout).'},
 {'id': 'training:12',
  'pred': 'D2',
  'reading': 'states',
  'source': 'Megatron Core user guide: Deterministic Training (nightly)',
  'version': "Megatron Core docs 'nightly' (fetched 2026-09-25)",
  'url': 'https://docs.nvidia.com/megatron-core/developer-guide/nightly/user-guide/deterministic-training.html',
  'quote': ['Determinism costs an independent output buffer: a reduction that would otherwise accumulate into shared '
            'memory with unordered atomics writes into its own buffer instead, fixing the summation order run to run.',
            'Triton picks a kernel config by timing its candidates, so the winner depends on the machine at that '
            'instant and ranks can disagree.'],
  'raw_file': 'training/megatron_core_deterministic_training_nightly.txt',
  'agent_note': "States atomics (D2) and autotuned kernel selection (analogue of D2's cuDNN algorithm selection)."},
 {'id': 'training:13',
  'pred': 'context',
  'reading': 'context',
  'source': 'Megatron Core user guide: Deterministic Training (nightly)',
  'version': "Megatron Core docs 'nightly'",
  'url': 'https://docs.nvidia.com/megatron-core/developer-guide/nightly/user-guide/deterministic-training.html',
  'quote': ['Clearing it is worth roughly 15% TFLOP/s on large configs, and more the more torch.empty calls a step '
            'makes.'],
  'raw_file': 'training/megatron_core_deterministic_training_nightly.txt',
  'agent_note': 'Cost of one determinism knob (uninitialized-memory fill); bears on the cost side of D1.'},
 {'id': 'training:14',
  'pred': 'D1',
  'reading': 'states',
  'source': 'Megatron-LM/Megatron-Core README, section Reproducibility (PyPI long description)',
  'version': 'megatron-core 0.12.1 (uploaded 2025-05-23); section absent from 0.19.2 PyPI description',
  'url': 'https://pypi.org/pypi/megatron-core/0.12.1/json',
  'quote': ['Megatron training can be bitwise reproducible; to enable this mode use',
            'This means that the same training config run twice in the same HW and SW environment should produce '
            'identical model checkpoints, losses and accuracy metric values (iteration time metrics may vary).',
            'In addition, determinisim has only been verified in NGC PyTorch containers up to and newer than 23.12.'],
  'raw_file': 'training/megatron_core_0.12.1_pypi_readme.txt',
  'agent_note': 'States D1: bitwise reproducibility with a deterministic mode, scoped to the same HW and SW '
                'environment.'},
 {'id': 'training:15',
  'pred': 'D2',
  'reading': 'states',
  'source': 'Megatron-LM/Megatron-Core README, section Reproducibility (PyPI long description)',
  'version': 'megatron-core 0.12.1',
  'url': 'https://pypi.org/pypi/megatron-core/0.12.1/json',
  'quote': ['The specific NCCL algorithm that is used during an all-reduce (as specified by the environment variable',
            'Flash attention is non-deterministic; do not use'],
  'raw_file': 'training/megatron_core_0.12.1_pypi_readme.txt',
  'agent_note': 'States NCCL algorithm choice as a reproducibility factor (D2).'},
 {'id': 'training:16',
  'pred': 'context',
  'reading': 'context',
  'source': 'Megatron Core API: core.tensor_parallel.random (CudaRNGStatesTracker)',
  'version': 'Megatron Core docs 0.19.0',
  'url': 'https://docs.nvidia.com/megatron-core/developer-guide/latest/apidocs/core/core.tensor_parallel.random.html',
  'quote': ['Using the add method, a cuda rng state is initialized based on the input seed and is assigned to name.',
            'tensor-model-parallel state: This state is different among a set of model parallel GPUs, but the same '
            'across data parallel groups.'],
  'raw_file': 'training/megatron_core_tp_random.txt',
  'agent_note': 'State inventory: RNG streams are per parallel group, so they are tied to the parallel layout (bears '
                'on D1).'},
 {'id': 'training:17',
  'pred': 'context',
  'reading': 'context',
  'source': 'Megatron Core API guide: dist_checkpointing',
  'version': 'Megatron Core docs 0.19.0',
  'url': 'https://docs.nvidia.com/megatron-core/developer-guide/latest/api-guide/core/dist_checkpointing.html',
  'quote': ['A key property of distributed checkpoints is that a checkpoint saved under one parallel configuration '
            '(tensor, pipeline, or data parallelism) can be loaded under a different parallel configuration.',
            'Not reshardable — not possible to change model parallelism when using this format.'],
  'raw_file': 'training/megatron_core_dist_checkpointing.txt',
  'agent_note': 'Checkpoint state can be moved across layouts (resharding); says nothing about bitwise identity after '
                'resharding.'},
 {'id': 'training:18',
  'pred': 'D2',
  'reading': 'bears',
  'source': 'NCCL User Guide: Environment Variables (NCCL_ALGO)',
  'version': 'NCCL 2.32.3 documentation',
  'url': 'https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html',
  'quote': ['The default is unset, which causes NCCL to automatically choose the available algorithms based on the '
            'node topology and architecture.'],
  'raw_file': 'training/nccl_env.txt',
  'agent_note': 'Bears on D2: algorithm (hence reduction order) chosen from topology/architecture. No explicit '
                'determinism or reproducibility statement found in the 2.32.3 env, collectives or troubleshooting '
                'pages.'},
 {'id': 'training:19',
  'pred': 'context',
  'reading': 'context',
  'source': 'torch.distributed.checkpoint (DCP)',
  'version': "PyTorch 2.14 docs (page 'Last Updated On: Jul 08, 2026')",
  'url': 'https://docs.pytorch.org/docs/2.14/distributed.checkpoint.html',
  'quote': ['It handles load-time resharding which enables saving in one cluster topology and loading into another.',
            'returning a model and optimizer state_dict that can be resharded with a different number of trainers '
            'and/or different parallelisms.'],
  'raw_file': 'training/pytorch_dcp.txt',
  'agent_note': 'State portability across topologies; no bitwise claim.'},
 {'id': 'training:20',
  'pred': 'D8',
  'reading': 'states',
  'source': 'torch.distributed.checkpoint (DCP)',
  'version': 'PyTorch 2.14 docs',
  'url': 'https://docs.pytorch.org/docs/2.14/distributed.checkpoint.html',
  'quote': ['Asynchronous version of save. This code first de-stages the state_dict on to the staging storage '
            '(defaults to CPU memory), and then calls the save in a separate thread.'],
  'raw_file': 'training/pytorch_dcp.txt',
  'agent_note': 'Describes the asynchronous, CPU-staged save of D8.'},
 {'id': 'training:21',
  'pred': 'D8',
  'reading': 'states',
  'source': 'PyTorch recipe: Asynchronous Saving with Distributed Checkpoint (DCP)',
  'version': 'Last Updated: Feb 03, 2026',
  'url': 'https://docs.pytorch.org/tutorials/recipes/distributed_async_checkpoint_recipe.html',
  'quote': ['Checkpointing is often a bottleneck in the critical path for distributed training workloads, incurring '
            'larger and larger costs as both model and world sizes grow.',
            'this optimization attacks the main overhead of asynchronous checkpointing, which is the in-memory copying '
            'to checkpointing buffers.'],
  'raw_file': 'training/pytorch_dcp_async_recipe.txt',
  'agent_note': 'States D8 (checkpoint cost; asynchronous saving as the remedy).'},
 {'id': 'training:22',
  'pred': 'context',
  'reading': 'context',
  'source': 'PyTorch recipe: Getting Started with Distributed Checkpoint (DCP)',
  'version': 'Last Updated: Jul 10, 2025',
  'url': 'https://docs.pytorch.org/tutorials/recipes/distributed_checkpoint_recipe.html',
  'quote': ['You can load in the same world size or different world size.'],
  'raw_file': 'training/pytorch_dcp_recipe.txt',
  'agent_note': 'State portability across world size.'},
 {'id': 'training:23',
  'pred': 'context',
  'reading': 'context',
  'source': 'Zhuang, Zhang, Song, Hooker: Randomness in Neural Network Training: Characterizing the Impact of Tooling',
  'version': 'arXiv 2106.11872v1 (22 Jun 2021)',
  'url': 'https://arxiv.org/abs/2106.11872',
  'quote': ['with overhead up to 746%, 241%, and 196% on a spectrum of widely used GPU accelerator architectures, '
            'relative to non-deterministic training.',
            'GPUs with older Pascal architecture (P100) evidence higher overhead than GPUs with later Volta (V100) and '
            'Turing (T4) architecture.'],
  'raw_file': 'training/zhuang2021_randomness.txt',
  'agent_note': 'Measured cost of deterministic GPU training; bears on D1 (deterministic algorithms are the price).'},
 {'id': 'training:24',
  'pred': 'D2',
  'reading': 'states',
  'source': 'Zhuang et al. 2021',
  'version': 'arXiv 2106.11872v1',
  'url': 'https://arxiv.org/abs/2106.11872',
  'quote': ['Some convolution algorithm implementation in cuDNN are designed to trade determinism for execution speed.',
            'This is because the difference in input data order will result in different ﬂoat-point accumulation order '
            'in gradients accumulation stage thus introducing latent implementation noise.'],
  'raw_file': 'training/zhuang2021_randomness.txt',
  'agent_note': 'Bears on D2: cuDNN algorithms and accumulation order as sources.'},
 {'id': 'training:25',
  'pred': 'D1',
  'reading': 'states',
  'source': 'Donaghy et al. (Gensyn): OPEN-1B: A Fully Auditable Training Run',
  'version': 'arXiv 2609.17380v1 (15 Sep 2026)',
  'url': 'https://arxiv.org/abs/2609.17380',
  'quote': ['Determinism means a computation returns the same result every time it runs on the same machine with the '
            'same environment.',
            'Determinism does not imply reproducibility. A training run can be perfectly repeatable on its own GPU '
            'while disagreeing with an identical run on a processor or a different GPU model. A framework’s '
            'deterministic mode addresses only the first case.',
            'Changing the number of data parallel workers results in different batch orderings.'],
  'raw_file': 'training/open1b_2026.txt',
  'agent_note': 'States D1 for standard deterministic modes (same machine; different GPU model or worker count breaks '
                'it).'},
 {'id': 'training:26',
  'pred': 'D1',
  'reading': 'opposite',
  'source': 'OPEN-1B',
  'version': 'arXiv 2609.17380v1',
  'url': 'https://arxiv.org/abs/2609.17380',
  'quote': ['this makes the entire training run bit-exact under replay, independent of device count and topology, '
            'enabling third-party audit of any training segment.',
            'In the case of a hardware failure or resource re-allocation, the run can be re-sharded onto a different '
            'number of devices without perturbing the training data sequence.',
            'We trade off compute performance for reproducibility.'],
  'raw_file': 'training/open1b_2026.txt',
  'agent_note': "States the opposite of D1's 'changing GPU count or type breaks it' for a run built on custom "
                'reproducible kernels (RepOps), a topology-invariant data stream and a deterministic all-reduce, at a '
                'stated performance cost (MFU about 5%, same section). It qualifies D1 rather than contradicting it '
                'for standard stacks.'},
 {'id': 'training:27',
  'pred': 'D2',
  'reading': 'states',
  'source': 'OPEN-1B',
  'version': 'arXiv 2609.17380v1',
  'url': 'https://arxiv.org/abs/2609.17380',
  'quote': ['By imposing a definite order on the sources of training nondeterminism, GPU kernel reductions, data batch '
            'ordering across a data-parallel cluster, and inter/intra-node collective communication'],
  'raw_file': 'training/open1b_2026.txt',
  'agent_note': 'Names kernel reductions and collective communication as sources (D2); adds data batch ordering.'},
 {'id': 'training:28',
  'pred': 'D1',
  'reading': 'states',
  'source': 'Arun et al.: Verde: Verification via Refereed Delegation for Machine Learning Programs (RepOps)',
  'version': 'arXiv 2502.19405v1 (26 Feb 2025)',
  'url': 'https://arxiv.org/abs/2502.19405',
  'quote': ['Given the same parallelized program, owing to differences in architecture, distinct hardware '
            'implementations may (and often do) execute a + b + c in different orders, ending up with different '
            'results.',
            'RepOps currently ensures reproducibility between setups when programs are run on a single GPU in each '
            'setup.',
            'incur around 60% overhead RepOps on an A100 GPU'],
  'raw_file': 'training/verde_repops.txt',
  'agent_note': 'States the hardware-type half of D1 for ordinary kernels; cross-hardware BR achieved with custom '
                'kernels on a single GPU, at a cost.'},
 {'id': 'training:29',
  'pred': 'D1',
  'reading': 'bears',
  'source': 'Lian et al.: Universal Checkpointing (DeepSpeed UCP)',
  'version': 'arXiv 2406.18820v3 (4 Jul 2025)',
  'url': 'https://arxiv.org/abs/2406.18820',
  'quote': ['distributed checkpoints are tightly coupled to specific model parallelism and hardware configurations',
            'the training can be seamlessly resumed using different Target parallelism strategies, while achieving '
            'consistent convergence if the training were to continue with the Source strategy.',
            'Most importantly, the resumed training curves match the curves from the Source at iterations 101–200.'],
  'raw_file': 'training/ucp_deepspeed.txt',
  'agent_note': 'Bears on D1: resuming under changed parallelism is evaluated by matching loss curves, not by bitwise '
                'identity; no bitwise claim made.'},
 {'id': 'training:30',
  'pred': 'context',
  'reading': 'context',
  'source': 'Wan et al.: ByteCheckpoint: A Unified Checkpointing System for Large Foundation Model Development',
  'version': "arXiv 2407.20143v4 (2 Apr 2025); NSDI'25",
  'url': 'https://arxiv.org/abs/2407.20143',
  'quote': ['CPU states include dataloader module, Random Number Generator (RNG) state, global training step number, '
            'and learning-rate scheduler, all stored in CPU memory.',
            'the token buffers should be copied to the destination workers for bitwise-correct resuming.'],
  'raw_file': 'training/bytecheckpoint.txt',
  'agent_note': 'State inventory for a lossless resume (GPU params/optimizer + CPU dataloader/RNG/step/LR schedule).'},
 {'id': 'training:31',
  'pred': 'D8',
  'reading': 'states',
  'source': 'ByteCheckpoint',
  'version': 'arXiv 2407.20143v4',
  'url': 'https://arxiv.org/abs/2407.20143',
  'quote': ['ByteCheckpoint significantly reduces runtime checkpoint stalls, achieving an average reduction of 54.20×.',
            'This improvement reduces the average checkpoint stall time from minutes or seconds to sub-second '
            'durations, outperforming both DCP and MCP.'],
  'raw_file': 'training/bytecheckpoint.txt',
  'agent_note': "States D8 (stall measured; reduced by the system's asynchronous pipeline)."},
 {'id': 'training:32',
  'pred': 'D8',
  'reading': 'states',
  'source': 'Jiang et al.: MegaScale: Scaling Large Language Model Training to More Than 10,000 GPUs',
  'version': 'arXiv 2402.15627v1 (23 Feb 2024)',
  'url': 'https://arxiv.org/abs/2402.15627',
  'quote': ['In the first stage, each GPU worker writes its on-chip states to the host memory, and then continues the '
            'training process.',
            'this process can be reduced to several seconds thanks to the high PCIe bandwidth, thereby minimally '
            'interrupting the ongoing training process.',
            'the system can catch up to the training progress prior to the crash within 15 minutes from the latest '
            'checkpoints, maintaining over 90% effective training time rate'],
  'raw_file': 'training/megascale.txt',
  'agent_note': 'States D8 (two-stage host-memory then asynchronous persist).'},
 {'id': 'training:33',
  'pred': 'D8',
  'reading': 'bears',
  'source': 'Llama Team, AI @ Meta: The Llama 3 Herd of Models, §3.3.4',
  'version': 'arXiv 2407.21783v3 (23 Nov 2024)',
  'url': 'https://arxiv.org/abs/2407.21783',
  'quote': ['We aim to minimize GPU pause time during checkpointing and increase checkpoint frequency to reduce the '
            'amount of lost work after a recovery.',
            'To increase the effective training time, we reduced job startup and checkpointing time'],
  'raw_file': 'training/llama3.txt',
  'agent_note': 'Bears on D8 (checkpoint pause is a cost being minimised); no number for the overhead itself.'},
 {'id': 'training:34',
  'pred': 'context',
  'reading': 'context',
  'source': 'Llama 3, §3.3.4',
  'version': 'arXiv 2407.21783v3',
  'url': 'https://arxiv.org/abs/2407.21783',
  'quote': ['the synchronous nature of training makes it less fault-tolerant—a single GPU failure may require a '
            'restart of the entire job.',
            'During a 54-day snapshot period of pre-training, we experienced a total of 466 job interruptions.',
            'Checkpointing saves each GPU’s model state, ranging from 1 MB to 4 GB per GPU, for recovery and '
            'debugging.'],
  'raw_file': 'training/llama3.txt',
  'agent_note': 'Frequency of stop/resume events in frontier training.'},
 {'id': 'training:35',
  'pred': 'D7',
  'reading': 'bears',
  'source': 'Llama 3, §3.3.4',
  'version': 'arXiv 2407.21783v3',
  'url': 'https://arxiv.org/abs/2407.21783',
  'quote': ['tens of thousands of GPUs may increase or decrease power consumption at the same time, for example, due '
            'to all GPUs waiting for checkpointing or collective communications to finish'],
  'raw_file': 'training/llama3.txt',
  'agent_note': 'Bears on D7: waiting GPUs draw measurably less than working ones at data-centre scale; gives no '
                'fraction.'},
 {'id': 'training:36',
  'pred': 'D8',
  'reading': 'states',
  'source': 'Kokolis, Kuchnik et al.: Revisiting Reliability in Large-Scale Machine Learning Research Clusters',
  'version': 'arXiv 2410.21680v2 (6 Feb 2025); HPCA 2025',
  'url': 'https://arxiv.org/abs/2410.21680',
  'quote': ['3) Checkpoint overhead: The time checkpointing adds to job runtime.',
            'checkpoint write overhead needs to be under a minute O(10s), achievable with asynchronous checkpoint '
            'writing strategies',
            'To reach ETTR of 0.9 for the largest feasible training runs on RSC-1 (∼12,000 GPUs, taking two thirds of '
            'RSC-1), checkpoint write time overhead needs to be on the order of ∼10 seconds or failure rate needs to '
            'dramatically improve from 6.50 to ∼1.'],
  'raw_file': 'training/kokolis2025.txt',
  'agent_note': "States D8 (modelled, not measured per job: 'we currently lack a reliable way for tracking either at "
                "scale')."},
 {'id': 'training:37',
  'pred': 'D8',
  'reading': 'states',
  'source': 'Mohan, Phanishayee, Chidambaram: CheckFreq: Frequent, Fine-Grained DNN Checkpointing',
  'version': 'FAST 2021 proceedings PDF',
  'url': 'https://www.usenix.org/system/files/fast21-mohan.pdf',
  'quote': ['CheckFreq can reduce the recovery time from hours to seconds while bounding the runtime overhead within '
            '3.5%.',
            'checkpointing requires the training to brieﬂy pause to capture the model weights accurately.'],
  'raw_file': 'training/checkfreq_fast21.txt',
  'agent_note': 'States D8 (checkpoint stall; pipelined snapshot/persist reduces it).'},
 {'id': 'training:38',
  'pred': 'context',
  'reading': 'context',
  'source': 'CheckFreq',
  'version': 'FAST 2021',
  'url': 'https://www.usenix.org/system/files/fast21-mohan.pdf',
  'quote': ['When the job is interrupted, these iterators can either miss out, or repeat data items in an epoch, '
            'resulting in loss in model accuracy when resuming at iteration granularity.',
            'resulting in upto the 13% drop in accuracy for popular models ResNet18 (Fig 6).'],
  'raw_file': 'training/checkfreq_fast21.txt',
  'agent_note': 'State inventory: data-iterator state must be saved for a faithful resume.'},
 {'id': 'training:39',
  'pred': 'D8',
  'reading': 'states',
  'source': 'Wang et al.: Gemini: Fast Failure Recovery in Distributed Training with In-Memory Checkpoints',
  'version': 'SOSP 2023 (author copy; ACM DL PDF returned 403)',
  'url': 'https://www.cs.rice.edu/~eugeneng/papers/SOSP23.pdf',
  'quote': ['Existing solutions have significant failure recovery costs due to the severe restriction imposed by the '
            'bandwidth of remote storage in which they store checkpoints.',
            'Moreover, it achieves optimal checkpoint frequency, i.e., every iteration, and incurs no overhead on '
            'training throughput for large model training.'],
  'raw_file': 'training/gemini_sosp23.txt',
  'agent_note': 'States D8 (in-memory checkpoints remove throughput overhead).'},
 {'id': 'training:40',
  'pred': 'D8',
  'reading': 'states',
  'source': 'Maurya, Rafique, Cappello, Nicolae: DataStates-LLM: Scalable Checkpointing for Transformer Models Using '
            'Composable State Providers',
  'version': 'arXiv 2601.16956v1 (23 Jan 2026)',
  'url': 'https://arxiv.org/abs/2601.16956',
  'quote': ['This results in significant runtime overheads due to blocking device-to-host transfers, data-oblivious '
            'serialization, and storage I/O contention.',
            'higher checkpointing throughput and reduces end-to-end training time by up to 2.2×compared to '
            'state-of-the-art solutions'],
  'raw_file': 'training/datastates_llm_2026.txt',
  'agent_note': 'States D8.'},
 {'id': 'training:41',
  'pred': 'D8',
  'reading': 'states',
  'source': 'Xie, Chen, Zheng, Yang, Zhang: PHOENIX: Resilient LLM Training with Hot-Swapping via Zero-Overhead '
            'Checkpoint',
  'version': 'arXiv 2607.01646v2 (6 Jul 2026)',
  'url': 'https://arxiv.org/abs/2607.01646',
  'quote': ['Existing fault-tolerance mechanisms either impose non-trivial overhead during failure-free execution or '
            'suffer from prolonged recovery latency',
            'PHOENIX efficiently overlaps the in-memory checkpointing with computation, thus introducing zero overhead '
            'during error-free execution.'],
  'raw_file': 'training/phoenix_2026.txt',
  'agent_note': 'States D8.'},
 {'id': 'training:42',
  'pred': 'D8',
  'reading': 'states',
  'source': 'Han et al.: TierCheck: Tiered Checkpointing for Fault Tolerance in Large Language Model Training',
  'version': 'arXiv 2605.17821v1 (18 May 2026)',
  'url': 'https://arxiv.org/abs/2605.17821',
  'quote': ['Existing checkpointing systems rely on monolithic, single-tier storage backend, forcing a trade-off '
            'between state-saving overhead and recovery speed.',
            'reduces end-to-end checkpointing time to under 10 s'],
  'raw_file': 'training/tiercheck_2026.txt',
  'agent_note': 'States D8.'},
 {'id': 'training:43',
  'pred': 'context',
  'reading': 'context',
  'source': 'Athlur et al.: Varuna: Scalable, Low-cost Training of Massive Deep Learning Models',
  'version': 'arXiv 2111.04007v2 (15 Nov 2021); EuroSys 2022',
  'url': 'https://arxiv.org/abs/2111.04007',
  'quote': ['employing dynamic, semantics-preserving reconfiguration of the training job.',
            'require users to provide different sets of hyper-parameters and mini-batch sizes for a varying number of '
            'resources.'],
  'raw_file': 'training/varuna.txt',
  'agent_note': 'Preemption handling preserves sync-SGD semantics and batch size; no claim that resumed training is '
                'bitwise identical (bears on D1).'},
 {'id': 'training:44',
  'pred': 'context',
  'reading': 'context',
  'source': 'Thorpe et al.: Bamboo: Making Preemptible Instances Resilient for Affordable Training of Large DNNs',
  'version': 'arXiv 2204.12013v1 (26 Apr 2022); NSDI 2023',
  'url': 'https://arxiv.org/abs/2204.12013',
  'quote': ['we built Bamboo atop synchronous microbatching where model state is always consistent.',
            'elastic batching because dropping samples is equivalent to changing the effective batch size at a '
            'training iteration'],
  'raw_file': 'training/bamboo.txt',
  'agent_note': 'Preserves consistent model state via redundant computation; alternatives (sample dropping) change the '
                'trajectory. No bitwise claim.'},
 {'id': 'training:45',
  'pred': 'context',
  'reading': 'context',
  'source': 'Jang et al.: Oobleck: Resilient Distributed Training of Large Models Using Pipeline Templates',
  'version': 'arXiv 2309.08125v2 (7 Nov 2023); SOSP 2023',
  'url': 'https://arxiv.org/abs/2309.08125',
  'quote': ['Each pipeline may have more batches to compute, but the global batch size remains constant.',
            'Oobleck does not change the global batch size arbitrarily in such cases.'],
  'raw_file': 'training/oobleck.txt',
  'agent_note': 'Preserves global batch size across reconfiguration; no bitwise claim.'},
 {'id': 'training:46',
  'pred': 'context',
  'reading': 'context',
  'source': 'Groeneveld et al.: OLMo: Accelerating the Science of Language Models',
  'version': 'arXiv 2402.00838v4 (7 Jun 2024)',
  'url': 'https://arxiv.org/abs/2402.00838',
  'quote': ['The training instances are shuffled in the exact same way for each training run. The data order and exact '
            'composition of each training batch can be reconstructed from the artifacts we release.'],
  'raw_file': 'training/olmo1.txt',
  'agent_note': 'Data-order state is reproducible; no bitwise claim about weights across restarts.'},
 {'id': 'training:47',
  'pred': 'context',
  'reading': 'context',
  'source': 'OLMo Team: 2 OLMo 2 Furious',
  'version': 'arXiv 2501.00656v3 (8 Oct 2025)',
  'url': 'https://arxiv.org/abs/2501.00656',
  'quote': ['Containers further capture software dependencies and the runtime details of workloads. This helps run '
            'repeatable experiments, and makes it possible to replay old results even months after they happened.',
            'an improper ordering of the compute nodes in the NCCL library'],
  'raw_file': 'training/olmo2.txt',
  'agent_note': 'Environment pinning for repeatability; no bitwise claim across restarts or GPU counts.'},
 {'id': 'serving:0',
  'pred': 'D3',
  'reading': 'states',
  'source': "He, H. and Thinking Machines Lab, 'Defeating Nondeterminism in LLM Inference', Thinking Machines Lab: "
            'Connectionism (blog)',
  'version': 'Sep 10, 2025 (doi 10.64434/tml.20250910)',
  'url': 'https://thinkingmachines.ai/blog/defeating-nondeterminism-in-llm-inference/',
  'quote': ['the primary reason nearly all LLM inference endpoints are nondeterministic is that the load (and thus '
            'batch-size) nondeterministically varies!',
            'our forward pass lacks “batch invariance”, causing our request’s output to depend on the batch size of '
            'our forward pass.'],
  'raw_file': 'serving/tml_blog.txt',
  'agent_note': "States the prediction's first half: batch composition/size, not atomics, as the primary source."},
 {'id': 'serving:1',
  'pred': 'D3',
  'reading': 'states',
  'source': "He, H. and Thinking Machines Lab, 'Defeating Nondeterminism in LLM Inference', Thinking Machines Lab: "
            'Connectionism (blog)',
  'version': 'Sep 10, 2025 (doi 10.64434/tml.20250910)',
  'url': 'https://thinkingmachines.ai/blog/defeating-nondeterminism-in-llm-inference/',
  'quote': ['concurrency (and atomic adds) end up being completely uninvolved in LLM inference nondeterminism!',
            'the forward pass in an LLM is in fact “run-to-run deterministic.”'],
  'raw_file': 'serving/tml_blog.txt',
  'agent_note': "States the 'not only atomics' part (in stronger form: atomics uninvolved in the forward pass)."},
 {'id': 'serving:2',
  'pred': 'D3',
  'reading': 'states',
  'source': "He, H. and Thinking Machines Lab, 'Defeating Nondeterminism in LLM Inference', Thinking Machines Lab: "
            'Connectionism (blog)',
  'version': 'Sep 10, 2025 (doi 10.64434/tml.20250910)',
  'url': 'https://thinkingmachines.ai/blog/defeating-nondeterminism-in-llm-inference/',
  'quote': ['Surprisingly, we generate 80 unique completions, with the most common of these occuring 78 times.',
            'when we enable our batch-invariant kernels, all of our 1000 completions are identical.'],
  'raw_file': 'serving/tml_blog.txt',
  'agent_note': 'States that batch-invariant kernels remove the run-to-run differences (Qwen3-235B, 1000 completions, '
                'temperature 0).'},
 {'id': 'serving:3',
  'pred': 'D3',
  'reading': 'states',
  'source': "He, H. and Thinking Machines Lab, 'Defeating Nondeterminism in LLM Inference', Thinking Machines Lab: "
            'Connectionism (blog)',
  'version': 'Sep 10, 2025 (doi 10.64434/tml.20250910)',
  'url': 'https://thinkingmachines.ai/blog/defeating-nondeterminism-in-llm-inference/',
  'quote': ['We will set up an API server with one GPU running Qwen-3-8B, and request 1000 sequences with an output '
            'length of between 90 and 110.',
            'Unoptimized Deterministic vLLM\n55',
            'Much of the slowdown comes from the fact that the FlexAttention integration in vLLM has not been heavily '
            'optimized yet.'],
  'raw_file': 'serving/tml_blog.txt',
  'agent_note': 'States the cost: table reads vLLM default 26 s, unoptimized deterministic 55 s, + improved attention '
                'kernel 42 s.'},
 {'id': 'serving:4',
  'pred': 'D3',
  'reading': 'states',
  'source': "He, H. and Thinking Machines Lab, 'Defeating Nondeterminism in LLM Inference', Thinking Machines Lab: "
            'Connectionism (blog)',
  'version': 'Sep 10, 2025 (doi 10.64434/tml.20250910)',
  'url': 'https://thinkingmachines.ai/blog/defeating-nondeterminism-in-llm-inference/',
  'quote': ['Despite obtaining batch invariance, we only lose about 20% performance compared to cuBLAS.'],
  'raw_file': 'serving/tml_blog.txt',
  'agent_note': 'States a kernel-level cost (batch-invariant Triton matmul vs cuBLAS).'},
 {'id': 'serving:5',
  'pred': 'D1',
  'reading': 'bears',
  'source': "He, H. and Thinking Machines Lab, 'Defeating Nondeterminism in LLM Inference', Thinking Machines Lab: "
            'Connectionism (blog)',
  'version': 'Sep 10, 2025 (doi 10.64434/tml.20250910)',
  'url': 'https://thinkingmachines.ai/blog/defeating-nondeterminism-in-llm-inference/',
  'quote': ['It is not “hardware/software version invariant” — your GPU/PyTorch version may return a different value, '
            'but it should deterministically return the same value.'],
  'raw_file': 'serving/tml_blog.txt',
  'agent_note': 'Bears on D1 (inference analogue): run-to-run determinism does not extend across hardware/software '
                'versions.'},
 {'id': 'serving:6',
  'pred': 'D4',
  'reading': 'bears',
  'source': "He, H. and Thinking Machines Lab, 'Defeating Nondeterminism in LLM Inference', Thinking Machines Lab: "
            'Connectionism (blog)',
  'version': 'Sep 10, 2025 (doi 10.64434/tml.20250910)',
  'url': 'https://thinkingmachines.ai/blog/defeating-nondeterminism-in-llm-inference/',
  'quote': ['it’s necessary that the reduction order for a given token does not depend on how many other tokens from '
            'its sequence are being simultaneously processed.',
            'the reduction order must be identical regardless of whether 0 tokens are in the KV cache (prefill) or 999 '
            'tokens are in the KV cache (decoding).'],
  'raw_file': 'serving/tml_blog.txt',
  'agent_note': 'Bears on whether recompute (prefill of the full sequence) reproduces decode-time numerics: only with '
                'batch-invariant attention.'},
 {'id': 'serving:7',
  'pred': 'D3',
  'reading': 'bears',
  'source': "Yuan, Li, Ding, Xie, Li, Zhao, Wan, Shi, Hu, Liu, 'Understanding and Mitigating Numerical Sources of "
            "Nondeterminism in LLM Inference' (v1 title: 'Give Me FP32 or Give Me Death? Challenges and Solutions for "
            "Reproducible Reasoning'), arXiv 2506.09501",
  'version': 'v2, 24 Oct 2025',
  'url': 'https://arxiv.org/abs/2506.09501',
  'quote': ['changing system configuration, such as evaluation batch size, GPU count, and GPU version, can introduce '
            'significant differences in the generated responses.',
            'can exhibit up to9% variation in accuracy and 9,000 tokens difference in response length due to '
            'differences in GPU count, type, and evaluation batch size.'],
  'raw_file': 'serving/yuan2025_nondeterminism.txt',
  'agent_note': 'Bears on D3: batch size named as one source among GPU count and GPU type (not singled out as main).'},
 {'id': 'serving:8',
  'pred': 'D1',
  'reading': 'bears',
  'source': "Yuan, Li, Ding, Xie, Li, Zhao, Wan, Shi, Hu, Liu, 'Understanding and Mitigating Numerical Sources of "
            "Nondeterminism in LLM Inference' (v1 title: 'Give Me FP32 or Give Me Death? Challenges and Solutions for "
            "Reproducible Reasoning'), arXiv 2506.09501",
  'version': 'v2, 24 Oct 2025',
  'url': 'https://arxiv.org/abs/2506.09501',
  'quote': ['the technique is currently limited to handling variations related only to the batch dimension, making it '
            'robust to continuous batching and other batch-size–related changes, but not to other forms of '
            'nondeterminism like changing the TP sizes or GPU types.'],
  'raw_file': 'serving/yuan2025_nondeterminism.txt',
  'agent_note': 'States for inference what D1 states for training: batch invariance does not survive a change of TP '
                'size or GPU type.'},
 {'id': 'serving:9',
  'pred': 'D3',
  'reading': 'bears',
  'source': "Yuan, Li, Ding, Xie, Li, Zhao, Wan, Shi, Hu, Liu, 'Understanding and Mitigating Numerical Sources of "
            "Nondeterminism in LLM Inference' (v1 title: 'Give Me FP32 or Give Me Death? Challenges and Solutions for "
            "Reproducible Reasoning'), arXiv 2506.09501",
  'version': 'v2, 24 Oct 2025',
  'url': 'https://arxiv.org/abs/2506.09501',
  'quote': ['(1) continuous batching[ 36], which dynamically modifies the set of requests within a batch;(2) different '
            'operator implementations, such as Split-K versus Non-Split-K MatMul [23]',
            '(4) collective operations in parallel settings, such as AllReduce; and(5) parallelization strategies, '
            'such as tensor parallelism (TP)'],
  'raw_file': 'serving/yuan2025_nondeterminism.txt',
  'agent_note': 'Lists sources of reordering; bears on D3 (batching first among several) and D2 (collectives).'},
 {'id': 'serving:10',
  'pred': 'D3',
  'reading': 'bears',
  'source': "Yuan, Li, Ding, Xie, Li, Zhao, Wan, Shi, Hu, Liu, 'Understanding and Mitigating Numerical Sources of "
            "Nondeterminism in LLM Inference' (v1 title: 'Give Me FP32 or Give Me Death? Challenges and Solutions for "
            "Reproducible Reasoning'), arXiv 2506.09501",
  'version': 'v2, 24 Oct 2025',
  'url': 'https://arxiv.org/abs/2506.09501',
  'quote': ['LayerCast produces consistent outputs across different batch sizes and GPU configurations, with '
            'divergence rates below 3.4%.',
            'LayerCast offers substantial benefits over full FP32: memory usage is reduced by 34%'],
  'raw_file': 'serving/yuan2025_nondeterminism.txt',
  'agent_note': 'Bears on D3: an alternative remedy (FP32 compute) that reduces but does not remove divergence; cost '
                'stated against full FP32.'},
 {'id': 'serving:11',
  'pred': 'D3',
  'reading': 'states',
  'source': "vLLM documentation, 'Batch Invariance' (latest developer preview docs)",
  'version': 'page dated September 23, 2026; fetched 2026-09-25',
  'url': 'https://docs.vllm.ai/en/latest/features/batch_invariance.html',
  'quote': ['Batch invariance ensures that the output of a model is deterministic and independent of the batch size or '
            'the order of requests in a batch.',
            'Enabling batch invariance may impact performance compared to the default non-deterministic mode. This '
            'trade-off is intentional to guarantee reproducibility.'],
  'raw_file': 'serving/vllm_bi.txt',
  'agent_note': 'States the remedy and that it has a cost (not quantified here).'},
 {'id': 'serving:12',
  'pred': 'D3',
  'reading': 'bears',
  'source': "vLLM documentation, 'Batch Invariance' (latest developer preview docs)",
  'version': 'page dated September 23, 2026; fetched 2026-09-25',
  'url': 'https://docs.vllm.ai/en/latest/features/batch_invariance.html',
  'quote': ['Batch invariance is currently in beta.',
            'Disables certain optimizations that may introduce non-determinism (such as custom all-reduce operations '
            'in tensor parallel mode)'],
  'raw_file': 'serving/vllm_bi.txt',
  'agent_note': 'Bears on D3/D2: the feature is beta; also removes custom all-reduce under TP.'},
 {'id': 'serving:13',
  'pred': 'D1',
  'reading': 'bears',
  'source': "vLLM documentation, 'Reproducibility' (latest developer preview docs)",
  'version': 'page dated April 28, 2026; fetched 2026-09-25',
  'url': 'https://docs.vllm.ai/en/latest/usage/reproducibility.html',
  'quote': ['Even with the above settings, vLLM only provides reproducibility when it runs on the same hardware and '
            'the same vLLM version.',
            'vLLM does not guarantee the reproducibility of the results by default, for the sake of performance.'],
  'raw_file': 'serving/vllm_repro.txt',
  'agent_note': 'States the inference analogue of D1 (same hardware and same software version).'},
 {'id': 'serving:14',
  'pred': 'D3',
  'reading': 'bears',
  'source': "vLLM documentation, 'Reproducibility' (latest developer preview docs)",
  'version': 'page dated April 28, 2026; fetched 2026-09-25',
  'url': 'https://docs.vllm.ai/en/latest/usage/reproducibility.html',
  'quote': ['In offline mode, you can either set VLLM_ENABLE_V1_MULTIPROCESSING=0 which makes scheduling '
            'deterministic, or enable batch invariance to make the outputs insensitive to scheduling.'],
  'raw_file': 'serving/vllm_repro.txt',
  'agent_note': 'Bears on D3: scheduling (hence batch composition) is the variable either fixed or made irrelevant.'},
 {'id': 'serving:15',
  'pred': 'D4',
  'reading': 'states',
  'source': "vLLM documentation, 'Optimization and Tuning' (stable docs; page references vLLM v0.23.0)",
  'version': 'page dated August 20, 2026; fetched 2026-09-25',
  'url': 'https://docs.vllm.ai/en/stable/configuration/optimization/',
  'quote': ['In such cases, vLLM can preempt requests to free up KV cache space for other requests. Preempted requests '
            'are recomputed when sufficient KV cache space becomes available again.',
            'In vLLM V1, the default preemption mode is RECOMPUTE rather than SWAP, as recomputation has lower '
            'overhead in the V1 architecture.'],
  'raw_file': 'serving/vllm_opt_stable.txt',
  'agent_note': 'States D4 (drop-and-recompute as the current default; swap as the alternative).'},
 {'id': 'serving:16',
  'pred': 'D4',
  'reading': 'states',
  'source': "vLLM documentation, 'Optimization and Tuning' (stable docs; page references vLLM v0.23.0)",
  'version': 'page dated August 20, 2026; fetched 2026-09-25',
  'url': 'https://docs.vllm.ai/en/stable/configuration/optimization/',
  'quote': ['While this mechanism ensures system robustness, preemption and recomputation can adversely affect '
            'end-to-end latency.'],
  'raw_file': 'serving/vllm_opt_stable.txt',
  'agent_note': 'States the recompute cost (latency).'},
 {'id': 'serving:17',
  'pred': 'D3',
  'reading': 'states',
  'source': "SGLang documentation, 'Deterministic Inference'",
  'version': 'undated page; fetched 2026-09-25',
  'url': 'https://docs.sglang.ai/advanced_features/deterministic_inference.html',
  'quote': ['The main source is varying batch sizes. Different batch sizes cause GPU kernels to split reduction '
            'operations differently, leading to different addition orders.'],
  'raw_file': 'serving/sglang_det.txt',
  'agent_note': 'States the D3 mechanism.'},
 {'id': 'serving:18',
  'pred': 'D3',
  'reading': 'states',
  'source': "SGLang documentation, 'Deterministic Inference'",
  'version': 'undated page; fetched 2026-09-25',
  'url': 'https://docs.sglang.ai/advanced_features/deterministic_inference.html',
  'quote': ['Building on Thinking Machines Lab’s batch-invariant operators, SGLang achieves fully deterministic '
            'inference while maintaining compatibility with chunked prefill, CUDA graphs, radix cache, and non-greedy '
            'sampling.'],
  'raw_file': 'serving/sglang_det.txt',
  'agent_note': 'States the remedy in a second engine.'},
 {'id': 'serving:19',
  'pred': 'D3',
  'reading': 'states',
  'source': "The SGLang Team, 'Towards Deterministic Inference in SGLang and Reproducible RL Training', LMSYS Org blog",
  'version': 'September 22, 2025 (updated September 24)',
  'url': 'https://lmsys.org/blog/2025-09-22-sglang-deterministic/',
  'quote': ["Compared to the 61.5% slowdown reported in TML's blog, SGLang achieves an average slowdown of only 34.35% "
            'with the FlashInfer and FlashAttention 3 backends',
            'Deterministic inference is generally usable, with most slowdowns ranging from 25% to 45%'],
  'raw_file': 'serving/lmsys_det.txt',
  'agent_note': 'States the cost of batch-invariant kernels in SGLang.'},
 {'id': 'serving:20',
  'pred': 'D3',
  'reading': 'states',
  'source': "The SGLang Team, 'Towards Deterministic Inference in SGLang and Reproducible RL Training', LMSYS Org blog",
  'version': 'September 22, 2025 (updated September 24)',
  'url': 'https://lmsys.org/blog/2025-09-22-sglang-deterministic/',
  'quote': ['the largest source of nondeterminism is the varying batch sizes'],
  'raw_file': 'serving/lmsys_det.txt',
  'agent_note': 'States D3 (citing the TML blog).'},
 {'id': 'serving:21',
  'pred': 'D3',
  'reading': 'bears',
  'source': "Wasti, Ye, Rao, Goin, Zhang, Liu, Gimelshein, Kwon, You, Li (vLLM and TorchTitan Teams), 'No More "
            "Train-Inference Mismatch: Bitwise Consistent On-Policy Reinforcement Learning with vLLM and TorchTitan', "
            'vLLM Blog',
  'version': 'November 10, 2025',
  'url': 'https://blog.vllm.ai/2025/11/10/bitwise-consistent-train-inference.html',
  'quote': ['Our current results show that the bitwise RL run is 2.4x slower than the non-bitwise case.'],
  'raw_file': 'serving/vllm_blog_bi.txt',
  'agent_note': 'States a cost of bitwise-consistent (batch-invariant) train+inference in an RL loop.'},
 {'id': 'serving:22',
  'pred': 'D3',
  'reading': 'bears',
  'source': "Wasti, Ye, Rao, Goin, Zhang, Liu, Gimelshein, Kwon, You, Li (vLLM and TorchTitan Teams), 'No More "
            "Train-Inference Mismatch: Bitwise Consistent On-Policy Reinforcement Learning with vLLM and TorchTitan', "
            'vLLM Blog',
  'version': 'November 10, 2025',
  'url': 'https://blog.vllm.ai/2025/11/10/bitwise-consistent-train-inference.html',
  'quote': ['Kernels for high batch sizes parallelize heavily on the batch dimension, while kernels for low batch '
            'sizes parallelize more within a single instance to have better utilization on parallel cores on GPUs.'],
  'raw_file': 'serving/vllm_blog_bi.txt',
  'agent_note': 'Bears on D3: the kernel-selection mechanism behind batch-size dependence.'},
 {'id': 'serving:23',
  'pred': 'D4',
  'reading': 'states',
  'source': "Kwon et al., 'Efficient Memory Management for Large Language Model Serving with PagedAttention', SOSP "
            '2023, arXiv 2309.06180',
  'version': 'v1, 12 Sep 2023 (only version)',
  'url': 'https://arxiv.org/abs/2309.06180',
  'quote': ['To answer the second question of how to recover an evicted block, we consider two techniques:',
            'In our case, we copy evicted blocks to the CPU memory.',
            'Recomputation. In this case, we simply recompute the KV cache when the preempted sequences are '
            'rescheduled.'],
  'raw_file': 'serving/kwon2023_pagedattention.txt',
  'agent_note': 'States D4 (both mechanisms).'},
 {'id': 'serving:24',
  'pred': 'D4',
  'reading': 'states',
  'source': "Kwon et al., 'Efficient Memory Management for Large Language Model Serving with PagedAttention', SOSP "
            '2023, arXiv 2309.06180',
  'version': 'v1, 12 Sep 2023 (only version)',
  'url': 'https://arxiv.org/abs/2309.06180',
  'quote': ['Our results reveal that swapping incurs excessive overhead with small block sizes. This is because small '
            'block sizes often result in numerous small data transfers between CPU and GPU, which limits the effective '
            'PCIe bandwidth.',
            'recomputation is more efficient when the block size is small, while swapping is more efficient when the '
            'block size is large'],
  'raw_file': 'serving/kwon2023_pagedattention.txt',
  'agent_note': 'States the cost trade-off (swap: transfer bandwidth; recompute: compute).'},
 {'id': 'serving:25',
  'pred': 'D4',
  'reading': 'states',
  'source': "Kwon et al., 'Efficient Memory Management for Large Language Model Serving with PagedAttention', SOSP "
            '2023, arXiv 2309.06180',
  'version': 'v1, 12 Sep 2023 (only version)',
  'url': 'https://arxiv.org/abs/2309.06180',
  'quote': ['The performances of swapping and recomputation depend on the bandwidth between CPU RAM and GPU memory and '
            'the computation power of the GPU.'],
  'raw_file': 'serving/kwon2023_pagedattention.txt',
  'agent_note': "States D4's cost split directly."},
 {'id': 'serving:26',
  'pred': 'D4',
  'reading': 'bears',
  'source': "Sun, Huang, Zhao, Xiao, Zhang, Li, Lin, 'Llumnix: Dynamic Scheduling for Large Language Model Serving', "
            'OSDI 2024, arXiv 2406.03243',
  'version': 'v1, 5 Jun 2024 (only version)',
  'url': 'https://arxiv.org/abs/2406.03243',
  'quote': ['We quantify the preemption loss by measuring the latency penalty caused by preemption, including the '
            'extra queuing time and the recomputing for previous KV cache.',
            'the P99 request experiences a total preemption loss of 50 seconds (preempted twice)'],
  'raw_file': 'serving/sun2024_llumnix.txt',
  'agent_note': 'Bears on D4: measured cost of recompute-based preemption in vLLM (LLaMA-7B, A10).'},
 {'id': 'serving:27',
  'pred': 'D4',
  'reading': 'bears',
  'source': "Sun, Huang, Zhao, Xiao, Zhang, Li, Lin, 'Llumnix: Dynamic Scheduling for Large Language Model Serving', "
            'OSDI 2024, arXiv 2406.03243',
  'version': 'v1, 5 Jun 2024 (only version)',
  'url': 'https://arxiv.org/abs/2406.03243',
  'quote': ['Naïve solutions include recomputing or copying the KV cache of the rescheduled requests, however with '
            'high computation stalls and downtime, reaching over 50× of the decoding cost',
            'Llumnix can safely copy the KV cache of previous tokens in parallel with the computation for new tokens. '
            'In this way, Llumnix achieves near-zero and constant downtime to the rescheduled request.'],
  'raw_file': 'serving/sun2024_llumnix.txt',
  'agent_note': 'Bears on D4: a third option (live migration of KV cache between instances) with downtime independent '
                'of length.'},
 {'id': 'serving:28',
  'pred': 'D4',
  'reading': 'states',
  'source': "Sun, Huang, Zhao, Xiao, Zhang, Li, Lin, 'Llumnix: Dynamic Scheduling for Large Language Model Serving', "
            'OSDI 2024, arXiv 2406.03243',
  'version': 'v1, 5 Jun 2024 (only version)',
  'url': 'https://arxiv.org/abs/2406.03243',
  'quote': ['the downtime of migration is nearly constant with increasing sequence lengths (roughly 20-30 ms), even '
            'shorter than a single decode step.',
            'recomputing an 8k sequence for LLaMA-30B takes 3.5s, which translates to a service stall similar to 54 '
            'decode steps.'],
  'raw_file': 'serving/sun2024_llumnix.txt',
  'agent_note': 'States measured costs of recompute vs migration.'},
 {'id': 'serving:29',
  'pred': 'D4',
  'reading': 'states',
  'source': "Wu, Zhong, Zhang, Liu, Liu, Sun, Huang, Liu, Jin, 'Fast Distributed Inference Serving for Large Language "
            "Models' (FastServe), arXiv 2305.05920",
  'version': 'v3, 25 Sep 2024',
  'url': 'https://arxiv.org/abs/2305.05920',
  'quote': ['FastServe swaps out inactive key-value tensors of jobs to the host memory to accommodate additional '
            'pending jobs, and swaps in key-value tensors back to the GPU memory for upcoming jobs.',
            'The token generation time in the decoding phase is about 60 ms, while the time to swap the key-value '
            'tensors between host memory and GPU memory with PCIe 4.0×16 full bandwidth is about 36 ms.'],
  'raw_file': 'serving/wu2023_fastserve.txt',
  'agent_note': 'States D4 (swap) and its transfer cost (OPT-175B, 16 A100).'},
 {'id': 'serving:30',
  'pred': 'D4',
  'reading': 'states',
  'source': "Wu, Zhong, Zhang, Liu, Liu, Sun, Huang, Liu, Jin, 'Fast Distributed Inference Serving for Large Language "
            "Models' (FastServe), arXiv 2305.05920",
  'version': 'v3, 25 Sep 2024',
  'url': 'https://arxiv.org/abs/2305.05920',
  'quote': ['Strawman solution 2: kill and re-compute low-priority jobs.',
            'the killed jobs lose their generation states, necessitating to rebuild their key-value tensors. This '
            'results in the waste of valuable computational resources and time.'],
  'raw_file': 'serving/wu2023_fastserve.txt',
  'agent_note': 'States D4 (recompute) and its compute cost.'},
 {'id': 'serving:31',
  'pred': 'D4',
  'reading': 'states',
  'source': "Abhyankar, He, Srivatsa, Zhang, Zhang, 'InferCept: Efficient Intercept Support for Augmented Large "
            "Language Model Inference', ICML 2024, arXiv 2402.01869",
  'version': 'v2, 30 May 2024',
  'url': 'https://arxiv.org/abs/2402.01869',
  'quote': ['This approach, which we call Preserve, avoids recomputation but occupies GPU memory during the entire '
            'interception.',
            'Although Swap avoids recomputation and GPU memory wastage, with limited GPU-CPU link bandwidth, '
            'foreground tasks (normal forwarding) could be bottlenecked by waiting for swapping to finish.'],
  'raw_file': 'serving/abhyankar2024_infercept.txt',
  'agent_note': 'States D4 plus a third option (preserve in GPU memory), with the cost of each.'},
 {'id': 'serving:32',
  'pred': 'D4',
  'reading': 'states',
  'source': "Abhyankar, He, Srivatsa, Zhang, Zhang, 'InferCept: Efficient Intercept Support for Augmented Large "
            "Language Model Inference', ICML 2024, arXiv 2402.01869",
  'version': 'v2, 30 May 2024',
  'url': 'https://arxiv.org/abs/2402.01869',
  'quote': ['causing unnecessary recomputation of already computed contexts, which accounts for 37-40% of total model '
            'forwarding time.'],
  'raw_file': 'serving/abhyankar2024_infercept.txt',
  'agent_note': 'States a measured compute cost of discard-and-recompute on pauses for tool calls.'},
 {'id': 'serving:33',
  'pred': 'D4',
  'reading': 'states',
  'source': "Qiao et al., 'ConServe: Fine-Grained GPU Harvesting for LLM Online and Offline Co-Serving', arXiv "
            '2410.01228',
  'version': 'v2, 3 Sep 2025',
  'url': 'https://arxiv.org/abs/2410.01228',
  'quote': ['preempting a request forces a costly choice: either discard the entire KV cache and pay for expensive '
            'recomputation later, or stall the GPU to swap it back and forth to host memory, leading to a collapse in '
            'throughput.',
            'Our profiling shows that under memory pressure, up to 69% of GPU time is wasted on recomputation or '
            'swapping [27].'],
  'raw_file': 'serving/qiao2025_conserve.txt',
  'agent_note': 'States D4 and its cost.'},
 {'id': 'serving:34',
  'pred': 'D4',
  'reading': 'bears',
  'source': "Qiao et al., 'ConServe: Fine-Grained GPU Harvesting for LLM Online and Offline Co-Serving', arXiv "
            '2410.01228',
  'version': 'v2, 3 Sep 2025',
  'url': 'https://arxiv.org/abs/2410.01228',
  'quote': ['ConServe asynchronously checkpoints only the state of the single, newly-generated token after each '
            'iteration per request, eliminating overhead that would otherwise be proportional to the sequence’s '
            'length.',
            'This reduces preemption latency from the hundreds of milliseconds of a full iteration'],
  'raw_file': 'serving/qiao2025_conserve.txt',
  'agent_note': 'Bears on D4: incremental KV checkpointing and layer-wise preemption as a 2025 alternative.'},
 {'id': 'serving:35',
  'pred': 'D4',
  'reading': 'bears',
  'source': "Matteson, 'Re-feeding Is Not Replaying: Measuring Replay Noise in Counterfactual Token-Credit "
            "Estimation', arXiv 2606.15621",
  'version': 'v1, 14 Jun 2026',
  'url': 'https://arxiv.org/abs/2606.15621',
  'quote': ['re-feeding changes the credit estimate at rates 14–28 percentage points above the replica floor',
            'rerunning the harness under vLLM’s batch-invariant kernels makes all three passes identical on every '
            'measured channel, with both disagreement rates exactly zero.'],
  'raw_file': 'serving/matteson2026_refeeding.txt',
  'agent_note': 'Bears on whether recompute (re-feed/prefill) reproduces resumed-KV outputs: not by default; yes under '
                'batch-invariant kernels in the tested configuration.'},
 {'id': 'serving:36',
  'pred': 'D3',
  'reading': 'bears',
  'source': "Matteson, 'Re-feeding Is Not Replaying: Measuring Replay Noise in Counterfactual Token-Credit "
            "Estimation', arXiv 2606.15621",
  'version': 'v1, 14 Jun 2026',
  'url': 'https://arxiv.org/abs/2606.15621',
  'quote': ['Two bit-identical request batches, submitted seconds apart with identical seeds, disagree on 9–23%'],
  'raw_file': 'serving/matteson2026_refeeding.txt',
  'agent_note': 'Bears on D3: run-to-run differences on a stock engine without batch invariance.'},
 {'id': 'serving:37',
  'pred': 'D4',
  'reading': 'bears',
  'source': "Chodavarapu and Xu, 'The Illusion of Equivalence: Systematic FP16 Divergence in KV-Cached Autoregressive "
            "Inference', arXiv 2604.15409",
  'version': 'v1, 16 Apr 2026',
  'url': 'https://arxiv.org/abs/2604.15409',
  'quote': ['cache-ON and cache-OFF execution paths employ different floating-point accumulation orderings which, due '
            'to FP16 non-associativity, produce a deterministic divergence in decoded token sequences.',
            'These findings establish that FP16 KV cache inference is fundamentally non-equivalent to recomputation'],
  'raw_file': 'serving/chodavarapu2026_fp16_kv.txt',
  'agent_note': 'Bears on whether recompute reproduces cached decode outputs: in FP16, it does not (cache-on vs '
                'cache-off decoding).'},
 {'id': 'serving:38',
  'pred': 'D4',
  'reading': 'bears',
  'source': "Chodavarapu and Xu, 'The Illusion of Equivalence: Systematic FP16 Divergence in KV-Cached Autoregressive "
            "Inference', arXiv 2604.15409",
  'version': 'v1, 16 Apr 2026',
  'url': 'https://arxiv.org/abs/2604.15409',
  'quote': ['Controlled FP32 falsification reduces divergence by eight orders of magnitude, eliminates token flips, '
            'and drops the flip rate to exactly 0.0%'],
  'raw_file': 'serving/chodavarapu2026_fp16_kv.txt',
  'agent_note': 'Bears on the same point: FP32 removes the token-level divergence.'},
 {'id': 'serving:39',
  'pred': 'D4',
  'reading': 'bears',
  'source': "Lorup, 'Stage-Replay Divergence Follows the KV Cache: Fixed-Prefix Precision Controls and Bidirectional "
            "Cache Transplantation', arXiv 2607.28495",
  'version': 'v1, 30 Jul 2026',
  'url': 'https://arxiv.org/abs/2607.28495',
  'quote': ['In BF16, replicas remain exact while the constructions differ on 166 suffixes and 20 correctness labels',
            'Exact-token replay can therefore be repeatable without preserving live-state fidelity.'],
  'raw_file': 'serving/lorup2026_stage_replay.txt',
  'agent_note': 'Bears on whether one-shot prefill of identical tokens reproduces the live-cache continuation: not in '
                'BF16 (200 items).'},
 {'id': 'serving:40',
  'pred': 'D4',
  'reading': 'bears',
  'source': "Lorup, 'Stage-Replay Divergence Follows the KV Cache: Fixed-Prefix Precision Controls and Bidirectional "
            "Cache Transplantation', arXiv 2607.28495",
  'version': 'v1, 30 Jul 2026',
  'url': 'https://arxiv.org/abs/2607.28495',
  'quote': ['The BF16 disagreements recur, whereas FP32 produces no decoded disagreement (95% Wilson upper bound '
            '1.88%).'],
  'raw_file': 'serving/lorup2026_stage_replay.txt',
  'agent_note': 'Bears on the same point; precision dependence.'},
 {'id': 'hardware:0',
  'pred': 'D5',
  'reading': 'states',
  'source': 'NVIDIA, "NVIDIA Tesla P100" (Pascal GP100 architecture whitepaper)',
  'version': 'WP-08019-001_v01.1',
  'url': 'https://images.nvidia.com/content/pdf/tesla/whitepaper/pascal-architecture-whitepaper.pdf',
  'quote': ['Compute Preemption is another important new hardware and software feature added to GP100 that allows '
            'compute tasks to be preempted at instruction-level granularity, rather than thread block granularity as '
            'in prior Maxwell and Kepler GPU architectures.',
            'The new Pascal GP100 Compute Preemption feature allows compute tasks running on the GPU to be interrupted '
            'at instruction-level granularity, and their context swapped to GPU DRAM. This permits other applications '
            'to be swapped in and run, followed by the original task’s context being swapped back in to continue '
            'execution where it left off.'],
  'raw_file': 'hardware/pascal_whitepaper.txt',
  'agent_note': 'States the prediction (instruction-level preemption from Pascal GP100; context swapped to DRAM and '
                'back). Vendor whitepaper; no overhead figure given.'},
 {'id': 'hardware:1',
  'pred': 'D5',
  'reading': 'states',
  'source': 'NVIDIA, CUDA C++ Programming Guide (archived)',
  'version': '12.4.0, last updated Mar 07, 2024',
  'url': 'https://docs.nvidia.com/cuda/archive/12.4.0/cuda-c-programming-guide/index.html',
  'quote': ['for devices featuring the Pascal architecture onwards (compute capability with major revision number 6 '
            'and higher), there exists support for Compute Preemption. This allows compute tasks to be preempted at '
            'instruction-level granularity, rather than thread block granularity as in prior Maxwell and Kepler GPU '
            'architecture',
            'However, there will be context switch overheads associated with Compute Preemption, which is '
            'automatically enabled on those devices for which support exists.',
            'Users wishing to avoid context switch overheads associated with different processes can ensure that only '
            'one process is active on the GPU by selecting exclusive-process mode.'],
  'raw_file': 'hardware/cuda_c_programming_guide_12.4.0.txt',
  'agent_note': 'States the prediction (Pascal onward, automatic) and adds that it carries context-switch overheads '
                '(no number). This paragraph is from the archived 12.4.0 guide; the current 13.4.2 guide text contains '
                'no "Compute Preemption" / cudaDevAttrComputePreemptionSupported match (searched).'},
 {'id': 'hardware:2',
  'pred': 'D5',
  'reading': 'bears',
  'source': 'NVIDIA, CUDA Programming Guide (current, PDF)',
  'version': 'Release 13.4.2',
  'url': 'https://docs.nvidia.com/cuda/cuda-programming-guide/pdf/cuda-programming-guide.pdf',
  'quote': ['Stream priorities will not preempt already executing work, or guarantee any specific execution order.',
            'Higher-priority tasks do not preempt already running lower-priority tasks. The GPU does not reassess work '
            'queues during task execution, and increasing a stream’s priority will not interrupt ongoing work.'],
  'raw_file': 'hardware/cuda_programming_guide_13.4.2.txt',
  'agent_note': 'Only bears on it: within one context, stream priority does not preempt running work (a user-level '
                'scheduling statement, not the hardware context-switch mechanism). Current guide 13.4.2.'},
 {'id': 'hardware:3',
  'pred': 'D5',
  'reading': 'bears',
  'source': 'Han, Zhang, Chen, Chen, "Microsecond-scale Preemption for Concurrent GPU-accelerated DNN Inferences" '
            '(REEF), OSDI 2022',
  'version': 'OSDI 2022 proceedings PDF',
  'url': 'https://www.usenix.org/system/files/osdi22-han.pdf',
  'quote': ['Although NVIDIA claims that their GPUs have been equipped with preemption support since Pascal '
            'architecture [51], there is no public available information or a software controllable interface [12, 39, '
            '77].',
            'it is difﬁcult to implement preemptive scheduling on the GPU due to the large context (e.g., a large '
            'amount of registers) [56, 70]. Meanwhile, commodity GPUs also lack hardware support for the preemption '
            'mechanism.',
            'This implies that the running best-effort kernels can be proactively killed and restored without saving '
            'contexts.'],
  'raw_file': 'hardware/reef_osdi22.txt',
  'agent_note': 'Bears on it, partly against the "transparent/usable" reading: the hardware claim is acknowledged but '
                'REEF says there is no public or software-controllable interface; REEF instead kills and re-runs '
                'idempotent kernels (no context save).'},
 {'id': 'hardware:4',
  'pred': 'D5',
  'reading': 'bears',
  'source': 'Fan et al., "GPreempt: GPU Preemptive Scheduling Made General and Efficient", USENIX ATC 2025',
  'version': 'ATC 2025 proceedings PDF',
  'url': 'https://www.usenix.org/system/files/atc25-fan.pdf',
  'quote': ['Unlike CPU-based systems, GPUs lack a user-facing context-switch interface, making resource preemption '
            'more complex.',
            'GPU task contexts are much larger than CPU (44 MB in NVIDIA A100 GPU vs. less than 1 KB in x86 CPU), and '
            'the overhead associated with context switching is considerable.',
            'Through a thorough analysis of NVIDIA open GPU kernel source [24], we discover an undocumented and '
            'little-known hardware resource allocation mechanism: timeslice allocation.',
            'resulting in a per-SM context footprint of 420 KB and an aggregate GPU context of approximately 44.3 MB '
            '[1]. With the memory bandwidth of 1.1 TB/s, context-saving is completed within 40 µs. Our empirical '
            'evaluation reveals a combined overhead of approximately 100 µs (§5.3) for these operations.'],
  'raw_file': 'hardware/gpreempt_atc25.txt',
  'agent_note': 'Bears on it: hardware context switch exists (driven via driver timeslices) with a stated context size '
                '(~44 MB on A100) and ~100 µs combined overhead; no user-facing interface.'},
 {'id': 'hardware:5',
  'pred': 'D5',
  'reading': 'bears',
  'source': 'Hu et al., "Hummingbird: SLO-Oriented GPU Preemption at Microsecond-scale"',
  'version': 'arXiv 2601.04071v2, 10 Feb 2026',
  'url': 'https://arxiv.org/abs/2601.04071',
  'quote': ['enabling microsecond-scale preemption on closed-source GPUs while effectively harvesting idle GPU time '
            'slices.'],
  'raw_file': 'hardware/2601.04071.txt',
  'agent_note': 'Only bears on it: 2026 system-level preemption on closed-source GPUs; not the vendor mechanism.'},
 {'id': 'hardware:6',
  'pred': 'context',
  'reading': 'context',
  'source': 'NVIDIA GPU Operator docs, "Time-Slicing GPUs in Kubernetes"',
  'version': 'latest (fetched 2026-09-25; no date on page)',
  'url': 'https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-sharing.html',
  'quote': ['Unlike Multi-Instance GPU (MIG), there is no memory or fault-isolation between replicas, but for some '
            'workloads this is better than not being able to share at all.'],
  'raw_file': 'hardware/gpu_operator_time_slicing.txt',
  'agent_note': 'Context: time-slicing multiplexes contexts on one GPU without memory/fault isolation.'},
 {'id': 'hardware:7',
  'pred': 'context',
  'reading': 'context',
  'source': 'NVIDIA, Multi-Process Service documentation',
  'version': 'latest, last updated Sep 09, 2026',
  'url': 'https://docs.nvidia.com/deploy/mps/latest/index.html',
  'quote': ['Enabling MPS provides the benefit of improved GPU utilization and reduced GPU context switching.'],
  'raw_file': 'hardware/nvidia_mps.txt',
  'agent_note': 'Context: MPS reduces GPU context switching.'},
 {'id': 'hardware:8',
  'pred': 'context',
  'reading': 'context',
  'source': 'NVIDIA, CUDA Programming Guide (current, PDF)',
  'version': 'Release 13.4.2',
  'url': 'https://docs.nvidia.com/cuda/cuda-programming-guide/pdf/cuda-programming-guide.pdf',
  'quote': ['MPS primarily targets different processes (e.g., MPI programs), allowing them to run on the GPU at the '
            'same time without time-slicing.'],
  'raw_file': 'hardware/cuda_programming_guide_13.4.2.txt',
  'agent_note': 'Context: MPS avoids time-slicing between processes.'},
 {'id': 'hardware:9',
  'pred': 'D6',
  'reading': 'states',
  'source': 'S. Gurfinkel, "Checkpointing CUDA Applications with CRIU", NVIDIA Technical Blog',
  'version': 'Jul 02, 2024 (cuda-checkpoint 550.54.09 in text)',
  'url': 'https://developer.nvidia.com/blog/checkpointing-cuda-applications-with-criu/',
  'quote': ['This utility can be used to transparently checkpoint and restore CUDA state within a running Linux '
            'process.',
            'Any CUDA driver APIs that launch work, manage resources, or otherwise impact GPU state are locked. '
            'Already submitted CUDA work, including stream callbacks, is completed. Device memory is copied to the '
            'host, into allocations managed by the CUDA driver. All CUDA GPU resources are released.',
            'GPUs are re-acquired by the process. Device memory is copied back to the GPU and GPU memory mappings are '
            'restored at their original addresses. CUDA objects such as streams and contexts are restored. CUDA driver '
            'APIs are unlocked.',
            'The response is 102, showing that earlier GPU operations were persisted correctly.'],
  'raw_file': 'hardware/nvidia_blog_criu.txt',
  'agent_note': 'States the prediction: transparent per-process CUDA checkpoint/restore with CRIU; suspend waits for '
                'submitted work (a quiescent point, not mid-kernel).'},
 {'id': 'hardware:10',
  'pred': 'D6',
  'reading': 'bears',
  'source': 'S. Gurfinkel, "Checkpointing CUDA Applications with CRIU", NVIDIA Technical Blog',
  'version': 'Jul 02, 2024 (cuda-checkpoint 550.54.09 in text)',
  'url': 'https://developer.nvidia.com/blog/checkpointing-cuda-applications-with-criu/',
  'quote': ['x64 only. Acts upon a single process, not a process tree. Doesn’t support UVM or IPC memory. Doesn’t '
            'support GPU migration. Waits for already-submitted CUDA work to finish before completing a checkpoint.',
            'Preemption of lower-priority work on a single node by checkpointing the preempted task'],
  'raw_file': 'hardware/nvidia_blog_criu.txt',
  'agent_note': 'Bears on it: limitations as of driver 550 (2024), incl. no GPU migration; preemption named as a use '
                'case.'},
 {'id': 'hardware:11',
  'pred': 'D6',
  'reading': 'states',
  'source': 'NVIDIA, CUDA Driver API Reference Manual, 6.1 CUDA Checkpointing',
  'version': 'v13.4, last updated Sep 14, 2026',
  'url': 'https://docs.nvidia.com/cuda/cuda-driver-api/cuda_driver_api/group__CUDA__CHECKPOINT.html',
  'quote': ['The CUDA checkpoint and restore API’s provide a way to save and restore GPU state for full process '
            'checkpoints when used with CPU side process checkpointing solutions. They can also be used to pause GPU '
            'work and suspend a CUDA process to allow other applications to make use of GPU resources.',
            'Checkpoint and restore capabilities are currently restricted to Linux.',
            'Lock the CUDA process specified by pid which will block further CUDA API calls.',
            'GPU UUID pairs can be specified in args to remap the process old GPUs onto new GPUs. The GPU to restore '
            'onto needs to have enough memory and be of the same chip type as the old GPU.'],
  'raw_file': 'hardware/cuda_driver_api_13.4_checkpoint.txt',
  'agent_note': 'States the prediction (driver API, v13.4); restore onto a different GPU of the same chip type is now '
                'documented (contrast the 2024 blog "no GPU migration").'},
 {'id': 'hardware:12',
  'pred': 'D6',
  'reading': 'bears',
  'source': 'NVIDIA, CUDA Driver API Reference Manual, 7.49 CUcheckpointGpuPair',
  'version': 'v13.4, last updated Sep 14, 2026',
  'url': 'https://docs.nvidia.com/cuda/cuda-driver-api/cuda_driver_api/structCUcheckpointGpuPair.html',
  'quote': ['CUDA checkpoint GPU UUID pairs for device remapping during restore.'],
  'raw_file': 'hardware/cuda_driver_api_13.4_gpupair.txt',
  'agent_note': 'Bears on it: device remapping on restore (v13.4).'},
 {'id': 'hardware:13',
  'pred': 'D6',
  'reading': 'bears',
  'source': 'NVIDIA, CUDA Programming Guide (current, PDF)',
  'version': 'Release 13.4.2',
  'url': 'https://docs.nvidia.com/cuda/cuda-programming-guide/pdf/cuda-programming-guide.pdf',
  'quote': ['CUDA Checkpoint does not guarantee that localized green contexts retain their localization properties '
            'when restored on a different device. The application may exhibit reduced performance after a restore.'],
  'raw_file': 'hardware/cuda_programming_guide_13.4.2.txt',
  'agent_note': 'Bears on it: restore on a different device is possible but some properties are not guaranteed '
                '(performance, not correctness, is named).'},
 {'id': 'hardware:14',
  'pred': 'D6',
  'reading': 'states',
  'source': 'Stoyanov et al., "CRIUgpu: Transparent Checkpointing of GPU-Accelerated Workloads"',
  'version': 'arXiv 2502.16631v1, 23 Feb 2025',
  'url': 'https://arxiv.org/abs/2502.16631',
  'quote': ['(ii) Checkpointing the GPU state of CUDA tasks into host memory allocations managed by the driver, and '
            'releasing all GPU resources held by the application. Executing these steps results in the CUDA tasks '
            'entering a checkpointed state without direct reference to GPU hardware.',
            'CRIUgpu relies on a locking mechanism that ensure the execution of tasks is suspended before creating a '
            'checkpoint. This guarantees consistent CPU-GPU snapshots and deterministic restore operations',
            'CRIUgpu can create unified CPU-GPU snapshots for large models in single- and multi-GPU setups without '
            'steady-state performance overhead.'],
  'raw_file': 'hardware/2502.16631.txt',
  'agent_note': 'States the prediction (unified transparent CPU+GPU snapshot via cuda-checkpoint + CRIU; authors claim '
                'deterministic restore).'},
 {'id': 'hardware:15',
  'pred': 'D6',
  'reading': 'bears',
  'source': 'Stoyanov et al., "CRIUgpu: Transparent Checkpointing of GPU-Accelerated Workloads"',
  'version': 'arXiv 2502.16631v1, 23 Feb 2025',
  'url': 'https://arxiv.org/abs/2502.16631',
  'quote': ['Checkpointed applications can only be restored on systems with compatible GPU topology with the same '
            'number, type, memory size, VRAM accessibility by the host, and connectivity between GPUs.',
            'at the time of writing, the cuda-checkpoint tool does not support checkpoint/restore operations with '
            'NCCL.',
            'Replaying the logged API calls during restore can also lead to prolonged recovery times and inconsistent '
            'GPU state, especially with non-deterministic operations such as floating-point computations [52].'],
  'raw_file': 'hardware/2502.16631.txt',
  'agent_note': 'Bears on it: restore constrained to same topology; no NCCL support (Feb 2025); API-replay '
                'alternatives risk inconsistent state.'},
 {'id': 'hardware:16',
  'pred': 'D6',
  'reading': 'bears',
  'source': 'Stoyanov et al., "CRIUgpu: Transparent Checkpointing of GPU-Accelerated Workloads"',
  'version': 'arXiv 2502.16631v1, 23 Feb 2025',
  'url': 'https://arxiv.org/abs/2502.16631',
  'quote': ['CRIUgpu Checkpoint (s) 77.40 146.43 88.81 130.81 CRIUgpu Restore (s) 38.83 98.91 43.43 145.14 GPU memory '
            '54 GB 54 GB 58 GB 58 GB Table 2.CRIUgpu checkpoint and restore times for Llama 3.1 and GPT-2 model '
            'training on a single H100 80GB and A100 80GB GPU.',
            'A key insight is the dominance of GPU memory in overall checkpoint size, consistently exceeding 80% and '
            'often surpassing 90%'],
  'raw_file': 'hardware/2502.16631.txt',
  'agent_note': 'Bears on it (cost): Table 2 reports 77.40-146.43 s checkpoint and 38.83-145.14 s restore for 54-58 GB '
                'of GPU memory; checkpoint dominated by GPU memory.'},
 {'id': 'hardware:17',
  'pred': 'context',
  'reading': 'context',
  'source': 'Hu et al., "Hummingbird: SLO-Oriented GPU Preemption at Microsecond-scale"',
  'version': 'arXiv 2601.04071v2, 10 Feb 2026',
  'url': 'https://arxiv.org/abs/2601.04071',
  'quote': ['Approaches like Gandiva [86] suspend and resume models, moving states between GPU and host memory'],
  'raw_file': 'hardware/2601.04071.txt',
  'agent_note': 'Context: suspend/resume by moving state to host memory in cluster schedulers.'},
 {'id': 'hardware:18',
  'pred': 'D7',
  'reading': 'states',
  'source': 'Vadari, "The Model Parking Tax: Quantifying the Hidden Energy Cost of Always-On GPU Model Deployment"',
  'version': 'arXiv 2605.23918v1, 15 Apr 2026',
  'url': 'https://arxiv.org/abs/2605.23918',
  'quote': ['the CUDA context forces a discrete DVFS transition consuming +26–66W over bare idle (26–50 W on HBM '
            'architectures, 66 W on GDDR6), while the marginal VRAM effect is bounded below measurement relevance',
            'Our results identify a constraint consistent across all tested architectures: idle-with-context power is '
            'determined by DVFS state, not memory occupancy.',
            'Bare idle (W) 71.8 53.7 35.6 SM clock, bare (MHz) 345 210 210 CUDA ctx power (W) 121.7 80.0 102.1 SM '
            'clock, ctx (MHz) 1980 1410 2520 Context overhead (W) +49.9 +26.3 +66.4 Context (% of TDP) 7.1% 8.8% 19.0%',
            'CUDA active(1980 MHz): 7 GPUs, mean 145.5 W± 11.2 W. The CUDA context effect is+70.9W'],
  'raw_file': 'hardware/2605.23918.txt',
  'agent_note': 'Bears on it directly (idle-with-context: 121.7 W H100, 80.0 W A100, 102.1 W L40S controlled; 145.5 W '
                'H100 fleet telemetry). Whether that is a "substantial fraction of active power" is not stated here; '
                'the paper reports the context step as 7-19% of TDP. Single-author preprint (v1).'},
 {'id': 'hardware:19',
  'pred': 'D7',
  'reading': 'bears',
  'source': 'Vadari, "The Model Parking Tax: Quantifying the Hidden Energy Cost of Always-On GPU Model Deployment"',
  'version': 'arXiv 2605.23918v1, 15 Apr 2026',
  'url': 'https://arxiv.org/abs/2605.23918',
  'quote': ['The 2024 US Data Center Energy Usage Report estimates GPU idle power at∼20% of Thermal Design Power (TDP) '
            '[2].',
            'Once a CUDA context is created—by any CUDA runtime call—the SM clock jumps to maximum boost andremains '
            'thereat 0% utilization [ 1].',
            'All three approaches maintain at least one active CUDA context, meaning the DVFS overhead we measure '
            'persists.'],
  'raw_file': 'hardware/2605.23918.txt',
  'agent_note': 'Bears on it: ~20% of TDP idle is quoted SECONDHAND (the LBNL report itself returned 403 on the day). '
                'MIG/MPS/time-slicing keep a context, so the step persists.'},
 {'id': 'hardware:20',
  'pred': 'D7',
  'reading': 'states',
  'source': 'Lei et al., "The Energy Cost of Execution-Idle in GPU Clusters"',
  'version': 'arXiv 2604.04745v1, 6 Apr 2026',
  'url': 'https://arxiv.org/abs/2604.04745',
  'quote': ['GPUs are becoming a major contributor to data center power, yet unlike CPUs, they can remain at high '
            'power even when visible activity is near zero. We call this stateexecution-idle.',
            'yet power stays around 110 W. Only after the program terminates does the GPU enterdeep idle, where power '
            'drops to the baseline level of roughly 35 W.',
            'It accounts for 48% of energy in long-lived, academic serving workloads and 7–65% across five replays of '
            'industry-derived traces',
            'setting only the SM-related clock to the available minimum reduces execution-idle power from 105 W to 61 '
            'W, while lowering both SM and memory clocks further reduces it to 35 W (deep idle power).'],
  'raw_file': 'hardware/2604.04745.txt',
  'agent_note': 'States the prediction in its own terms (a loaded-but-inactive GPU draws well above deep idle; large '
                'share of serving energy); clock downscaling recovers most of it.'},
 {'id': 'hardware:21',
  'pred': 'D7',
  'reading': 'bears',
  'source': 'Argerich, Fürst, Patiño-Martínez, "Watt Counts: Energy-Aware Benchmark for Sustainable LLM Inference on '
            'Heterogeneous GPU Architectures"',
  'version': 'arXiv 2604.09048v1, 10 Apr 2026',
  'url': 'https://arxiv.org/abs/2604.09048',
  'quote': ['The H100 with a relatively high idle power (59W) and midrange max power draw (416W)',
            '(L4: 17W, 73W, T4: 12W, 82W, A30: 27W, 171W)'],
  'raw_file': 'hardware/2604.09048.txt',
  'agent_note': 'Bears on it: idle vs max measured power per GPU as the paper reports them. Idle here is not stated to '
                'be with a resident model.'},
 {'id': 'hardware:22',
  'pred': 'D7',
  'reading': 'bears',
  'source': 'Vercellino et al., "Measurement of Generative AI Workload Power Profiles for Whole-Facility Data Center '
            'Infrastructure Planning"',
  'version': 'arXiv 2604.07345v1, 8 Apr 2026',
  'url': 'https://arxiv.org/abs/2604.07345',
  'quote': ['the measured average and standard deviation for idle power of operation were 72.5 W (±0.1 W) for each GPU',
            'The HPL benchmark was used to stress-test GPUs, yielding a mean peak power of 696 W.'],
  'raw_file': 'hardware/2604.07345.txt',
  'agent_note': 'Bears on it: H100 SXM idle 72.5 W vs 696 W HPL stress as reported; idle without a resident job.'},
 {'id': 'hardware:23',
  'pred': 'D7',
  'reading': 'bears',
  'source': 'Patel et al., "POLCA: Power Oversubscription in LLM Cloud Providers"',
  'version': 'arXiv 2308.12908v1, 24 Aug 2023',
  'url': 'https://arxiv.org/abs/2308.12908',
  'quote': ['While RoBERTa is still at 75% of the TDP at the iteration boundary, GPT-NeoX drops down to 50%, and '
            'Flan-T5 goes down all the way to 20%, which corresponds to the idle power of the GPUs.'],
  'raw_file': 'hardware/2308.12908.txt',
  'agent_note': 'Bears on it: A100 idle ~20% of TDP; power at training iteration boundaries between idle and 75% of '
                'TDP. The task names the ASPLOS 2024 version "Characterizing Power Management Opportunities for LLMs '
                'in the Cloud"; only the arXiv v1 was fetched.'},
 {'id': 'hardware:24',
  'pred': 'D7',
  'reading': 'bears',
  'source': 'You, Chung, Chowdhury, "Zeus: Understanding and Optimizing GPU Energy Consumption of DNN Training", NSDI '
            '2023',
  'version': 'arXiv 2208.06102v2, 29 Sep 2022',
  'url': 'https://arxiv.org/abs/2208.06102',
  'quote': ['its average power consumption tends closer to 90W, which is close to the GPU’s idle power consumption of '
            '70W.'],
  'raw_file': 'hardware/2208.06102.txt',
  'agent_note': 'Bears on it: V100 (power limit range 100-250 W per the paper) idle 70 W.'},
 {'id': 'hardware:25',
  'pred': 'context',
  'reading': 'context',
  'source': 'Chung et al., "The ML.ENERGY Benchmark", NeurIPS D&B 2025',
  'version': 'arXiv 2505.06371v2, 16 Oct 2025',
  'url': 'https://arxiv.org/abs/2505.06371',
  'quote': ['Generally, LLMs and VLMs consume significantly less power than the GPU’s TDP because LLM decoding, the '
            'dominant operation for LLM serving, is memory-intensive and does not fully utilize the GPU’s compute '
            'resources.'],
  'raw_file': 'hardware/2505.06371.txt',
  'agent_note': 'Context for the denominator of D7: active LLM decode power is well below TDP.'},
 {'id': 'hardware:26',
  'pred': 'context',
  'reading': 'context',
  'source': 'Patel et al., "Splitwise: Efficient generative LLM inference using phase splitting"',
  'version': 'arXiv 2311.18677v2, 20 May 2024',
  'url': 'https://arxiv.org/abs/2311.18677',
  'quote': ['the token phase is memory bound and its power draw does not vary when increasing the number of tokens to '
            'process.',
            'the token generation phase incurs almost no latency impact when power capping by over 50% ( i.e., 700 to '
            '350W).'],
  'raw_file': 'hardware/2311.18677.txt',
  'agent_note': 'Context for D7 denominator: decode-phase power.'},
 {'id': 'hardware:27',
  'pred': 'context',
  'reading': 'context',
  'source': 'Samsi et al., "From Words to Watts: Benchmarking the Energy Costs of Large Language Model Inference"',
  'version': 'arXiv 2310.03003v1, 4 Oct 2023',
  'url': 'https://arxiv.org/abs/2310.03003',
  'quote': ['For a 30% reduction in power from 250W to 175W, the inference time increases by an average of 6.7% for a '
            'corresponding average reduction in total energy by 23.21%.'],
  'raw_file': 'hardware/2310.03003.txt',
  'agent_note': 'Context: power capping and inference energy (V100/A100); no idle figure found in this paper.'},
 {'id': 'hardware:28',
  'pred': 'context',
  'reading': 'context',
  'source': 'Kwon et al., "Efficient Memory Management for Large Language Model Serving with PagedAttention" (vLLM), '
            'SOSP 2023',
  'version': 'arXiv 2309.06180v1, 12 Sep 2023',
  'url': 'https://arxiv.org/abs/2309.06180',
  'quote': ['Approximately 65% of the memory is allocated for the model weights, which remain static during serving. '
            'Close to 30% of the memory is used to store the dynamic states of the requests.',
            'the KV cache of a single token demands 800 KB of space, calculated as 2 (key and value vectors)× 5120 '
            '(hidden state size)× 40 (number of layers)× 2 (bytes per FP16).',
            'the memory required to store the KV cache of one request can be as much as 1.6 GB.'],
  'raw_file': 'hardware/2309.06180.txt',
  'agent_note': 'Context: Transformer state at a token boundary is the KV cache, growing per token (OPT-13B figures).'},
 {'id': 'hardware:29',
  'pred': 'D4',
  'reading': 'states',
  'source': 'Kwon et al., "Efficient Memory Management for Large Language Model Serving with PagedAttention" (vLLM), '
            'SOSP 2023',
  'version': 'arXiv 2309.06180v1, 12 Sep 2023',
  'url': 'https://arxiv.org/abs/2309.06180',
  'quote': ['In our case, we copy evicted blocks to the CPU memory.',
            'Recomputation. In this case, we simply recompute the KV cache when the preempted sequences are '
            'rescheduled.',
            'The performances of swapping and recomputation depend on the bandwidth between CPU RAM and GPU memory and '
            'the computation power of the GPU.'],
  'raw_file': 'hardware/2309.06180.txt',
  'agent_note': 'States the prediction (swap vs recompute; transfer vs compute cost).'},
 {'id': 'hardware:30',
  'pred': 'context',
  'reading': 'context',
  'source': 'Gu, Dao, "Mamba: Linear-Time Sequence Modeling with Selective State Spaces"',
  'version': 'arXiv 2312.00752v2, 31 May 2024',
  'url': 'https://arxiv.org/abs/2312.00752',
  'quote': ['unrolling the model autoregressively during inference requires only constant time per step since it does '
            'not require a cache of previous elements.',
            'autoregressive inference requires explicitly storing the entire context (i.e. the KV cache), which '
            'directly causes the slow linear-time inference and quadratic-time training of Transformers. On the other '
            'hand, recurrent models are efficient because they have a finite state, implying constant-time inference '
            'and linear-time training.',
            'efficient models must have a small state, while effective models must have a state that contains all '
            'necessary information from the context.'],
  'raw_file': 'hardware/2312.00752.txt',
  'agent_note': 'Context: SSM state at a token boundary is fixed-size; Transformer state is the whole context.'},
 {'id': 'hardware:31',
  'pred': 'context',
  'reading': 'context',
  'source': 'Peng et al., "RWKV: Reinventing RNNs for the Transformer Era"',
  'version': 'arXiv 2305.13048v2, 11 Dec 2023',
  'url': 'https://arxiv.org/abs/2305.13048',
  'quote': ['allows us to formulate the model as either a Transformer or an RNN, thus parallelizing computations '
            'during training and maintains constant computational and memory complexity during inference.',
            'RWKV (ours) O(Td) O(d) Table 1: Inference complexity comparison with different Transformers.'],
  'raw_file': 'hardware/2305.13048.txt',
  'agent_note': 'Context: RWKV inference memory O(d), constant in sequence length.'},
 {'id': 'hardware:32',
  'pred': 'context',
  'reading': 'context',
  'source': 'Han, Zhang, Chen, Chen, "Microsecond-scale Preemption for Concurrent GPU-accelerated DNN Inferences" '
            '(REEF), OSDI 2022',
  'version': 'OSDI 2022 proceedings PDF',
  'url': 'https://www.usenix.org/system/files/osdi22-han.pdf',
  'quote': ['REEF devises a reset-based preemption scheme that launches a real-time kernel on the GPU by proactively '
            'killing and restoring best-effort kernels at microsecond-scale.'],
  'raw_file': 'hardware/reef_osdi22.txt',
  'agent_note': 'Context: kill-and-rerun preemption (idempotent kernels) as the alternative to context save.'}]
