"""PRED70: the 70 declared predictions (Predictions70/DECLARATION.md; prompt-log entry 234). Pushed before any model exists.

Each entry: (id, batch, cls, system, ingredient, Q, null, H0, forecast).
  Q         CRR's prediction for this system, in the system's own terms, with its decisive quantity and threshold.
  null      the replacement for the CRR ingredient (the harness's T-G).
  H0        the domain's own model or theorem for the same target (the harness's T-N), or 'none'.
  forecast  the investigator's forecast of the harness outcome, written now (ADDS / WRONG / REDUNDANT-IG /
            REDUNDANT-DOMAIN / INTERNAL / PROPOSES / UNSTATED).
Fixed CRR knobs (P3 is not fixed by CRR): A6 memory weight q = 0.5 per occasion (geometric q^k), with the grid
q in {0.25, 0.5, 0.75} printed as a sensitivity only; H-L5 margins decided by the paired bootstrap of the instrument
(src/crr/instrument/core.py: regularity) at n_boot 2000, seed 0; 'more than 1 %' is the harness's TOL_G.
"""

P = [
 # ---- P01 oscillators with events of their own (H-L5 class claim; H-CUT antipode against extremum)
 ("P01-1", 1, "cycle", "Hodgkin-Huxley neuron, I = 10 uA/cm2 + white noise sd 1, 200 spikes", "H-L5", "the Fisher arc of the voltage between spikes is more regular than the inter-spike interval: CV(arc) < CV(ISI) with the bootstrap CI excluding 0", "CV of the ISI (clock)", "renewal ISI statistics (a limit cycle perturbed by noise is clock-regular)", "WRONG"),
 ("P01-2", 1, "cycle", "Morris-Lecar neuron (type I parameters) near the SNIC bifurcation with noise", "H-L5", "CV(arc) < CV(ISI), CI excluding 0", "CV(ISI)", "type-I excitability: ISI variance dominated by the slow passage near the ghost", "WRONG"),
 ("P01-3", 1, "cycle", "Stuart-Landau oscillator with frequency noise (phase diffusion D = 0.05)", "H-L5", "CV(arc per cycle) < CV(period)", "CV(period)", "phase diffusion: period CV = sqrt(D T)/T, arc per cycle fixed by the amplitude", "REDUNDANT-DOMAIN"),
 ("P01-4", 1, "cycle", "Oregonator (Belousov-Zhabotinsky), relaxation regime, epsilon = 0.04", "H-CUT (A3)", "the system's own event (the fast rise of x) lies nearer the antipodal cut of the analytic-signal phase than the waveform extremum on at least 2/3 of cycles", "the extremum (peak cut)", "none", "WRONG"),
 ("P01-5", 1, "cycle", "Lorenz system (sigma 10, rho 28, beta 8/3): lobe switches as own events", "H-L5", "the Fisher arc (identity metric on x) between lobe switches is more regular than the time between switches", "CV(time between switches)", "none (chaotic residence times, exponential tail)", "WRONG"),
 # ---- P02 stick-slip, relaxation and recharge
 ("P02-1", 2, "fric", "Burridge-Knopoff two-block spring-slider with rate-and-state friction under slow loading", "H-L5", "arc of the block displacement since the last slip is more regular than time since the last slip: CV(arc) < CV(clock), CI excluding 0", "CV(clock)", "none (the L5 claim's own class, synthetic)", "ADDS"),
 ("P02-2", 2, "fric", "Olami-Feder-Christensen earthquake cellular automaton (alpha 0.2, 50 x 50), events above the median size", "H-L5", "the loading accumulated between large events (natural-time arc) is more regular than clock time", "CV(clock)", "Varotsos natural time: event-count time", "REDUNDANT-DOMAIN"),
 ("P02-3", 2, "fric", "dripping faucet (mass-spring with mass loss at detachment), flow in the period-1 regime with noise", "H-L5", "CV(inflow mass between drops) < CV(inter-drop time)", "CV(inter-drop time)", "the mass-threshold model: drop at fixed critical mass", "REDUNDANT-DOMAIN"),
 ("P02-4", 2, "fric", "geyser as an integrate-and-fire recharge with noisy recharge rate", "H-L5", "CV(recharge arc) < CV(eruption interval)", "CV(interval)", "integrate-and-fire: the threshold on the integrated input", "REDUNDANT-DOMAIN"),
 ("P02-5", 2, "fric", "Suarez-Schopf delayed-oscillator El Nino model (alpha 0.75, delay 6) with noise", "H-CUT (A3)", "the sign change of the temperature anomaly lies at the antipode of the analytic-signal phase from the last peak more often than halfway in clock time", "the clock midpoint", "delay-oscillator period ~ 4 delays", "INTERNAL"),
 # ---- P03 remembered state (A6) and stability thresholds
 ("P03-1", 3, "mem", "Beverton-Holt recruitment with density remembered by A6 (q = 0.5)", "A6", "the equilibrium remains stable for every growth rate (no flip bifurcation), as without memory", "instantaneous density", "Beverton-Holt is monotone: globally stable equilibrium", "REDUNDANT-IG"),
 ("P03-2", 3, "mem", "Nicholson blowfly delay equation with the delayed density replaced by the A6 remembered density", "A6", "the Hopf threshold on the delay-product moves by more than 1 % and in the stabilising direction", "the pure delay", "distributed-delay (gamma kernel) Hopf thresholds", "REDUNDANT-DOMAIN"),
 ("P03-3", 3, "mem", "cobweb market (linear supply and demand, slope ratio b/d = 1.2) with prices expected by A6", "A6", "adaptive expectations stabilise the cobweb: the critical slope ratio exceeds 1 by more than 1 %", "naive expectations", "Nerlove adaptive expectations: stable iff b/d < (2 - w)/w", "REDUNDANT-DOMAIN"),
 ("P03-4", 3, "mem", "SIS epidemic (beta 0.3, gamma 0.1) with contact reduced by A6-remembered prevalence", "A6", "remembered prevalence induces damped oscillations absent without memory (a complex leading eigenvalue at the endemic state)", "instantaneous prevalence", "none cited", "ADDS"),
 ("P03-5", 3, "mem", "Goodwin growth cycle with the wage bargain on A6-remembered employment", "A6", "memory turns the neutral Goodwin centre into a stable focus (negative real part beyond 1 %)", "instantaneous employment", "Goodwin: a conservative (neutral) cycle", "ADDS"),
 # ---- P04 learning and cognition
 ("P04-1", 4, "learn", "Rescorla-Wagner learning of a reward that switches between 0.2 and 0.8 every 50 trials", "A6", "a bounded Frechet-mean (q = 0.5 geometric weights) tracker has lower mean squared error than the RW delta rule at its best rate", "RW at its best learning rate", "the delta rule is exactly an exponential moving average (A6 with geometric weights)", "REDUNDANT-DOMAIN"),
 ("P04-2", 4, "learn", "drift-diffusion decision (drift 0.2, bound 1, noise 1)", "A1' natural time", "decision time measured in evidence-arc units is less variable than clock decision time", "clock decision time", "Wald: the bound is fixed in evidence units, so evidence at decision is constant", "REDUNDANT-DOMAIN"),
 ("P04-3", 4, "learn", "serial-position memory: 20 items, recency by exponential decay, primacy by rehearsal", "P3", "P3's geometric occasion weights reproduce the recency slope of the exponential-decay model within 1 %", "equal weights", "exponential trace decay", "REDUNDANT-DOMAIN"),
 ("P04-4", 4, "learn", "power law of practice: RT = a N^-b fitted to a simulated learner with exponential components", "A6", "a bounded (A6) memory predicts an exponential, not power-law, approach: exponential fits better than power (lower SSE)", "the power law", "Heathcote, Brown and Mewhort: exponential fits individual data better", "REDUNDANT-DOMAIN"),
 ("P04-5", 4, "learn", "temporal-difference learning on a 5-state chain with a reward change at trial 500", "A6", "relearning after the change is faster with A6-bounded value memory than with a decaying learning rate 1/n", "1/n learning rate", "constant step-size TD tracks non-stationarity (Sutton and Barto)", "REDUNDANT-DOMAIN"),
 # ---- P05 continual learning and optimisation (synthetic)
 ("P05-1", 5, "cl", "two-task linear regression, SGD, EWC penalty: forgetting against path length and endpoint", "D6/H-T1", "forgetting tracks path length better than the old-probe endpoint (R2 higher by 0.05)", "the old-probe endpoint", "convex learner: forgetting is a function of the endpoint only (SCOPE lemma)", "WRONG"),
 ("P05-2", 5, "cl", "heavy-ball momentum on a two-task quadratic with the equanimity weight Omega = 1", "H-EQ", "Omega = 1 is within a step of the best fixed weight (reduces to a constant)", "the best fixed weight", "a fixed Laplace weight is optimal on a quadratic", "REDUNDANT-IG"),
 ("P05-3", 5, "cl", "SGD with warm restarts (SGDR) on a noisy quadratic: restarts as cuts", "A3", "restarting at the antipode of the loss oscillation phase reaches a lower final loss than restarting on a fixed schedule", "fixed-period restarts", "none cited", "WRONG"),
 ("P05-4", 5, "cl", "early stopping on a noisy linear model: stop at a cut of the validation-loss phase", "A3", "stopping at the first antipodal cut of the validation-loss oscillation beats patience-based early stopping in test loss by more than 1 %", "patience-based stopping", "none cited", "WRONG"),
 ("P05-5", 5, "cl", "online mean estimation under drift: A6 bounded mean against a Kalman filter with known drift variance", "A6", "the A6 tracker's error is within 1 % of the Kalman filter's", "the Kalman filter", "the steady-state Kalman gain is an exponential moving average", "REDUNDANT-DOMAIN"),
 # ---- P06 physics
 ("P06-1", 6, "phys", "Kuramoto model (N = 200, Lorentzian frequencies) with A6-remembered mean field", "A6", "memory raises the critical coupling above 2 gamma by more than 1 %", "the instantaneous mean field", "Kc = 2 gamma (Kuramoto); delayed/filtered coupling results", "REDUNDANT-DOMAIN"),
 ("P06-2", 6, "phys", "mean-field Ising with Glauber dynamics and A6-remembered magnetisation in the field", "A6", "the critical temperature is unchanged by memory (the fixed point is the same)", "instantaneous magnetisation", "Tc = J z (mean-field)", "REDUNDANT-IG"),
 ("P06-3", 6, "phys", "radioactive decay chain A -> B -> C: B-decay events in natural time", "H-L5", "counts between B decays are more regular in natural time (event count) than in clock time", "clock time", "a Poisson process: natural time is uniform by construction", "REDUNDANT-DOMAIN"),
 ("P06-4", 6, "phys", "driven damped pendulum at resonance: energy per cycle", "D5 occasions", "the energy dissipated per occasion (between antipodal cuts) is constant in steady state", "per clock interval", "steady state: dissipation per period equals work per period", "REDUNDANT-DOMAIN"),
 ("P06-5", 6, "phys", "flashing Brownian ratchet: switching at antipodal cuts of the particle's phase", "A3", "switching at the antipodal cut gives a higher drift velocity than periodic switching at the optimal period", "optimal periodic switching", "feedback ratchets beat open-loop ratchets (Cao, Dinis, Parrondo)", "REDUNDANT-DOMAIN"),
 # ---- P07 chemistry and cell biology
 ("P07-1", 7, "chem", "Michaelis-Menten kinetics: product formation against substrate depletion", "A1' own unit", "the reaction's own unit (Km) makes the progress curve universal: curves at different S0/Km collapse only in Km units", "clock units", "the integrated Michaelis-Menten equation (Lambert W)", "REDUNDANT-DOMAIN"),
 ("P07-2", 7, "chem", "genetic toggle switch (Gardner) with noise: switching events", "H-L5", "the arc between switches is more regular than residence times", "CV(residence time)", "Kramers escape: exponential residence times", "WRONG"),
 ("P07-3", 7, "chem", "repressilator (Elowitz-Leibler) with noise: protein peaks as own events", "H-CUT (A3)", "the promoter-state switch lies nearer the antipodal cut than the protein extremum", "the extremum", "none", "INTERNAL"),
 ("P07-4", 7, "chem", "Goodwin circadian oscillator: phase-response to a light pulse", "A3", "the crossover from advance to delay in the PRC lies at the antipode of subjective noon", "the PRC's own crossover", "phase-response theory (infinitesimal PRC of the limit cycle)", "REDUNDANT-DOMAIN"),
 ("P07-5", 7, "chem", "Dupont calcium oscillations: spike timing under IP3 noise", "H-L5", "CV(arc between Ca spikes) < CV(inter-spike interval)", "CV(ISI)", "stochastic Ca spikes: ISI SD proportional to mean (Skupin)", "WRONG"),
 # ---- P08 ecology and evolution
 ("P08-1", 8, "eco", "Rosenzweig-MacArthur predator-prey with predators responding to A6-remembered prey", "A6", "memory lowers the enrichment level at which the paradox-of-enrichment Hopf occurs by more than 1 %", "instantaneous prey", "Rosenzweig: Hopf at K* = h(1 + m...)", "ADDS"),
 ("P08-2", 8, "eco", "MacArthur-Wilson island biogeography with A6-remembered species pool", "A6", "the equilibrium richness is unchanged by memory", "instantaneous pool", "S* = P I/(I + E)", "REDUNDANT-IG"),
 ("P08-3", 8, "eco", "Wright-Fisher drift, N = 100: fixation times in natural time (generations of heterozygosity loss)", "A1' natural time", "the fixation 'arc' (Fisher-Rao arc of the allele frequency path) is less variable than the fixation time", "fixation time", "Kimura: mean fixation time 4N ln-type; arc from 0 to 1 is pi (fixed)", "INTERNAL"),
 ("P08-4", 8, "eco", "host-parasite Red Queen matching-alleles cycles", "H-L5", "arc per cycle is more regular than the cycle period", "CV(period)", "none", "WRONG"),
 ("P08-5", 8, "eco", "logistic harvest with the quota set on A6-remembered stock", "A6", "memory destabilises the harvest equilibrium (an overshoot in the recovery exceeds 1 %)", "instantaneous stock", "delayed-feedback overshoot in harvest control", "REDUNDANT-DOMAIN"),
 # ---- P09 economics and finance
 ("P09-1", 9, "econ", "volatility of returns simulated from GARCH(1,1) (omega 0.05, alpha 0.1, beta 0.85)", "A6", "an A6 bounded mean of squared returns forecasts volatility as well as GARCH (within 1 % in MSE)", "GARCH", "GARCH(1,1) is an exponentially weighted variance plus a constant", "REDUNDANT-DOMAIN"),
 ("P09-2", 9, "econ", "Kaldor business cycle (nonlinear investment) with A6-remembered income", "A6", "memory shrinks the limit-cycle amplitude by more than 1 %", "instantaneous income", "none cited", "ADDS"),
 ("P09-3", 9, "econ", "Metzler inventory cycle with sales expectations by A6", "A6", "the inventory cycle's damping increases with memory (more negative real part)", "naive expectations", "Metzler: stability depends on the expectation coefficient", "REDUNDANT-DOMAIN"),
 ("P09-4", 9, "econ", "intertemporal choice: A6 geometric weights as the discount function", "P3", "P3 geometric weights predict time-consistent choices (no preference reversal), against hyperbolic discounting", "hyperbolic discounting", "exponential discounting is time-consistent (Strotz)", "REDUNDANT-DOMAIN"),
 ("P09-5", 9, "econ", "a random-walk price with regime shifts: trading on A3 cuts of the price phase", "A3", "a strategy trading at antipodal cuts earns a positive mean return net of zero cost", "buy-and-hold", "efficient markets: no predictable return on a random walk", "WRONG"),
 # ---- P10 social systems and networks
 ("P10-1", 10, "soc", "DeGroot opinion averaging on a ring of 50 agents with A6 memory of neighbours' opinions", "A6", "consensus value unchanged; convergence slower by more than 1 %", "instantaneous opinions", "DeGroot: consensus at the eigenvector-weighted mean", "ADDS"),
 ("P10-2", 10, "soc", "Hawkes self-exciting process (exponential kernel, branching 0.6)", "A6", "the A6 geometric kernel reproduces the Hawkes intensity: identical to the exponential-kernel Hawkes process", "no memory (Poisson)", "the Hawkes process with exponential kernel", "REDUNDANT-DOMAIN"),
 ("P10-3", 10, "soc", "Schelling segregation (tolerance 0.4) with A6-remembered neighbourhood composition", "A6", "memory lowers the final segregation index by more than 1 %", "instantaneous neighbourhood", "none cited", "PROPOSES"),
 ("P10-4", 10, "soc", "Nagel-Schreckenberg traffic (p = 0.3) with drivers braking on A6-remembered headway", "A6", "memory raises the density of the jam transition by more than 1 %", "instantaneous headway", "anticipation models raise capacity", "ADDS"),
 ("P10-5", 10, "soc", "Daley-Kendall rumour spreading with A6-remembered encounters", "A6", "the final fraction never hearing the rumour (0.203 without memory) changes by more than 1 %", "instantaneous", "Daley-Kendall: 0.203", "WRONG"),
 # ---- P11 physiology and health
 ("P11-1", 11, "phys", "Bergman minimal glucose-insulin model: glucose after a meal", "A6", "remote insulin action X is already an exponential memory: adding A6 changes the glucose nadir by less than 1 %", "the model's own X", "Bergman's remote compartment", "REDUNDANT-DOMAIN"),
 ("P11-2", 11, "phys", "Borbely two-process sleep model: sleep onset as a cut", "A3", "sleep onset occurs at the antipode of the circadian process C phase from the last wake-up", "the S-threshold crossing", "the two-process model: onset when S meets the upper C threshold", "WRONG"),
 ("P11-3", 11, "phys", "respiratory sinus arrhythmia: heart period modulated by breathing", "H-L5", "arc of the heart-period signal per breath is more regular than the breath duration", "CV(breath duration)", "none", "WRONG"),
 ("P11-4", 11, "phys", "repeated drug dosing with first-order elimination: trough levels", "A6", "the steady-state trough under A6 accumulation equals the pharmacokinetic accumulation factor", "no memory", "accumulation factor 1/(1 - e^{-kT})", "REDUNDANT-DOMAIN"),
 ("P11-5", 11, "phys", "menstrual-cycle hormone model (Keener-style) with noise: ovulation as own event", "H-L5", "CV(arc between ovulations) < CV(cycle length)", "CV(cycle length)", "none", "WRONG"),
 # ---- P12 climate and earth systems
 ("P12-1", 12, "clim", "Budyko-Sellers energy balance with ice-albedo feedback: hysteresis width", "A6", "an A6-remembered ice line widens the hysteresis loop by more than 1 %", "instantaneous ice line", "the static bistability: the loop width is a property of the equilibria", "REDUNDANT-IG"),
 ("P12-2", 12, "clim", "Stommel two-box thermohaline circulation with slow freshwater forcing", "H-CUT (A3)", "collapse occurs at the antipode of the circulation carrier (half the arc from on to off)", "the saddle-node point", "Stommel: collapse at the saddle-node bifurcation", "WRONG"),
 ("P12-3", 12, "clim", "Daisyworld with A6-remembered temperature in daisy growth", "A6", "memory narrows the range of luminosity over which temperature is regulated by more than 1 %", "instantaneous temperature", "none cited", "ADDS"),
 ("P12-4", 12, "clim", "Saltzman-style glacial oscillator (ice, CO2, deep ocean) with noise", "H-L5", "CV(arc per glacial cycle) < CV(cycle period)", "CV(period)", "none", "WRONG"),
 ("P12-5", 12, "clim", "annual river floods (Gumbel maxima): recurrence of the 10-year flood in natural time", "A1' natural time", "exceedances counted in natural time (events) are Poisson with the same rate as in clock time", "clock time", "return-period theory: Poisson exceedances", "REDUNDANT-DOMAIN"),
 # ---- P13 engineering and control
 ("P13-1", 13, "ctrl", "PI controller with actuator saturation: integral windup", "A6", "a bounded (A6) integral reduces overshoot after saturation by more than 1 % against the plain integral", "plain integral", "anti-windup (leaky or clamped integrator)", "REDUNDANT-DOMAIN"),
 ("P13-2", 13, "ctrl", "relay (bang-bang) thermostat with hysteresis: switching events", "H-CUT (A3)", "switching occurs at the antipode of the temperature cycle's phase", "the hysteresis thresholds", "relay feedback: switching at the thresholds (describing function)", "REDUNDANT-DOMAIN"),
 ("P13-3", 13, "ctrl", "M/M/1 queue (rho = 0.8): busy periods in natural time (customers served)", "A1' natural time", "busy periods are less variable in customers served than in clock time", "clock time", "busy-period distributions (Kendall): both known", "REDUNDANT-DOMAIN"),
 ("P13-4", 13, "ctrl", "TCP AIMD congestion window sawtooth with random loss", "H-L5", "the window arc between losses is more regular than the time between losses", "CV(time between losses)", "AIMD sawtooth: loss times Poisson", "WRONG"),
 ("P13-5", 13, "ctrl", "exponential smoothing (Holt) forecasting of a trend with level shifts", "A6", "A6 with q = 0.5 equals simple exponential smoothing with alpha = 0.5", "no memory", "simple exponential smoothing", "REDUNDANT-DOMAIN"),
 # ---- P14 agents, AI and information
 ("P14-1", 14, "ai", "non-stationary Bernoulli bandit (arms swap every 500 steps): discounted UCB against A6 bounded-mean UCB", "A6", "A6 bounded-mean UCB has lower regret than sliding-window UCB by more than 1 %", "sliding-window UCB", "discounted UCB (Garivier-Moulines) is A6 with geometric weights", "REDUNDANT-DOMAIN"),
 ("P14-2", 14, "ai", "a two-state MDP agent with an off-switch pressed at random times, valuation on own steps", "Proposition 7", "the own-step valuation has zero stake: V_on = V_off to round-off", "wall-clock valuation", "utility indifference (Armstrong); POST (Thornley)", "REDUNDANT-DOMAIN"),
 ("P14-3", 14, "ai", "recommender feedback loop: filter bubble under engagement vs A6-remembered interests", "A6", "remembered interests slow the collapse of topic diversity by more than 1 %", "instantaneous interests", "none cited", "ADDS"),
 ("P14-4", 14, "ai", "federated averaging with stragglers: server update on A6-remembered client updates", "A6", "A6 server momentum lowers the final loss by more than 1 % against plain FedAvg", "FedAvg", "FedAvgM (server momentum, Hsu et al.)", "REDUNDANT-DOMAIN"),
 ("P14-5", 14, "ai", "language-model perplexity drift on a shifting token stream: A6 bounded unigram model", "A6", "an A6 unigram tracker has lower cross-entropy than the cumulative-count unigram after a shift", "cumulative counts", "cache / recency language models (Kuhn and De Mori)", "REDUNDANT-DOMAIN"),
]

FORECASTS = {p[0]: p[8] for p in P}
assert len(P) == 70 and len({p[0] for p in P}) == 70
