"""Build docs/pedagogy/ELEGANCE_LEDGER.md from the pinned synthesis outputs (owner request 2026-09-17,
prompt-log entry 61): every row that carries an `elegance:` or `child:` line, in battery and row order.
The ledger is a record of pedagogical easement and elegance noticed while running the SYNTHESIS class. It is
not evidence, not a curated result (R8: ledger/LEDGER.md is the only curated table), and every number in it
is a number the pinned row prints. Deterministic. Run:
uv run python docs/pedagogy/build_elegance_ledger.py > docs/pedagogy/ELEGANCE_LEDGER.md
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCES = [ROOT / "theory/retrodictions/synthesis.txt"] + sorted((ROOT / "theory/retrodictions/synthesis_batches").glob("batch_*.txt"))


def parse(text):
    rows, cur = [], None
    for line in text.splitlines():
        m = re.match(r"^\[ *(\d+)\] \(([^)]*)\) (.*)$", line)
        if m:
            cur = dict(n=int(m.group(1)), cls=m.group(2), system=m.group(3).strip()); rows.append(cur); continue
        m = re.match(r"^\s+(source|Q|OUTCOME|elegance|child):\s+(.*)$", line)
        if m and cur is not None:
            cur[m.group(1)] = m.group(2).strip()
    return rows


def main():
    print("# Elegance ledger: pedagogical easement noticed while running the SYNTHESIS class")
    print()
    print("Generated by `build_elegance_ledger.py` from the pinned synthesis outputs (prompt-log entry 61).")
    print("A record, not evidence: elegance never changes an outcome, and the outcome beside each entry is the")
    print("row's computed label (ADDS is always a candidate pending expert review). Every number here is one the")
    print("pinned row prints. The child line is a fifth-grader explanation of the principle the row shows,")
    print("for teaching it to children, families and communities; it is not a claim that the principle is true")
    print("of the world, only that it can be carried in plain words.")
    print()
    total = 0
    for src in SOURCES:
        rows = [r for r in parse(src.read_text()) if r.get("elegance") or r.get("child")]
        if not rows:
            continue
        print(f"## {src.relative_to(ROOT)}")
        print()
        for r in rows:
            total += 1
            print(f"### [{r['n']}] {r['system']}")
            print()
            if r.get("source"):
                print(f"- source row: {r['source']}")
            print(f"- outcome: {r.get('OUTCOME', '?')}")
            if r.get("elegance"):
                print(f"- elegance: {r['elegance']}")
            if r.get("child"):
                print(f"- for a fifth grader: {r['child']}")
            print()
    print(f"Entries: {total}.")


if __name__ == "__main__":
    main()
